.gitignore
lib/components/artist/shows.js
lib/containers/artist.js

Added a Shows component!

---

lib/components/artist/show.js
lib/components/artist/shows.js

Should I add Pods back to the gitignore?

[Shows] Added a ShowView submodule

---

Emission.podspec
Example/Emission.xcodeproj/xcshareddata/xcschemes/Emission.xcscheme
Example/Emission/AppDelegate.m
Example/Podfile.lock
Example/Pods/Headers/Private/Emission/ARTemporaryAPIModule.h
Example/Pods/Headers/Public/Emission/ARTemporaryAPIModule.h
Example/Pods/Local Podspecs/Emission.podspec.json
Example/Pods/Manifest.lock
Example/Pods/Pods.xcodeproj/project.pbxproj
Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Emission.xcscheme
Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/React-Core-RCTNetwork-RCTText-RCTWebSocket.xcscheme
Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
lib/components/artist/header.js
lib/components/buttons/inverted_button.js

Until we do this through metaphysics (#15), this module makes it possible to use Eigen’s existing API code to get/set the artist follow status.

[Artist] Add support to get/set follow status

---

lib/components/artist/article.js
lib/components/artist/articles.js
lib/components/artist/articles/article.js
lib/components/artist/articles/index.js
lib/containers/artist.js

Articles rail

---

Example/node_modules/remove-markdown/.npmignore
Example/node_modules/remove-markdown/LICENSE
Example/node_modules/remove-markdown/README.md
Example/node_modules/remove-markdown/index.js
Example/node_modules/remove-markdown/package.json
Example/node_modules/remove-markdown/test/markdown.md
Example/node_modules/remove-markdown/test/remove-markdown.js
Example/node_modules/remove-markdown/test/result.txt
lib/components/artist/biography.js
lib/components/text/serif.js
node_modules/remove-markdown/.npmignore
node_modules/remove-markdown/LICENSE
node_modules/remove-markdown/README.md
node_modules/remove-markdown/index.js
node_modules/remove-markdown/package.json
node_modules/remove-markdown/test/markdown.md
node_modules/remove-markdown/test/remove-markdown.js
node_modules/remove-markdown/test/result.txt
package.json

Fixes #31.
For now we strip markdown, as rendering it would probably cause some surprise gotchas. See #42 for future work.

[Artist Bio] Add blurb

---

lib/components/artist/articles/index.js
lib/components/artist/related_artists/index.js
lib/components/artist/shows/index.js
lib/components/artist/shows/large_list.js
lib/components/separator.js

[Shows] Fixed vertical spacing and separator on shows tab

---

lib/components/artist/articles/article.js
lib/components/artist/related_artists/related_artist.js

Use cropped image URLs from metaphyics

---

Example/Emission/AppDelegate.m
Pod/Classes/Core/AREmissionFontsLoader.m
Pod/Classes/Core/RCTScrollView+EnclosingScrollView.m
lib/components/artist/articles/article.js
lib/components/artist/articles/index.js
lib/components/artist/shows/large_list.js
lib/components/artist/shows/small_list.js
lib/components/artworks/artwork.js
lib/components/artworks/grid.js
lib/components/artworks/index.js
lib/components/opaque_image_view.js
lib/containers/artist.js

Fixes #51.
Still need to add works count next to section title.
Currently I don’t paginate the ‘for sale’ section, so need to find the artist with the most for sale works and see if that would be an issue right now or if we can delay worrying about that till post v1.

Artworks styling

---

Example/Emission/AppDelegate.m
Pod/Classes/Core/AREmissionFontsLoader.m
lib/components/artist/shows/large_list.js
lib/components/artist/shows/small_list.js
lib/components/artworks/artwork.js
lib/components/artworks/grid.js
lib/components/artworks/index.js
lib/components/opaque_image_view.js
lib/containers/artist.js

[Artworks] First paginate for sale works, then when depleted paginate other works.

---

lib/components/artist/artworks/grid.js

[Artworks] Fetch next page long before user (typically) reaches end of view.

---

lib/components/artist/header.js

Found myself battling this optimistic choice from Eigen. I will still be optimistic, but completely from Eigen’s side, not the component itself.

[Header] Let selected state toggling completely up to host app.

---

lib/components/artist/about.js
lib/components/artist/articles/article.js
lib/components/artist/artworks/artwork.js
lib/components/artist/artworks/index.js
lib/components/artist/biography.js
lib/components/artist/related_artists/related_artist.js
lib/components/artist/shows/index.js
lib/components/artist/shows/large_image_show.js
lib/components/artist/shows/medium_image_show.js
lib/components/artist/shows/metadata.js
lib/components/artist/shows/small_image_show.js

Fixes #68.
Fixes #67.
Fixes #66.
Fixes #64.
Will fix #65.

QA work for null states

---

lib/components/artist/articles/index.js
lib/components/artist/artworks/grid.js
lib/components/artist/shows/small_list.js
lib/containers/artist.js

- Scroll to top: #103 
- Remove horizontal scroller from articles component #83

Scrollview fixes

---

lib/components/artist/artworks/index.js

[Artworks] Include page query generator when artist only has not for-sale works.

---

lib/components/artist/header.js
lib/components/artist/shows/metadata.js
lib/components/text/serif.js

Too many PRs...
Fixes #93 
Fixes #92 
Fixes #84

Miscellaneous QA

---

lib/components/artist/about.js
lib/components/artist/biography.js

[About] Section hides related artists and/or bio if nonexistent

---

lib/components/artist/header.js

[Header] Added parsing for artist birthday and nationality in header

---

lib/components/artist/related_artists/related_artist.js

[RelatedArtists] Fixed artwork count string

---

lib/components/artist/related_artists/index.js
lib/components/artist/related_artists/related_artist.js
lib/components/artist/shows/medium_image_show.js
lib/components/artist/shows/medium_list.js

Fixed grid alignment in Related Artists and Past Shows on iPad

---

lib/components/artist/biography.js

[Biography] Fix truncation + Replace born with abbreviation

---

Pod/Classes/OpaqueImageViewComponent/AROpaqueImageView.m
lib/components/artist/related_artists/related_artist.js
lib/components/opaque_image_view.js

Fixes #94.
Also immediately show the placeholder color.

Fix crash when artist has no image.

---

lib/components/artist/biography.js
lib/components/artist/header.js
lib/components/artist/related_artists/related_artist.js
lib/components/artist/shows/index.js
lib/components/artist/shows/large_image_show.js
lib/components/artist/shows/large_list.js
lib/components/artist/shows/medium_image_show.js
lib/components/artist/shows/medium_list.js
lib/components/separator.js
lib/containers/artist.js

Assorted QA items

---

data/schema.graphql
data/schema.json
lib/components/artist/artworks/grid.js
lib/components/artist/artworks/index.js

This matches the sort order on https://www.artsy.net/artist/banksy/works 🌻
Fixes #99

Changed artworks sort to updated_at

---

Pod/Classes/SwitchViewComponent/ARSwitchViewManager.m

Aaand here we are again!
Fix #89 
As mentioned before, the change of text colours would need to be done within `ARSwitchView` in Extraction, will submit that also.

[SwitchView] Add top and bottom indicators for unselected tabs

---

lib/components/artist/artworks/artwork.js
lib/components/artist/artworks/grid.js

Fixes https://github.com/artsy/eigen/issues/1559
Fixes https://github.com/artsy/eigen/issues/1558

Updates to artwork metadata

---

Pod/Classes/Core/RCTScrollView+EnclosingScrollView.m

[RCTScrollView] Revert the monkey-patch changes for RN 0.25.1

---

lib/components/artist/related_artists/related_artist.js
lib/containers/artist.js

[WIP] Proposed solution for tab view

---

lib/components/artist/articles/article.js

[Articles] Use thumbnail title.

---

Example/Emission/AppDelegate.m
lib/components/artist/shows/large_image_show.js
lib/components/artist/shows/medium_image_show.js
lib/components/artist/shows/small_image_show.js

[Show] Guard against missing image

---

lib/components/artist/articles/article.js
lib/components/artist/related_artists/related_artist.js
lib/components/artist/shows/large_image_show.js
lib/components/artist/shows/medium_image_show.js
lib/components/artist/shows/small_image_show.js
lib/components/opaque_image_view.js

[ImageView] Load cropped images that take screen pixel ratio into account.

---

lib/components/artist/related_artists/index.js
lib/components/artist/related_artists/related_artist.js

Fix #131 
cc @katarinabatina, this is what I went with:

[Related Artists] Fix left margin of grid view

---

Example/Podfile.lock
Example/Pods/Extraction/Extraction/Classes/ARSpinner.m
Example/Pods/Extraction/Extraction/Classes/ARSwitchView.m
Example/Pods/Extraction/Extraction/Classes/UIView+ARSpinner.m
Example/Pods/Manifest.lock
Pod/Classes/SwitchViewComponent/ARSwitchViewManager.m
lib/components/switch_view.js
lib/containers/artist.js

Fix #90, history of this PR in #142.

[SwitchView] Set default tab selection to 'Works'

---

lib/components/artist/shows/index.js
lib/components/artist/shows/small_list.js

Fix #147. 
(as well as error mentioned [here](https://github.com/artsy/emission/pull/150#discussion_r65533101))

[Shows] Hide "Past Shows" if none exist

---

lib/components/artist/shows/index.js

because I'm bad at writing javascript, it seems.

[Shows] Use length instead of count

---

Pod/Classes/ViewControllers/ARArtistComponentViewController.h
Pod/Classes/ViewControllers/ARArtistComponentViewController.m
lib/components/artist/header.js
lib/containers/artist.js

Kinda silly of me to try to capture analytics data that we didn’t actually fetch.

[Events] Actually fetch required event data and expose the artist VC’s artist ID.

---

Example/Emission/AppDelegate.m
data/schema.graphql
data/schema.json
lib/components/artist/about.js
lib/components/artist/shows/index.js
lib/containers/artist.js

Using dummy variables until https://github.com/artsy/metaphysics/pull/298 is merged.

Hides about section if it shouldn't exist, and hides tab bar altogether if there isn't anything to show

---

lib/components/artist/header.js

[Header] Fix follower string to be singular when only 1 follow

---

lib/components/artist/artworks/artwork.js

[Artworks] Remove title space if no title available for artwork

---

lib/components/artist/header.js

Followers count now changes when follow button is pressed

---

lib/components/artist/articles/article.js
lib/components/artist/artworks/grid.js
lib/components/artist/header.js
lib/containers/artist.js

Fixes https://github.com/artsy/eigen/issues/1616, https://github.com/artsy/eigen/issues/1667, and https://github.com/artsy/eigen/issues/1670. It _might_ fix https://github.com/artsy/eigen/issues/1619, but that’s just a guess atm.

Fix crashes.

---

Example/Emission.xcodeproj/project.pbxproj
Example/Podfile.lock
lib/components/artist/shows/metadata.js

Looking into the Podfile and pbxproj weirdness.
Fixes #185

[Shows] Fixed crasher for shows without partner

---

lib/relay/config.js

[Relay] Add network request debugger in dev env.

---

Example/Emission/AppDelegate.m
Pod/Classes/ViewControllers/ARHomeComponentViewController.h
Pod/Classes/ViewControllers/ARHomeComponentViewController.m
data/schema.graphql
data/schema.json
lib/app_registry.js
lib/containers/home.js
lib/containers/index.js
lib/relay/routes.js

I am getting this error: ``Application Artist has not been registered``
I tried changing things in the app registry and relay routes but to no avail.

Added a Home container

---

Emission.podspec
package.json
scripts/release.js

Fix npm version parsing in podspec and add release task.

---

.gitignore
Example/Emission.xcodeproj/project.pbxproj
Example/Emission/AppDelegate.m
Example/Emission/Configuration.h.sample
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m
README.md
data/schema.graphql
data/schema.json
lib/relay/config.js

Fixes #190.
Be sure to read the instructions added to the README for how to configure your setup.

[Relay] Add user authentication support.

---

lib/containers/home.js

[Home] Defer rails content fetching.

---

data/schema.graphql
data/schema.json
lib/containers/home.js

React needs unique view keys to be able to identify views later on.
Also pulls in the recent metaphysics schema additions you both made.

Unique generic gene rails ids

---

data/schema.graphql
data/schema.json
lib/components/home/rail.js
lib/containers/home.js

With this, content for some rails can start to render before all content is fetched.

[Home] Per rail content fetching

---

data/schema.graphql
data/schema.json

Fixes https://github.com/artsy/emission/issues/205

[schema] sync

---

Example/Emission/AppDelegate.m
Example/Emission/Configuration.h.sample
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m
data/schema.graphql
data/schema.json
lib/components/home/artist_rail.js
lib/components/home/artwork_rail.js
lib/containers/home.js
lib/relay/config.js

@sarahscott @mennenia Be sure to read updated instructions for the configuration file!

[Home] Show artist rails.

---

dependencyci.yml

[DependencyCI] Skip deprecation check on transitive dep.

---

Example/Podfile.lock
npm-shrinkwrap.json
package.json

No apparent layout changes or concerns 🎉

Upgraded to RN v0.30.0 🐬

---

lib/components/home/artwork_rail.js

This is a preliminary go at a nice way to do the initial state. I will follow up soon with a final state and my first go at animating between the two.

[HomeArtworkRail] Rail layout for initial state

---

CHANGELOG.md
Dangerfile.js
Gemfile.lock

JS Dangerfiles are completely new, so this might take some iteration.

[Danger] Initial scoping for Danger

---

CHANGELOG.md
lib/components/home/artwork_rails/artwork_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js
lib/components/home/artwork_rails/relay_fragments.js

Routing for existing contexts:

[Home][ArtworkRail] Routing for header

---

Dangerfile.js

Improve code style

---

CHANGELOG.md
lib/components/home/artist_rails/artist_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js
lib/components/home/section_title.js

[Home][ArtistRail] Added header and separator to artist rail

---

lib/components/artist/shows/large_list.js
lib/components/artist/shows/medium_list.js
lib/components/artist/shows/metadata.js

[ArtistVC] Fixed bug in past shows iPad layout

---

CHANGELOG.md
Example/Podfile.lock
Pod/Classes/LoadFailureComponent/ARLoadFailureViewManager.h
Pod/Classes/LoadFailureComponent/ARLoadFailureViewManager.m
lib/app_registry.js
lib/components/load_failure_view.js

Fixes https://github.com/artsy/eigen/issues/1429

[LoadFailure] Show a pretty view when loading fails and allows retrying.

---

lib/components/home/artist_rails/artist_rail.js

[Artist Rail] Add margin at the end #trivial

---

lib/components/home/artwork_rails/artwork_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js

[Home][ArtworksRail] Updated routing

---

CHANGELOG.md
lib/components/home/artist_rails/artist_rail.js
lib/components/home/artwork_rails/artwork_rail.js

Simpleee, but effective. 
Was there even an issue for this?

[Home] Add minimum height to avoid loading jumps

---

Example/Emission/AppDelegate.m
npm-shrinkwrap.json
package.json

https://github.com/facebook/relay/pull/1367/files

[package] Update Relay to 0.9.3

---

CHANGELOG.md
lib/containers/home.js

Does it actually have to be 999 or is 50 ok for now 😄 ?
Related to https://github.com/artsy/metaphysics/issues/410
Fixes #274

[Home][ArtworkRail] Set a max of 99 artwork rails

---

lib/components/artwork_grids/generic_grid.js

There's a small delay for image-loading but it could be because it's in the simulator:
Fixes #280

[Home][ArtworkRail] Support for landscape iPad layout

---

CHANGELOG.md
Pod/Classes/SpinnerComponent/ARSpinnerManager.m
data/schema.graphql
data/schema.json
lib/components/artwork_grids/infinite_scroll_grid.js
lib/components/home/artist_rails/artist_card.js
lib/components/home/artist_rails/artist_rail.js
lib/components/spinner.js
lib/metaphysics.js

* The Relay warnings shown are because I’m not using Relay to populate the components with data. You can ignore them.
* The layout breaks with some artists, not sure if that’s to do with the replacing or just the data they have. Needs to be inspected further.

[Home/Artist] Add follow action to artists in artist rail.

---

lib/components/artist/header.js
lib/components/home/artist_rails/artist_card.js
lib/components/home/artist_rails/artist_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js

No need to perform these `__DEV__` checks ourselves.

`console.error` only logs in production #tiny

---

lib/components/artwork_grids/generic_grid.js

`Dimensions` is less reliable on-device as it is in the sim.

[Home][ArtworksRail] Fix for layout issues on-device #tiny

---

.vscode/settings.json
CHANGELOG.md
Example/Emission/storybook.js
Example/Podfile.lock
lib/__mocks__/react-relay.js
lib/app_registry.js
lib/components/__tests__/seperator-tests.js
lib/components/gene/header.js
lib/containers/__tests__/__snapshots__/gene-tests.js.snap
lib/containers/__tests__/gene-tests.js
lib/containers/gene.js
lib/relay/routes.js
npm-shrinkwrap.json
package.json
stories/artist_articles_story.js
stories/artist_component_story.js
stories/artist_header_story.js
stories/gene_component_story.js

Note: Currently not exposing it outside of the storybook interface, I guess it can be used via Eigen's admin once there's an emission deploy too.
---
I've fixed a few places where ESLint didn't run to remove the `;`, which adds some noise, I've not touched any of those files except to clean them to our standards while looking through the the app.
This updates us to Jest 15, biggest change is that it now automocks a lot more RN classes, https://github.com/facebook/jest/pull/1516 - it's not totally optimal, those mocks give warnings as you can see in the build ( [or here](https://cloud.githubusercontent.com/assets/49038/18782581/1422fcb6-817f-11e6-8547-60a5538d73dd.png) ) as I work on this, I'll figure those out. Just learned how to do JS mocking in  general.
---
Will comment inline

[Gene] Initial work on a Gene relay container

---

lib/components/home/artist_rails/artist_rail.js

[Home/Artist] Center spinner while loading. #trivial

---

Pod/Classes/Core/AREmission.m

Ensure we have required configuration. #trivial

---

CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
Example/Emission/Emission.entitlements
Example/Podfile.lock

I was seeing this on every launch
Which doesn't save the credentials, so I looked up why, turns out to be a bug in keychain itself. The workaround is to turn on keychain sharing: https://forums.developer.apple.com/thread/4743
This does just that.

Adds Keychain sharing

---

CHANGELOG.md
lib/containers/gene.js
npm-shrinkwrap.json
package.json

Oooook, that's got one of the trickiest bits in, handling the scroll locking inside the scroll
These changes are super documented, so it's better to read the source than for me to re-write it here.

[Gene] Scroll locking

---

Example/Emission.xcodeproj/project.pbxproj
Example/Emission/AppDelegate.m
Example/Emission/AuthenticationManager.h
Example/Emission/AuthenticationManager.m

Turns out I got something wrong on the staging flag, it wouldn't correctly authenticate on staging ( as the check was elsewhere ) 
So I moved all the authentication into another class. Now the AppDelegate really is only about Emission + view setup 👍

Move auth out of the AppDelegate

---

CHANGELOG.md
Example/Emission.xcodeproj/xcshareddata/xcschemes/Emission.xcscheme
Example/Emission/ARRootViewController.m
Example/Emission/AppDelegate.m
Example/Emission/AuthenticationManager.m
Example/Emission/Info.plist
Example/Emission/UnroutedViewController.m
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m
Pod/Classes/EigenCommunications/ARRefineOptionsModule.h
Pod/Classes/EigenCommunications/ARRefineOptionsModule.m
Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
lib/components/artist/header.js
lib/components/gene/header.js
lib/containers/gene.js
lib/native_modules/refine_callback.js

[Gene] Get the GeneVC hooked up with all native modules for Eigen

---

CHANGELOG.md
lib/components/home/artist_rails/artist_card.js
lib/components/home/artwork_rails/artwork_rail_header.js
lib/components/home/hero_units.js

Fixes https://github.com/artsy/eigen/issues/1921 & https://github.com/artsy/eigen/issues/1912

Fix crasher and banner size on ipad

---

Pod/Classes/ViewControllers/ARComponentViewController.m
lib/containers/artist.js
lib/containers/home.js

This fixes the finicky margin between the top of Home and the status bar.

[Home] Fix for status bar inconsistency #tiny

---

.gitignore
Example/Emission/ARRootViewController.m
Example/Emission/AppDelegate.m
Pod/Classes/ViewControllers/ARGeneComponentViewController.h
Pod/Classes/ViewControllers/ARGeneComponentViewController.m
lib/components/buttons/flat_white.js
lib/components/home/artwork_rails/artwork_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js
lib/containers/__tests__/gene-tests.js
lib/containers/gene.js
lib/native_modules/refine_callback.js

Adds ARGeneComponentVC, adds query params for generic_genes

---

Example/Emission/AppDelegate.m
Pod/Classes/ViewControllers/ARGeneComponentViewController.m
data/schema.graphql
data/schema.json
docs/running-emission-in-eigen.md
index.ios.js
lib/app_registry.js
lib/components/artwork_grids/infinite_scroll_grid.js
lib/components/buttons/flat_white.js
lib/components/gene/artworks.js
lib/components/gene/header.js
lib/components/home/artwork_rails/artwork_rail.js
lib/containers/__tests__/gene-tests.js
lib/containers/gene.js
lib/relay/config.js
lib/relay/routes.js
rn-cli.config.js

Creates the real infrastructure for passing in refine settings, and having those passed onwards to metaphysics.

Pass refine settings into the Gene component

---

lib/components/home/artist_rails/artist_rail.js
lib/components/home/artwork_rails/artwork_rail.js

For #333 
I personally think this is even worse than infinite spinners. 
With infinite spinners the user might think something got stuck and will kill the app to try and reload. Now, it's empty, and they may have no clue what to do about that or understand that a force restart of the app would help. It just looks like the app decided to be broken, with no indication why. 
This is just my view... I completely understand the step-by-step approach and that we ideally want it to just refresh and work.

[Home] Set rails to null during network failure

---

lib/containers/gene.js

[Gene] only for sale

---

Pod/Classes/ViewControllers/ARArtistComponentViewController.m
Pod/Classes/ViewControllers/ARComponentViewController.m
Pod/Classes/ViewControllers/ARHomeComponentViewController.m

so it applies to all subclasses - should fix #370 and #368

Moves authomaticallAdjustsScrolls to the base ARComponentVC 

---

CHANGELOG.md
data/schema.graphql
data/schema.json
lib/containers/home.js
lib/relay/config.js

[Home] Include all followed genes and fix order.

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARComponentViewController.m
Pod/Classes/ViewControllers/ARHomeComponentViewController.m

[VC] Align home to screen top, otherwise default to status bar bottom.

---

CHANGELOG.md
Example/Podfile.lock
npm-shrinkwrap.json
package.json

Release 1.1.1

---

CHANGELOG.md
Example/Emission/AppDelegate.m
Example/Podfile.lock
lib/components/home/hero_units.js

Fixes https://github.com/artsy/eigen/issues/1948

Larger banner font size on ipad

---

CHANGELOG.md
lib/containers/gene.js

[Gene] Disable refine button.

---

CHANGELOG.md
lib/components/artist/about.js

[Artist] Fix link to auction results.

---

.travis.yml
lib/containers/__tests__/__snapshots__/gene-tests.js.snap
lib/containers/__tests__/gene-tests.js

I started looking at adding the refine button back, but until I'm sure what the problem was, I couldn't really find any.
This PR doesn't add it back, but it does add back the tests that I removed from the Gene component. I can add the refine button back in another PR.

Update tests for the Gene Component

---

.travis.yml
lib/components/__tests__/__snapshots__/tab_view-tests.js.snap
lib/components/__tests__/tab_view-tests.js
lib/components/gene/__tests__/__snapshots__/about-test.js.snap
lib/components/gene/__tests__/about-test.js

https://github.com/yarnpkg/yarn/issues/764 seems to imply it is likely to help ( see https://github.com/yarnpkg/yarn/issues/764#issuecomment-256995983 )

Use node 6.7 on travis

---

README.md

A couple steps I needed to do to get this setup.

@alloy => Add a couple of steps to Installation

---

Example/Podfile

Re: https://github.com/artsy/emission/issues/418 - I think we need to do what Eidolon did here:
https://github.com/artsy/eidolon/pull/627/files#diff-4a25b996826623c4a3a4910f47f10c30L32

Use the podspec repos for fonts

---

CHANGELOG.md
lib/components/artwork_grids/__tests__/__snapshots__/artwork-tests.js.snap
lib/components/artwork_grids/__tests__/__snapshots__/generic-grid-tests.js.snap
lib/components/artwork_grids/__tests__/__snapshots__/infinite-scroll-grid-tests.js.snap
lib/components/artwork_grids/__tests__/artwork-tests.js
lib/components/artwork_grids/__tests__/generic-grid-tests.js
lib/components/artwork_grids/__tests__/infinite-scroll-grid-tests.js

These are basic snapshot tests for the artwork grids; they all definitely need additional logic tests but that will be done in a new PR (feel free to take them on 😉 ).

[Testing] Snapshot coverage for artwork grid components

---

CHANGELOG.md
lib/components/buttons/__tests__/__snapshots__/flat-white-tests.js.snap
lib/components/buttons/__tests__/__snapshots__/inverted-button-tests.js.snap
lib/components/buttons/__tests__/__snapshots__/navigation-button-tests.js.snap
lib/components/buttons/__tests__/flat-white-tests.js
lib/components/buttons/__tests__/inverted-button-tests.js
lib/components/buttons/__tests__/navigation-button-tests.js

[Testing] Added snapshots for all buttons

---

CHANGELOG.md
lib/components/artist/articles/index.js
lib/components/gene/__tests__/__snapshots__/header-tests.js.snap
lib/components/gene/header.js
lib/components/text/headline.js

Fixes https://github.com/artsy/eigen/issues/1996

Clips header text in gene page

---

README.md
package.json
yarn.lock

Adds react native debugger command and instructions

---

dangerfile.js
package.json
yarn.lock

Making sure the newly added PR danger rules work correctly.

Added rules to dangerfile

---

CHANGELOG.md
data/schema.graphql
data/schema.json
lib/components/artist/__tests__/__snapshots__/artworks-tests.js.snap
lib/components/artist/artworks/index.js
lib/components/artwork_grids/__tests__/infinite-scroll-grid-tests.js
lib/components/artwork_grids/infinite_scroll_grid.js
lib/containers/__tests__/__snapshots__/gene-tests.js.snap
lib/containers/gene.js

@alloy - Gene fix

---

CHANGELOG.md
Example/Emission/ARRootViewController.m
Example/Emission/AppDelegate.m
Pod/Classes/ViewControllers/ARWorksForYouComponentViewController.h
Pod/Classes/ViewControllers/ARWorksForYouComponentViewController.m
data/schema.graphql
data/schema.json
src/lib/app_registry.tsx
src/lib/components/works_for_you/notification.tsx
src/lib/containers/__tests__/__snapshots__/works-for-you-tests.tsx.snap
src/lib/containers/__tests__/works-for-you-tests.tsx
src/lib/containers/index.tsx
src/lib/containers/works_for_you.tsx
src/lib/relay/routes.tsx

The metaphysics response doesn't include the artist image for the avatar, so I'm going to get this tested and ready to merge without it and then get that set up in metaphysics. Also, tests are failing on this branch that I believe are fixed in the main `typescript` branch, so I will write tests for this as soon as it's merged.

[WorksForYou] Started on new container

---

CHANGELOG.md
Example/Emission/AppDelegate.m
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m
Pod/Classes/EigenCommunications/ARWorksForYouModule.h
Pod/Classes/EigenCommunications/ARWorksForYouModule.m
Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
src/lib/containers/__tests__/works-for-you-tests.tsx
src/lib/containers/works_for_you.tsx

Adds a way to replace [this](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/WorksForYou/ARWorksForYouViewController.m#L170)

Updates notifications using native module

---

CHANGELOG.md
Example/Podfile.lock
lib/containers/home.js

Needs to be cherry-picked onto master as well.
/cc @ashfurrow

Move active bids to top of home view

---

CHANGELOG.md
lib/components/home/artwork_rails/artwork_rail.js

Fixes https://github.com/artsy/eigen/issues/2237

Fixes display of artworks in non-expanding grids in artwork rails

---

Example/Podfile.lock

Sibling PR to https://github.com/artsy/eigen/pull/2241
> 3.1.1 just is a fix for this - https://github.com/artsy/Artsy-OSSUIFonts/issues/11

[Pods] Update fonts again for OSS consumers #trivial

---

package.json

Forking on CI is apperantly not efficient. Running in single process brings running time down from 396.647s to 17.688s.
```
PASS  src/lib/components/gene/__tests__/artworks-tests.tsx (141.589s)
PASS  src/lib/components/artist/__tests__/header-tests.tsx (144.711s)
PASS  src/lib/components/artist/__tests__/about-tests.tsx (141.6s)
PASS  src/lib/components/artwork_grids/__tests__/infinite-scroll-grid-tests.tsx (144.573s)
PASS  src/lib/components/gene/__tests__/header-tests.tsx (144.683s)
PASS  src/lib/containers/__tests__/artist-tests.tsx (224.629s)
PASS  src/lib/components/__tests__/separator-tests.tsx (221.703s)
PASS  src/lib/components/__tests__/tab_view-tests.tsx (223.679s)
PASS  src/lib/components/gene/__tests__/biography-tests.tsx (225.522s)
PASS …
```

[CI] Don’t try to run Jest with concurrency enabled.

---

dangerfile.ts

I'll see if I can get Danger to raise the error, then fix the error.
Not certain if using yarn this way will compile the TS for Danger, so it might not work at all.

Update Dangerfile to use master

---

CHANGELOG.md
Example/Emission/ARRootViewController.m
Pod/Classes/ViewControllers/ARWorksForYouComponentViewController.h
Pod/Classes/ViewControllers/ARWorksForYouComponentViewController.m
data/schema.graphql
data/schema.json
package.json
src/lib/app_registry.tsx
src/lib/components/artwork_grids/generic_grid.tsx
src/lib/components/works_for_you/notification.tsx
src/lib/containers/__tests__/works-for-you-tests.tsx
src/lib/containers/works_for_you.tsx
src/lib/relay/routes.tsx
yarn.lock

[WFU] Added special notification capabilities

---

src/lib/components/home/artwork_rails/artwork_rail.tsx

Fixes https://github.com/artsy/eigen/issues/2302

[WFU] fix bug in artwork rail header

---

src/lib/components/works_for_you/__tests__/__snapshots__/notifications-tests.tsx.snap
src/lib/components/works_for_you/notification.tsx
src/lib/containers/__tests__/__snapshots__/works-for-you-tests.tsx.snap

Fixes https://github.com/artsy/eigen/issues/2303 and https://github.com/artsy/eigen/issues/2306

[WFU] Fix for artist name titles and status dot #trivial

---

README.md
docs/debugging.md
yarn.lock

It became painfully clear in [this Slack chat](https://artsy.slack.com/archives/C02CAB1KW/p1493776090098445) that being able to debug e.g. GraphQL queries that Relay emits was hard to do for people not contributing to this repo regularly. Hopefully this should remedy that.

[doc] More elaborate debugging guide

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARHomeComponentViewController.m
Pod/Classes/ViewControllers/ARWorksForYouComponentViewController.m
src/lib/app_registry.tsx
src/lib/containers/__tests__/__snapshots__/home-tests.tsx.snap
src/lib/containers/__tests__/__snapshots__/works-for-you-tests.tsx.snap
src/lib/containers/__tests__/works-for-you-tests.tsx
src/lib/containers/home.tsx
src/lib/containers/works_for_you.tsx

Fix for scrollview bug

---

CHANGELOG.md
src/lib/components/works_for_you/notification.tsx
src/lib/containers/works_for_you.tsx

[WFU] Let nested components decide what data to fetch.

---

CHANGELOG.md
src/lib/containers/home.tsx

PTR now looks like this: 
https://artsy.slack.com/files/sarahscott/F5FD4QWNB/scroll.mov

[Home] Fixes pull-to-refresh scroll position bug

---

.vscode/settings.json
CHANGELOG.md
Example/Emission/ARRootViewController.m
package.json
src/lib/app_registry.tsx
src/lib/components/consignments/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/components/consignments/__tests__/index-tests.tsx
src/lib/components/consignments/index.tsx
src/lib/components/consignments/setup/__tests__/__snapshots__/info-tests.tsx.snap
src/lib/components/consignments/setup/__tests__/__snapshots__/welcome-tests.tsx.snap
src/lib/components/consignments/setup/__tests__/info-test.tsx
src/lib/components/consignments/setup/__tests__/info-tests.tsx
src/lib/components/consignments/setup/__tests__/welcome-tests.tsx
src/lib/components/consignments/setup/info.tsx
src/lib/components/consignments/setup/welcome.tsx
yarn.lock

Adds a new component that shows up in the UI:
Currently only shows:
---
@alloy it is worth considering whether the root separation of `container` and `component` at file-system level will continue to make sense. This is a root component that will/may have relay containers inside.
Perhaps a `root components` and `components`, or even just `components` with each one being a folder.
Not critical though.

[Consignments] Adds a root element for the navigation controller

---

Emission.podspec
README.md
package.json

Going to self-merge, just a heads up.

Automated release

---

package.json
yarn.lock

I tried also including https://github.com/orta/jest-snapshots-svg/ but I got blocked on https://github.com/charto/nbind/issues/78
Will see where that goes to, in theory I could add a postinstall hook that removes `@types/node` but that's a last case scenario. Will see how that goes.

[Dev] Add styled-components

---

.storybook/webpack.config.js
CHANGELOG.md
Example/Emission/index.ios.js
src/lib/components/consignments/__stories__/consignments-search.story.tsx
src/lib/components/consignments/__stories__/index.ts
src/lib/components/consignments/components/__tests__/__snapshots__/artist-search-results-tests.tsx.snap
src/lib/components/consignments/components/__tests__/artist-search-results-tests.tsx
src/lib/components/consignments/components/artist-search-results.tsx
src/lib/components/consignments/components/artwork-consignment-todo.tsx

Adds support for rendering the Artist Search component.
Design:
* ~~Changed "DONE" to "BACK" - I'd expect that when you hit an artist it would count that as a selection and go back. Hitting "done" when you got no results didn't make sense in comparison to "back". If it's not transactional, done doesn't fit IMO~~
* Added a spinner for when we're getting artist results
* Changed the height just enough to indicate that there could be more results to scroll. You never know when your search gives you the 4th item that you actually want.
/cc @katarinabatina <hr data-danger="yep"/>
<details>
<p>&nbsp;</p>
<pre><code>git fetch origin pull/565/head:orta-565-checkout
git checkout orta-565-checkout
yarn install …

[Consignments] Adds a component for Artist Search

---

data/schema.graphql
data/schema.json
src/lib/components/messages/inbox/conversation_snippet.tsx
src/lib/components/messages/inbox/inbox.tsx
src/lib/containers/messages.tsx
src/lib/relay/config.tsx

Just made a PR so you can see the changes<hr data-danger="yep"/>
<details>
<p>&nbsp;</p>
<pre><code>git fetch origin pull/580/head:l2succes-580-checkout
git checkout l2succes-580-checkout
yarn install
</p>
<p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the phone to get the Admin menu.</p>
<p>If you see <i>"Use Staging React Env" </i> - click that and restart, then follow the next step.</p>
<p>Click on <i>"Choose an RN build" </i> - then pick the one that says: "X,Y,Z"</p>
<p>Note: this is a …

Adds pagination to Inbox view

---

CHANGELOG.md
Example/Emission/Info.plist
Example/Podfile.lock

Going to self-merge - these are details for Emission-nebular deployment that needs to go in.
Only one key detail, will comment inline

[Dev] Handle some deploy details #trivial

---

data/schema.graphql
data/schema.json
src/lib/components/inbox/conversations/__tests__/__snapshots__/conversation_snippet-tests.tsx.snap
src/lib/components/inbox/conversations/__tests__/__snapshots__/conversations-tests.tsx.snap
src/lib/components/inbox/conversations/__tests__/conversation_snippet-tests.tsx
src/lib/components/inbox/conversations/__tests__/conversations-tests.tsx
src/lib/components/inbox/conversations/conversation_snippet.tsx
src/lib/containers/__tests__/__snapshots__/inbox-tests.tsx.snap

Sister PR: https://github.com/artsy/metaphysics/pull/649
Related: https://github.com/artsy/collector-experience/issues/295

[MSG] update last message timestamp with real data

---

.travis.yml
CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
src/lib/components/consignments/__stories__/consignments-bottom-aligned.story.tsx
src/lib/components/consignments/__stories__/consignments-search.story.tsx
src/lib/components/consignments/__stories__/consignments-todo.story.tsx
src/lib/components/consignments/__stories__/index.ts
src/lib/components/consignments/__stories__/index.tsx
src/lib/components/consignments/components/__tests__/__snapshots__/artist-search-results-tests.tsx.snap
src/lib/components/consignments/components/__tests__/__snapshots__/artwork-consignment-todo-tests.tsx.snap
src/lib/components/consignments/components/__tests__/__snapshots__/bottom-aligned-button-tests.tsx.snap
src/lib/components/consignments/components/__tests__/artist-search-results-tests.tsx
src/lib/components/consignments/components/__tests__/artwork-consignment-todo-tests.tsx
src/lib/components/consignments/components/__tests__/bottom-aligned-button-tests.tsx
src/lib/components/consignments/components/__tests__/runner.tsx
src/lib/components/consignments/components/artist-search-results.tsx
src/lib/components/consignments/components/bottom-aligned-button.tsx

Adds the ability to attach a "done" button to the keyboard with any hosted React hierarchy. 
It's a relatively simple class, but it comes with being the third time I have built tests/storybooks in the same way, so I've refactored those to remove the redundancy. Will comment this inline.<hr data-danger="yep"/>
<details>
<p>&nbsp;</p>
<pre><code>git fetch origin pull/586/head:orta-586-checkout
git checkout orta-586-checkout
yarn install
</p>
<p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the …

Adds a component for a keyboard aligned button

---

docs/using_the_beta.md
docs/welcome-to-beta.md
src/lib/components/inbox/conversations/__tests__/__snapshots__/conversation_snippet-tests.tsx.snap
src/lib/components/inbox/conversations/__tests__/__snapshots__/conversations-tests.tsx.snap
src/lib/components/inbox/conversations/__tests__/conversation_snippet-tests.tsx
src/lib/components/inbox/conversations/__tests__/conversations-tests.tsx

Based the off Eigen's - https://github.com/artsy/eigen/blob/master/docs/welcome_to_eigen_beta.md

Adds some docs for beta users - #trivial

---

.vscode/launch.json
.vscode/tasks.json
README.md
docs/relay.md
docs/vscode.md

Improves the on boarding by simplifying.
Removes a bunch of the tasks and launch settings that I don't think anyone is really using. React Debugger seems like a better way ATM to handle JS debugging.

Simplifies the docs with how we seem to be working ATM

---

CHANGELOG.md
src/lib/components/inbox/conversations/__tests__/__snapshots__/message-tests.tsx.snap
src/lib/components/inbox/conversations/__tests__/message-tests.tsx
src/lib/components/inbox/conversations/message.tsx
src/lib/containers/__tests__/__snapshots__/conversation-tests.tsx.snap
src/lib/containers/conversation.tsx

[MSG] Added a FlatList to Conversation component

---

CHANGELOG.md
Example/Podfile.lock
data/schema.graphql
data/schema.json
src/lib/app_registry.tsx
src/lib/components/inbox/conversations/__stories__/conversation-snippet.story.tsx
src/lib/components/inbox/conversations/conversation_snippet.tsx
src/lib/containers/__tests__/__snapshots__/conversation-tests.tsx.snap
src/lib/containers/__tests__/conversation-tests.tsx
src/lib/containers/conversation.tsx
src/lib/relay/routes.tsx

[MSG] Adds Relay support to Conversation container

---

dangerfile.ts
package.json
yarn.lock

I finally got around to writing my first Danger JS plugin by extracting the dependency check from Danger this weekend - https://github.com/danger/danger-js/pull/278
Danger should post some info about danger-plugin-yarn the in comments.

[Dev] Provides info on new dependencies added #trivial

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARArtistComponentViewController.m
Pod/Classes/ViewControllers/ARConversationComponentViewController.m
Pod/Classes/ViewControllers/ARGeneComponentViewController.m
Pod/Classes/ViewControllers/ARInboxComponentViewController.m
Pod/Classes/ViewControllers/ARWorksForYouComponentViewController.m

To accompany https://github.com/artsy/eigen/pull/2368

Moves native view controllers to use iOS7+ status bar api.

---

CHANGELOG.md
Example/Podfile.lock
data/schema.graphql
data/schema.json
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/__stories__/ConversationSnippet.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/Inbox.story.tsx
src/lib/Components/Inbox/Conversations/__tests__/ConversationSnippet-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/Conversations-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/Conversation-tests.tsx
src/lib/Containers/__tests__/Inbox-tests.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

Part of https://github.com/artsy/collector-experience/issues/294
Backward pagination (if we go down that route) will happen in a different pr.

 [MSG] Update Conversation schema and add message pagination

---

src/lib/Components/Inbox/Bids/ActiveBid.tsx
src/lib/Components/Inbox/Bids/__tests__/__snapshots__/ActiveBid-tests.tsx.snap
src/lib/Components/Inbox/Bids/index.tsx
src/lib/Components/Inbox/Conversations/ArtworkPreview.tsx
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/Previews/ArtworkPreview.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ZerostateInbox-tests.tsx-renders-correct-when-the-user-has-no-conversations.svg
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ZerostateInbox-tests.tsx.snap
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/Inbox.tsx
src/lib/Containers/__tests__/Inbox-tests.tsx
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap

This PR adds Pull to refresh support to the (Inbox) Active Bids + Messages view. It also fixes pagination.
Skip New Tests

[MSG] Inbox pull to refresh & pagination

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Composer.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Composer-tests.tsx.snap
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

Fixes: https://github.com/artsy/emission/issues/640

[MSG] fixes composer to stay above keyboard

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ZerostateInbox-tests.tsx.snap
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap

Fixes: https://github.com/artsy/emission/issues/648 https://github.com/artsy/emission/issues/646 https://github.com/artsy/emission/issues/644
Skip new tests

[Inbox] Fixes pull to refresh

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARInboxComponentViewController.h
src/lib/AppRegistry.tsx
src/lib/Components/Inbox/Bids/ActiveBid.tsx
src/lib/Components/Inbox/Bids/index.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ZerostateInbox-tests.tsx-renders-correct-when-the-user-has-no-conversations.svg
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ZerostateInbox-tests.tsx.snap
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/Inbox.tsx
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap

Fixes #662 
Fixes #663
Also makes it so the `Inbox` always force fetches data on load so that the `ZeroInboxState` hides when bids/conversations exist.
Will comment inline.
Skip New Tests.

[Inbox] Active Bids fixes

---

src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/ArtworkPreview-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap

[MSG] Fixes ArtworkPreview title truncation bug #trivial

---

CHANGELOG.md
Emission.podspec
Example/Podfile
Example/Podfile.lock

Fixes https://github.com/artsy/collector-experience/issues/402

[Podspec] Move RCTAnimation dependency to spec from Podfile.

---

docs/relay.md

Adds relay2ts instructions.

---

CHANGELOG.md
src/lib/AppRegistry.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/Conversation-tests.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

[MSG] Network connectivity state handling in Conversations

---

CHANGELOG.md
src/lib/Components/Artist/Header.tsx
src/lib/Components/ArtworkGrids/Artwork.tsx
src/lib/Components/Gene/Header.tsx
src/lib/Components/Home/ArtistRails/ArtistCard.tsx
src/lib/Components/Home/ArtistRails/ArtistRail.tsx
src/lib/Components/Home/ArtworkRails/ArtworkRailHeader.tsx
src/lib/Components/Inbox/Bids/index.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/Gene.tsx
src/lib/Containers/WorksForYou.tsx

Probably best to look at the commits.
Skip New Tests

Various crash fixes

---

CHANGELOG.md
data/schema.graphql
data/schema.json
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/Preview/ShowPreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/ShowPreview-tests.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/ShowPreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__stories__/ConversationSnippet.story.tsx
src/lib/Components/Inbox/Conversations/__tests__/ConversationSnippet-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/Conversations-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/Conversation-tests.tsx
src/lib/Containers/__tests__/Inbox-tests.tsx

Re-opening of https://github.com/artsy/emission/pull/694 but from an upstream branch, and not my fork.

@alloy => Show inquiries

---

README.md

Adds note about Storybooks to readme.

Adds note about Storybooks.

---

CHANGELOG.md
Example/Emission/index.storybooks.js
package.json
src/lib/Components/Artist/__stories__/ArtistArticles.story.tsx
src/lib/Components/Artist/__stories__/ArtistHeader.story.tsx
src/lib/Components/Buttons/__stories__/Buttons.story.tsx
src/lib/Components/Consignments/__stories__/BottomAligned.story.tsx
src/lib/Components/Consignments/__stories__/Consignments.story.tsx
src/lib/Components/Consignments/__stories__/ImageSelection.story.tsx
src/lib/Components/Consignments/__stories__/Search.story.tsx
src/lib/Components/Consignments/__stories__/Style.story.tsx
src/lib/Components/Consignments/__stories__/Todo.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/ArtworkPreview.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/Avatar.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/Composer.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/ConversationSnippet.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/Inbox.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/ZeroStateInbox.story.tsx
src/lib/Components/Text/__stories__/Typography.story.tsx
src/lib/Containers/__stories__/Artist.story.tsx
src/storiesRegistry.js
storybook/storyLoader.js
yarn.lock

Updates the storybook server to handle hierarchy, and removes the need to include your storybooks in the app - the list is pre-generated now.
I'll update the code extension after. I handle reaction.

[Dev] Move to Storybooks 3.2

---

CHANGELOG.md
src/lib/Components/Consignments/Components/ImageSelection.tsx
src/lib/Components/Consignments/Components/__tests__/ImageSelection-tests.tsx
src/lib/Components/Consignments/Components/__tests__/__snapshots__/ImageSelection-tests.tsx.snap
src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/SelectFromPhotoLibrary-tests.tsx.snap

Handles infinite looping through all photos inside the Photo roll. This has a really weird hack for testing, I'm pretty sure the issue is what I said it is.
I'd like to refactor this a bit, and try move selection state into the SelectFromPhotoLibrary instead of inside `ImageSelection` so that we can pass that back up correctly.

Uses real photos inside the photo picker

---

CHANGELOG.md
data/schema.graphql
data/schema.json
package.json
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/__stories__/ConversationSnippet.story.tsx
src/lib/Components/Inbox/Conversations/__tests__/ConversationSnippet-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap

Once https://github.com/artsy/metaphysics/pull/699 is merged, I'll update the temp code here.

@joeyAghion => [Messaging] Display unread indicator based on Metaphysics response

---

CHANGELOG.md
src/lib/Components/Consignments/Components/FormElements.tsx
src/lib/Components/Consignments/Components/Toggle.tsx
src/lib/Components/Consignments/Components/__tests__/FormElements-tests.tsx
src/lib/Components/Consignments/Screens/FinalSubmissionQuestions.tsx
src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
src/lib/Components/Consignments/Screens/__tests__/FinalSubmissionQuestions-tests.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx-shows-3-sets-of-questions-when-there's-no-edition-info.svg
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx-shows-and-additional-2-inputs-when-there's-edition-info.svg
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx.snap
src/lib/Components/Consignments/__stories__/Consignments.story.tsx
src/lib/Components/Consignments/index.tsx

This adds the a screen that is the final step in the submission process. Handles all the UI work, but none of the logic towards shipping the final build.
Made a nice GIF of my SVGs for testing too:

[Consignments] Adds the final submission screen

---

CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
Example/Emission/ARRootViewController.m
Example/Emission/InternalWebViewController.h
Example/Emission/InternalWebViewController.m

The link is https://github.com/artsy/emission/blob/master/docs/using_the_beta.md

[Beta] Include an "Emission docs" button

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Message.tsx

Fixes #704 
Related to [this MP pr](https://github.com/artsy/metaphysics/pull/720)

[MSG] Removed sanitization from message body

---

CHANGELOG.md
src/lib/Components/ConnectivityBanner.tsx
src/lib/Components/__tests__/ConnectivityBanner-tests.tsx
src/lib/Components/__tests__/__snapshots__/ConnectivityBanner-tests.tsx.snap
src/lib/Containers/Conversation.tsx

Extracted connectivity banner

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Preview/InvoicePreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/InvoicePreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap

Thx for pointing it out, I don't see the warning anymore (and I did on `master` - sorry!).

@alloy => [Messaging] Fix incorrect use of AttachmentPreview and props

---

CHANGELOG.md
package.json
src/lib/Components/Consignments/Components/ConsignmentBG.tsx
src/lib/Components/Consignments/Components/__tests__/__snapshots__/ConsignmentBG-tests.tsx.snap
src/lib/Components/Consignments/Components/__tests__/__snapshots__/Toggle-tests.tsx-looks-good-as-an-svg.svg
src/lib/Components/Consignments/Screens/__tests__/FinalSubmissionQuestions-tests.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx-shows-3-sets-of-questions-when-there's-no-edition-info-on-ipad.svg
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx-shows-3-sets-of-questions-when-there's-no-edition-info.svg
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx-shows-and-additional-2-inputs-when-there's-edition-info.svg
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx.snap
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Overview-tests.tsx.snap
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Provenance-tests.tsx.snap
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/SelectFromPhotoLibrary-tests.tsx.snap
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx-looks-right-as-an-svg.svg
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx.snap
src/lib/Components/Consignments/__tests__/__snapshots__/index-tests.tsx.snap
yarn.lock

Adds support for a centered with a max-width version of the consignment screens on iPad. 
Also comes with update to jest-snapshots-svg which now renders text: https://github.com/orta/jest-snapshots-svg/pull/28

[Consignments] iPad layouts

---

package.json
yarn.lock

Also adds JSON to the prettier so that the `package.json` doesn't change so much.

Update to danger 2.0

---

src/lib/Components/Consignments/Screens/Overview.tsx
src/lib/Components/Consignments/Screens/__tests__/Overview-tests.tsx

Tests are so easy to write in React.
#trivial

[Consignments] Links the location button to the location screen and adds tests for the regression

---

CHANGELOG.md
src/lib/components/artwork_grids/__tests__/__snapshots__/artwork-tests.tsx.snap
src/lib/components/artwork_grids/artwork.tsx
yarn.lock

Cherry-picks #689. This is a merge into a new `v1.3.11` branch cut from the last stable release (1.3.10). See [Slack](https://artsy.slack.com/archives/C02BAQ5K7/p1504720100000277) for more discussion.

Cherry-pick #689

---

src/lib/Components/Inbox/Conversations/index.tsx

Cherry-picked from https://github.com/artsy/emission/pull/743
This fixes the Inbox pagination, silly mis-named var! 
Skip New Tests #trivial

@alloy => [BugFix] Correct var name for pagination thru conversations

---

.vscode/extensions.json
.vscode/settings.json
CHANGELOG.md
Example/Emission/AppDelegate.h
Pod/Classes/OpaqueImageViewComponent/AROpaqueImageView.m
Pod/Classes/ViewControllers/ARArtistComponentViewController.m
Pod/Classes/ViewControllers/ARMediaPreviewController.m
src/lib/AppRegistry.tsx
src/lib/Components/Artist/Articles/Article.tsx
src/lib/Components/Artist/Header.tsx
src/lib/Components/Artist/Shows/index.tsx
src/lib/Components/Artist/__stories__/ArtistArticles.story.tsx
src/lib/Components/Artist/__stories__/ArtistHeader.story.tsx
src/lib/Components/ArtworkGrids/InfiniteScrollGrid.tsx
src/lib/Components/Home/ArtistRails/ArtistCard.tsx
src/lib/Components/Inbox/Conversations/__stories__/ArtworkPreview.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/Inbox.story.tsx
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/Gene.tsx
src/lib/Containers/Inbox.tsx
src/lib/Containers/__stories__/Artist.story.tsx
src/lib/Containers/__stories__/Gene.story.tsx
src/lib/Containers/__stories__/Inquiry.story.tsx
src/lib/Containers/__stories__/MyAccount.story.tsx
src/lib/relay/QueryRenderers.tsx
typings/react-relay.d.ts
yarn.lock

Now I determine in objc what device type the app is running on and pass that into RN and the `QueryRenderer` so that it can be used by the shows fragments.
This also adds a recommended extension that will find/highlight `TODO:` and `FIXME:` comments.
Skip New Tests.

[Artist/Shows] Fix conditional query for past shows on iPad vs iPhone.

---

dangerfile.ts

See: https://github.com/artsy/artsy-danger/pull/15

[dev] Remove Danger rules which Peril handles

---

CHANGELOG.md
data/schema.graphql
data/schema.json
package.json
src/lib/Components/Inbox/Conversations/MarkReadMessage.ts
src/lib/Containers/Conversation.tsx
src/lib/relay/config.tsx

I'll make some comments in line, but this works! The message is marked as read, and a refresh of the inbox shows the indicator going away. 😅 
Skip New Tests

@l2succes => Mark message as read when rendering the conversation

---

CHANGELOG.md
dangerfile.ts
src/lib/Components/Consignments/Screens/Metadata.tsx
src/lib/Components/Consignments/Screens/Overview.tsx
src/lib/Components/Consignments/Screens/__tests__/Metadata-tests.tsx
src/lib/Components/Consignments/Screens/__tests__/Overview-tests.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Metadata-tests.tsx.snap
src/lib/Components/Consignments/Submission/__tests__/consignmentSetupToSubmission-tests.ts
src/lib/Components/Consignments/Submission/__tests__/create-tests.ts
src/lib/Components/Consignments/Submission/__tests__/objectToGraphQL-tests.ts
src/lib/Components/Consignments/Submission/__tests__/update-tests.ts
src/lib/Components/Consignments/Submission/consignmentSetupToSubmission.ts
src/lib/Components/Consignments/Submission/create.ts
src/lib/Components/Consignments/Submission/objectToGraphQL.ts
src/lib/Components/Consignments/Submission/types.ts
src/lib/Components/Consignments/Submission/update.ts
src/lib/Components/Consignments/__stories__/Todo.story.tsx
src/lib/Components/Consignments/__stories__/consignmentSetups.ts
src/lib/Components/Consignments/__tests__/fixtures/consignmentSetups.ts
src/lib/Components/Consignments/index.tsx

I need to make some metaphysics changes before I can wrap this up, so submitting this for momentum.

Submit draft consignments to metaphysics

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Composer.tsx
src/lib/Components/Inbox/Conversations/__tests__/Composer-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Composer-tests.tsx.snap
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

If a message mutation fails, the message text will show up in the Composer again so the user can try again
Fixes: https://github.com/artsy/emission/issues/625

[msg] Retry state for failed messages

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/__tests__/Messages-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap

Closes: https://github.com/artsy/collector-experience/issues/486

[messages] Initial message now sticks to the top of the scrollview

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap
src/lib/Components/Inbox/Typography/index.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap

[msg] Added pending state to timestamp

---

src/lib/Components/Inbox/Conversations/Messages.tsx

trivial no new tests
This is the quick fix! But we can add some interfaces...

@l2succes => [Messaging] Bug fix for prop mismatch

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/Preview/InvoicePreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/InvoicePreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

Fixes: https://github.com/artsy/emission/issues/764
And minor UI fixes to match spec

[MSG] fixes payment request component collapsing

---

CHANGELOG.md
data/schema.graphql
data/schema.json
package.json
src/lib/Components/Inbox/ActiveBids/ActiveBid.tsx
src/lib/Components/Inbox/ActiveBids/__tests__/ActiveBid-tests.tsx
src/lib/Components/Inbox/ActiveBids/__tests__/__snapshots__/ActiveBid-tests.tsx.snap
src/lib/relay/config.tsx

🚨 Depends on https://github.com/artsy/metaphysics/pull/751 🚨 ; fixes https://github.com/artsy/collector-experience/issues/493

[msg] added support for live open auctions in ActiveBids section

---

package.json

[packager] Also use Haul for Emission.app deploys.

---

package.json

[Dev] Adds a lock for the node/yarn/npm versions which match metaphysics

---

CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
Example/Emission/AppSetup.m
Example/Emission/UnroutedViewController.m
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m
Pod/Classes/EigenCommunications/ARNotificationsManager.h
Pod/Classes/EigenCommunications/ARNotificationsManager.m
data/schema.graphql
data/schema.json
src/lib/Components/Consignments/__stories__/BottomAligned.story.tsx
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/Preview/InvoicePreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__stories__/InvoicePreview.story.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/InvoicePreview-tests.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/InvoicePreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/Message-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/Messages-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap
src/lib/Components/__stories__/DottedLine.story.tsx
src/lib/Containers/__tests__/Conversation-tests.tsx
src/lib/Containers/__tests__/Gene-tests.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Gene-tests.tsx.snap
src/lib/NativeModules/NotificationsManager.tsx
src/setupJest.ts
storybook/storyLoader.js

cc @sarahscott this is basically where we got on the RN side...and it works on `master` with the Relay modern upgrade in!!
Skip New Tests

[Messaging] Launch webview when tapping on unpaid invoice, and refresh when paid

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Composer.tsx
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Composer-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

[Messaging] Back button alignment, Composer autofocus, and Conversation Separator

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/528

[msg] Updated hyperlink styling

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Message.tsx

Closes https://github.com/artsy/collector-experience/issues/270

[MSG] Show payment request modally.

---

Example/Podfile
Example/Podfile.lock

Updates fonts to use https://github.com/artsy/Artsy-OSSUIFonts/pull/15 so that emission-nebula can use it

Update the fonts reference

---

Example/Emission/AppSetup.m

The beta never switches to master, because we ship debug builds ( for better logging ) - so this checks if you're not in the sim (and for crashes)
Gonna self merge and deploy ASAP

Fixes for beta testing

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/__tests__/Composer-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Composer-tests.tsx.snap
src/lib/Containers/__tests__/Conversation-tests.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

Basically had to modify the tests a bit to enzyme's `dive` method which allow you to get to the child (assuming there's one) of a react component. 
More info here: https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/dive.md

Fixes tests for analytics work

---

src/lib/Components/Artist/Artworks/index.tsx

The refactoring in #807  included a typo 🐙  - it happens, but that area of the code was `any`'d - this is now hard typed so it can't happen again 👍 
#trivial Skip New Tests

[Crash] Fixes the Artist artworks infinite scroll

---

src/lib/Components/Inbox/Conversations/Composer.tsx

Fixes https://github.com/artsy/collector-experience/issues/655
trivial

[Messaging] Don't hide the keyboard when you press enter

---

CHANGELOG.md
src/lib/AppRegistry.tsx
src/lib/Containers/__tests__/index-tests.tsx
src/lib/Containers/index.tsx
src/lib/relay/QueryRenderers.tsx

This adds the Sale container to the app registry, the first steps to exposing it to Eigen as a native view controller.

Adds Sale container to app registry

---

CHANGELOG.md
Example/Emission/ARDefaults.m
Pod/Classes/OpaqueImageViewComponent/AROpaqueImageView.m
data/schema.graphql
data/schema.json
src/lib/Scenes/Home/Components/ForYou/Components/FairsRail.tsx
src/lib/Scenes/Home/Components/ForYou/Components/__tests__/FairsRail-tests.tsx
src/lib/Scenes/Home/Components/ForYou/Components/__tests__/__snapshots__/FairsRail-tests.tsx.snap
src/lib/Scenes/Home/Components/ForYou/index.tsx
src/lib/relay/config.tsx

Please note the ordering of rails is expected to change as we near the finish of the Home/ForYou scene; I put Fairs at the top for now.
Fixes https://github.com/artsy/collector-experience/issues/454 
Skip New Tests

New Fairs rail

---

CHANGELOG.md
src/lib/Components/WorksForYou/Notification.tsx
src/lib/Components/WorksForYou/__tests__/__snapshots__/Notification-tests.tsx.snap
src/lib/Containers/WorksForYou.tsx
src/lib/Containers/__tests__/WorksForYou-tests.tsx
src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/451

[wfu] removed title, date, status indicator

---

.gitignore
CHANGELOG.md
src/lib/Containers/Inquiry.tsx
src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap

Fix #[CE635](https://github.com/artsy/collector-experience/issues/635)
Phone:
Pad:

[QA] Inquiry Screen

---

CHANGELOG.md
data/schema.graphql
data/schema.json
src/lib/Scenes/Home/Components/ForYou/index.tsx

Fixes https://github.com/artsy/collector-experience/issues/659
Depends on https://github.com/artsy/metaphysics/pull/814
Skip New Tests

[ForYou] Remove ‘works by artists you follow’ rail.

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Preview/InvoicePreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__stories__/InvoicePreview.story.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/InvoicePreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/652.

Payments flow QA fixes

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARComponentViewController.m

Looks like I got it wrong the first time, fixed now

Updates the status bar text colours to black

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/ZeroStateInbox.tsx
src/lib/Components/States/ZeroState.tsx
src/lib/Components/States/__stories__/ZeroState.story.tsx
src/lib/Containers/WorksForYou.tsx
src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap
src/lib/Scenes/Favorites/Components/Artists/index.tsx
src/lib/Scenes/Favorites/Components/Artworks/index.tsx
src/lib/Scenes/Favorites/Components/Categories/index.tsx
storybook/storyLoader.js

Fixes https://github.com/artsy/collector-experience/issues/719
P.s: @mennenia this doesn't change _much_ in the Home, but it touches it - so you might have a little work on the rebase (mainly I added `.`s, changed a bit of text, changed the title font and turned the BG white ) [see slack](https://artsy.slack.com/archives/C02BAQ5K7/p1511020522000085)
Skip New Tests

Updates the zero states for home, messaging and favs

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/651

[Conversation] Don’t let scrollview capture taps.

---

src/lib/Scenes/Home/Components/ForYou/Components/FairsRail.tsx
src/lib/Scenes/Home/Components/ForYou/Components/__tests__/__snapshots__/FairsRail-tests.tsx.snap
yarn.lock

The following images are after scrolling a bit; the scroll view loads initially with a 20px margin.
Before:
After:
Fixes https://github.com/artsy/collector-experience/issues/722

fairs rail qa #trivial

---

CHANGELOG.md
src/lib/Components/Consignments/Screens/Overview.tsx

* [Consigments] Don’t assume a photo was selected. Fixes #840 / [Sentry](https://sentry.io/artsynet/eigen-staging/?query=e%5B0%5D.file)

[WIP] Crash fixes.

---

CHANGELOG.md
Example/Emission/ARRootViewController.m
Example/Emission/AppDelegate.m
Pod/Classes/ViewControllers/ARHomeComponentViewController.h
Pod/Classes/ViewControllers/ARHomeComponentViewController.m
src/lib/AppRegistry.tsx
src/lib/Scenes/Home/Components/ForYou/index.tsx
src/lib/Scenes/Home/index.tsx

Fixes https://github.com/artsy/collector-experience/issues/723
This makes sure that when a user taps an artist in a Works For You email, that artists' works are presented at the top of the Artists section when eigen is launched.
Skip New Tests

[home] home accommodates selected artist UTM param

---

src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/716 ✨

[home] added a top margin for new message loading indicator #trivial

---

CHANGELOG.md
src/lib/Components/Consignments/Submission/uploadPhotoToGemini.ts

Builds off https://github.com/artsy/metaphysics/pull/848 to un-hardcode the string for the template used in Gemini for Consignment submissions.

Grabs the key for the convection gemini token from metaphysics

---

src/lib/Components/Buttons/DarkNavigationButton.tsx
src/lib/Components/Consignments/Screens/Artist.tsx
src/lib/Scenes/Favorites/index.tsx

Fixes https://github.com/artsy/collector-experience/issues/747
#trivial
Skip New Tests

Don't crash if you click on the staging warning

---

CHANGELOG.md
Example/Emission/ARRootViewController.m
src/lib/Containers/Inquiry.tsx
src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/754

[MSG] Change inquiry statusbar background to white #trivial

---

CHANGELOG.md
src/lib/Components/Inbox/ActiveBids/ActiveBid.tsx
src/lib/Components/Inbox/ActiveBids/__tests__/__snapshots__/ActiveBid-tests.tsx.snap
src/lib/Components/Inbox/ActiveBids/index.tsx
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/776
Skip New Tests

[QA] Inbox / Active Bids spacing

---

Example/Emission/ARRootViewController.m
Example/Emission/AppDelegate.m
Pod/Classes/ViewControllers/ARHomeComponentViewController.h
Pod/Classes/ViewControllers/ARHomeComponentViewController.m

Forgot to do this in my last PR but it's a bit nicer.
Skip New Tests.

[home] use an enum instead of ints #trivial

---

CHANGELOG.md
src/lib/Components/Consignments/Components/CloseButton.tsx
src/lib/Components/Consignments/Components/ConsignmentBG.tsx
src/lib/Components/Consignments/Components/FormElements.tsx
src/lib/Components/Consignments/Screens/Overview.tsx
src/lib/Components/Consignments/Screens/Welcome.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Overview-tests.tsx.snap
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx.snap
src/lib/Components/Consignments/__tests__/__snapshots__/index-tests.tsx.snap

For https://github.com/artsy/collector-experience/issues/795
- Looks a bit wonky on iPad, but address that in the issue ^^^ waiting to hear back
- Still missing assets, currently has the inbox ones for styling/spacing purposes (but those are black so you can't see them)
Skip New Tests

[Consignments] New Welcome screen

---

scripts/deploy_master.sh

is now legit JSON, old version had an extra trailing comma

Fix master deploy JSON

---

package.json
src/lib/Components/Artist/Artworks/index.tsx
src/lib/Components/ArtworkGrids/RelayConnections/ArtistForSaleArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/ArtistNotForSaleArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/GeneArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/SaleArtworksGrid.tsx
src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
src/lib/Components/Consignments/Screens/__tests__/Overview-local-storage-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Composer-tests.tsx.snap
src/lib/Components/LoadFailureView.tsx
src/lib/Containers/__tests__/Artist-tests.tsx
src/lib/Containers/__tests__/Gene-tests.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap
src/lib/metaphysics.ts
yarn.lock

ran `yarn upgrade-interactive --latest`.
Will comment inline
#trivial

[Dev] Updates a good chunk of developer dependencies

---

src/lib/Scenes/Home/Components/ForYou/index.tsx
src/lib/Scenes/Home/Components/Sales/index.tsx

Fixes https://github.com/artsy/collector-experience/issues/823
#trivial

[Home] Makes For You and Auctions title top margin consistent

---

src/lib/Containers/Inbox.tsx
src/lib/Containers/__tests__/Inbox-tests.tsx

fixes https://github.com/artsy/collector-experience/issues/818
Checks to see if the refs exist, and if not, will call a relay refetch. TBH I'm like 90% on the fact that this works as I think it will, so will poke @alloy but should be fine regardless.
#trivial

[Messaging] Don't crash when you're on the zerostate

---

CHANGELOG.md
src/lib/Scenes/Home/index.tsx
yarn.lock

This makes sure that Home shows the Artists tab when there's a selected artist even when it's coming from the background and was originally on a different tab.
Fixes https://github.com/artsy/collector-experience/issues/751
Skip New Tests

[home] Pop to artist tab when coming from background w/selected artist

---

src/lib/Components/Inbox/Conversations/Preview/InvoicePreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/InvoicePreview-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/822

[msg] fixes font and alignment of canceled or refunded payment request labels #trivial

---

CHANGELOG.md
src/lib/Components/Home/ArtistRails/ArtistRail.tsx
src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarousel.tsx
src/lib/Scenes/Home/Components/ForYou/Components/FairsRail.tsx
src/lib/Scenes/Home/Components/ForYou/index.tsx

Fixes https://github.com/artsy/collector-experience/issues/820.
Also re-enables removal of off-screen subviews on the home view.

Bring back the artist rails

---

src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/Preview/InvoicePreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/InvoicePreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/806
Now our payment requests/attachments look like this on iPhone 5 🎉:

[msg] fix cut off previews on small screens #trivial

---

src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarousel.tsx

Fixes https://github.com/artsy/collector-experience/issues/828

[home] fixes ipad margins of ForYou artwork rails #trivial

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/Inbox.tsx

Fixes: https://github.com/artsy/collector-experience/issues/821
Fixes: https://github.com/artsy/collector-experience/issues/850
Fixes: https://github.com/artsy/collector-experience/issues/857
Fixes: https://github.com/artsy/collector-experience/issues/804

[Inbox] Fixes loading indicator stuck after fetch and conversation row collapsing 

---

src/lib/Components/Consignments/Screens/Welcome.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx.snap
src/lib/Components/Consignments/__tests__/__snapshots__/index-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/832
The view looks unchanged on larger iPhone/iPad screens.
Also seems to solve some issues with rotation on iPad.

[consignments] fixes cut-off text on small screens #trivial

---

src/lib/Components/Inbox/Conversations/ZeroStateInbox.tsx

Fixes https://github.com/artsy/collector-experience/issues/866 & https://github.com/artsy/collector-experience/issues/848

[msg] fixes text clipping and rotation bug in zero state inbox ui #trivial

---

docs/running-emission-in-eigen.md

Updated the docs re https://github.com/artsy/eigen/pull/2505
#trivial

[Dev] Updates docs for running emission in Eigen

---

CHANGELOG.md
docs/running-emission-in-eigen.md
src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
src/lib/Components/Consignments/Screens/__tests__/SelectFromPhotoLibrary-tests.tsx
src/lib/NativeModules/triggerCamera.tsx

Fixes a bug shipped in https://github.com/artsy/emission/pull/893 where the code is added to the wrong callback. I've added some tests, as this stuff is really tough to actually run in dev.

Move the code for adding a new photo to the right area

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/878

[msg] timestamps are more human readable

---

CHANGELOG.md
src/lib/Scenes/Favorites/index.tsx
src/lib/utils/track.ts

Fix https://github.com/artsy/collector-experience/issues/881
Small PR :), being merged into existing analytics PR just to avoid a few conflicts . 
Just assigning you @alloy because you were on the other PR

[Analytics] Add page views for saves and follows

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/RelayConnections/GeneArtworksGrid.tsx
src/lib/Containers/Gene.tsx
src/lib/Containers/__tests__/Gene-tests.tsx
src/lib/relay/QueryRenderers.tsx

Will comment inline
Fixes #578

Fix gene relay query vars

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Composer.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Composer-tests.tsx.snap
src/lib/Containers/Conversation.tsx
src/lib/Containers/Inquiry.tsx
src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap

Also fixes the test failing on CI.

[Conversation] Align header title with navigation button

---

CHANGELOG.md
src/lib/Components/Consignments/Screens/Overview.tsx
src/lib/Components/Consignments/Screens/__tests__/Overview-uploading-tests.tsx
src/lib/Components/Consignments/index.tsx

Fixes https://github.com/artsy/collector-experience/issues/834

[Consignments] Keep track of what images are being uplaoded so we don't ship dupes

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap

[Conversation] Remove rule below header.

---

CHANGELOG.md
src/lib/Components/Consignments/Components/ArtworkConsignmentTodo.tsx
src/lib/Components/Consignments/Components/__tests__/ArtworkConsignmentTodo-tests.tsx
src/lib/Components/Consignments/Components/__tests__/__snapshots__/ArtworkConsignmentTodo-tests.tsx.snap
src/lib/Components/Consignments/Screens/Edition.tsx
src/lib/Components/Consignments/Screens/Overview.tsx
src/lib/Components/Consignments/Screens/__tests__/Overview-tests.tsx
src/lib/Components/Consignments/Submission/__tests__/consignmentSetupToSubmission-tests.ts
src/lib/Components/Consignments/index.tsx

Fix https://github.com/artsy/collector-experience/issues/898
Thanks for the pointer @orta!
Not enough time to make a gif, sorry 😞

[Consignments] Bring required fields in line with force

---

CHANGELOG.md
src/lib/Components/Consignments/Screens/Metadata.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Metadata-tests.tsx.snap

Fix https://github.com/artsy/collector-experience/issues/896

[Consignments] Add autofocus to work details screen

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/RelayConnections/GeneArtworksGrid.tsx
src/lib/Containers/Gene.tsx
src/lib/Containers/__tests__/__snapshots__/Gene-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/907
Also moves to a better architected version of filtered artworks for a gene, which Reaction uses atm as well.

[Gene] Fix pagination.

---

CHANGELOG.md
src/lib/Scenes/Home/Components/Sales/Components/LotsByFollowedArtists.tsx
src/lib/Scenes/Home/Components/Sales/Components/__tests__/LotsByFollowedArtists-tests.tsx

Closes: https://github.com/artsy/collector-experience/issues/905

[Home/Auctions] fixes loading indicator/section header not hiding 

---

CHANGELOG.md
src/lib/Components/Consignments/Screens/Welcome.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx.snap

Updates the wording in the welcome popover

[Consignments] Updates the wording for welcome

---

CHANGELOG.md
src/lib/Scenes/Home/Components/Sales/Components/LotsByFollowedArtists.tsx
src/lib/Scenes/Home/Components/Sales/Components/__tests__/LotsByFollowedArtists-tests.tsx

Revert "[Home/Auctions] fixes loading indicator/section header not hiding "

---

CHANGELOG.md
src/lib/Scenes/Home/Components/Sales/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/index.tsx

As mentioned on https://github.com/artsy/collector-experience/issues/905#issuecomment-357438308, this needs a bit more work so we’re pulling the feature now to be able to ship.

[Home/Auctions] Disable Lots by Artists You Follow for this release.

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARComponentViewController.m
Pod/Classes/ViewControllers/ARHomeComponentViewController.m

In #955 I removed the JS side of the equation, but I need to fix up the native side too.

[iPhoneX] Fix the top margin for home

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/GenericGrid.tsx
src/lib/Scenes/Favorites/Components/Artists/index.tsx
src/lib/Scenes/Favorites/Components/Artworks/index.tsx
src/lib/Scenes/Favorites/Components/Categories/index.tsx

[IN-6](https://artsyproduct.atlassian.net/browse/IN-6) #resolve

[Saves&Faves] Add pagination spinners to each tab.

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/__tests__/Conversations-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ZeroStateInbox-tests.tsx.snap
src/lib/Components/Inbox/Conversations/index.tsx

Fixes [this issue](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=IN&selectedIssue=IN-7)
The zerostate inbox test is actually outdated also. I'll sort that when I come back. 

[MSG] Fix inbox header title when there are no messages

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/RelayConnections/ArtistForSaleArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/ArtistNotForSaleArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/GeneArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/SaleArtworksGrid.tsx
src/lib/Containers/WorksForYou.tsx

[IN-14](https://artsyproduct.atlassian.net/browse/IN-14)  #resolve

[dev] removes unused imports that relay no longer requires

---

CHANGELOG.md
src/lib/metaphysics.ts

https://artsyproduct.atlassian.net/browse/IN-59 #resolve

[Relay] Show ‘UNABLE TO LOAD’ view on GraphQL errors.

---

CHANGELOG.md
src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarouselHeader.tsx

https://artsyproduct.atlassian.net/browse/IN-62 #resolve

[ArtworkCarouselHeader] Fix crash due to missing artist details.

---

CHANGELOG.md
data/schema.graphql
data/schema.json
src/lib/Scenes/Home/Components/Sales/Components/LotsByFollowedArtists.tsx
src/lib/Scenes/Home/Components/Sales/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/index.tsx
src/lib/utils/renderWithLoadProgress.tsx

https://artsyproduct.atlassian.net/browse/IN-73 #resolve
Also fixes https://sentry.io/artsynet/eigen/issues/435565681/

Enable lots by artists you follow and hide when necessary

---

data/schema.graphql
data/schema.json
src/lib/Components/Inbox/Conversations/Messages.tsx

Need to update local schema to match latest changes with https://github.com/artsy/metaphysics/pull/918

Synch with latest MP schema

---

CHANGELOG.md
src/lib/Components/Consignments/Components/BottomAlignedButton.tsx

Adds an extra margin for the iPhone X

Improves the default bottom margin for iPhone x

---

package.json

Fixes https://github.com/artsy/emission/issues/904

Remove the clean part of `yarn start`

---

src/lib/Scenes/Home/Components/Sales/Components/SaleList.tsx
src/lib/Scenes/Home/Components/Sales/__tests__/__snapshots__/index-tests.tsx.snap

We can't dynamically update `numColumns` in our `FlatList`, but that's ok because we only need to check if we're on an iPad once. 
Note for the curious or for future implementations that would require dynamically changing `numColumns`: it is technically possible to update the number of columns but one would also have to [update keys as well](https://stackoverflow.com/questions/44291781/dynamically-changing-number-of-columns-in-react-native-flat-list). 
Fixes https://artsyproduct.atlassian.net/browse/IOS-95

[Auctions] Fix for dynamic updating of numColumns in auctions FlatList #trivial

---

CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
Example/Emission/AppSetup.m
src/lib/Components/OpaqueImageView.tsx

Following https://github.com/artsy/force/pull/2226 I’ve reduced the quality here to 80 as well and seeing about a ~19.5% reduction in downloaded data.

Reduce image quality to optimise download data requirements

---

Emission.podspec
Makefile

Adds the new deps - https://github.com/artsy/Specs/commit/9d5378347300bade19a4b30ec39ec91832ab3eee
#trivial

[Dev] Updates the makefile for shipping new RN deps

---

docs/adding_new_components.md

After #1003 I wanted to make sure we document how to do this.

Adds docs around adding new components

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Button.tsx
src/lib/Components/Bidding/Components/MaxBidPicker.tsx
src/lib/Components/Bidding/Components/Title.tsx
src/lib/Components/Bidding/Components/__tests__/Button-tests.tsx
src/lib/Components/Bidding/Components/__tests__/MaxBidPicker-tests.tsx
src/lib/Components/Bidding/Components/__tests__/Title-tests.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/Button-tests.tsx.snap
src/lib/Components/Bidding/Components/__tests__/__snapshots__/MaxBidPicker-tests.tsx.snap
src/lib/Components/Bidding/Components/__tests__/__snapshots__/Title-tests.tsx.snap
src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBid-tests.tsx.snap
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
src/lib/Components/Buttons/index.tsx

Adds <SelectMaxBid> component

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx

Adds confirm bid screen https://artsyproduct.atlassian.net/browse/PURCHASE-25
Similar to https://github.com/artsy/emission/pull/1010
**TODO** correct font (separate PR)

Adds Confirm Bid Screen

---

CHANGELOG.md
package.json
src/lib/Components/Bidding/Components/BiddingThemeProvider.tsx
src/lib/Components/Bidding/Components/Container.tsx
src/lib/Components/Bidding/Components/Containers.tsx
src/lib/Components/Bidding/Components/Divider.tsx
src/lib/Components/Bidding/Components/Timer.tsx
src/lib/Components/Bidding/Components/Title.tsx
src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/Title-tests.tsx.snap
src/lib/Components/Bidding/Elements/Flex.tsx
src/lib/Components/Bidding/Elements/Grid.tsx
src/lib/Components/Bidding/Elements/Icon.tsx
src/lib/Components/Bidding/Elements/Theme.tsx
src/lib/Components/Bidding/Elements/Typography.tsx
src/lib/Components/Bidding/Elements/types.d.ts
src/lib/Components/Bidding/Screens/BidResult.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BidResult-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBid-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/BidFlow-tests.tsx.snap
yarn.lock

This PR shows how our new type system and family could be implemented using [the `styled-system`](https://github.com/jxnblk/styled-system).
The Elements consist of very basic React components implemented based on the `styled-system` and a set of primitive values for color, typography and spacing (more to add later, but three of them for now).
```
src/lib/Components/Bidding/Elements
├── Flex.tsx
├── Grid.tsx
├── Theme.tsx
└── Typography.tsx
```
The Components are more opinionated and implemented based on the Element components described above. Right now, the level of reusability differs depending on the component, and we may need to re-organize some of these components. For example, the `<Grid>` component is less opinionated than the `<MaxBidPicker>` component, which is very specific to …

Adds a more re-useable low-level components to refactor the screens for the new bidding flow

---

src/lib/Components/Bidding/Components/Title.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/Title-tests.tsx.snap
src/lib/Components/Bidding/Elements/Typography.tsx
src/lib/Components/Bidding/Screens/BidResult.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BidResult-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBid-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/BidFlow-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-94
These are small items @briansw and I discussed earlier today:
* Removed the "Artsy's" from the Condition of Sale
* The margin between the CoS and the PLACE BID button is now 30px
* Changed the font size of the title to 22px
* Set maxWidth to the bid result screen to 
cc @briansw 

Address QA items for styling

---

CHANGELOG.md
src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarouselHeader.tsx
src/lib/Scenes/Home/Components/ForYou/Components/__tests__/ArtworkCarouselHeader-tests.tsx

Fixin that changelog now
Contains: #1035

@ashfurrow => Merge Emission crasher into a branch for 1.4.7

---

dangerfile.ts

Adds Danger rule for changelog formatting

---

README.md
package.json
scripts/merge-graphql-query-map.js
scripts/release.js

Nothing fancy, since this will be replaced by a longer-term solution on Metaphysics like a database. This is the first time the release script was run through prettier lately (ever?) so there are some superfluous changes.

Updates release with new script to merge query maps.

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Button.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/Button-tests.tsx.snap
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BidResult-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmFirstTimeBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBid-tests.tsx.snap
src/lib/Components/Buttons/InvertedButton.tsx
src/lib/Containers/__tests__/__snapshots__/BidFlow-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-131

Update the `<ConfirmBid>` component to show a spinner while loading

---

README.md

I thought linking to an issue with the current workaround would be less brittle than documenting everything in the readme, so I opened #1077.

Adds note about deploys not working

---

src/lib/Components/Bidding/Components/BidInfoRow.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmFirstTimeBid-tests.tsx.snap

The styles for the bid information row has been stable and I think it's time to consolidate it. There are other low-hanging fruit but I left it and keep this PR small and simple

Consolidate the bid information row #trivial

---

src/lib/Components/Bidding/Screens/ConfirmBid.tsx

As part of the effort to consolidate the `<ConfirmBid>` and `<ConfirmFirstTimeBid>` components, I started refactoring the `<ConfirmBid>` component. This PR extracts functions and constants that do not depend on `props` or `state` and makes it easier to understand what's specific to `<ConfirmBid>` and what is not.
Let me know if you have any feedback!

Move dependency-free functions and constants out of ConfirmBid #trivial

---

src/lib/Components/Bidding/Screens/ConfirmBid.tsx

This PR simplifies most of the variable assignments in the `<ConfirmBid>` component using ES6's variable deconstruction.
Let me know if there's any feedback!

Refactor <ConfirmBid> #trivial

---

CHANGELOG.md
Example/Podfile.lock
src/lib/Components/Bidding/Components/Timer.tsx
src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx
src/lib/Components/Bidding/Elements/Typography.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap

See https://github.com/artsy/emission/pull/1096 for explanation.

@yuki24 => updates unica font definition

---

.travis.yml
dangerfile.ts

You don't get all the features, but it should still green or red correctly

Support forked PRs in Emission

---

.vscode/extensions.json

Remove yaml extension from recommedations

---

src/lib/Components/Bidding/Screens/CreditCardForm.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/CreditCardForm-tests.tsx.snap

Updates credit card form to match specs:

#trivial [Bidding] fix margins on cc form

---

src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap

We merged two PRs (#1123 and #1128) almost at the same time and that seemed to have caused the build to fail due to a snapshot mismatch. This PR updates the snapshot to fix that.

Update snapshot to fix builds #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-227 and https://artsyproduct.atlassian.net/browse/PURCHASE-187

User should see an error message when MP returns an error

---

storybook/storyLoader.js

Storybook auto-updates this file so I'm just checking this in.

Check in auto-updated storyLoader.js #trivial

---

src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap

This addresses three tiny QA tickets that we uncovered today:
- https://artsyproduct.atlassian.net/browse/PURCHASE-233
- https://artsyproduct.atlassian.net/browse/PURCHASE-235
- https://artsyproduct.atlassian.net/browse/PURCHASE-247

Tiny visual fixes on bidding flow #trivial

---

src/lib/Components/Bidding/Screens/BidResult.tsx
src/lib/Components/Bidding/Screens/RegistrationResult.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap

Update margin on bid payoff screen #trivial

---

src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap

This is very very trivial, I just noticed the wrapping `<View>` is unnecessary.

Remove unnecessary nesting in <BillingAddress> #trivial

---

README.md

As discussed in our meeting this morning, this PR adds myself as a point person for the Emission project.

Adds @ashfurrow as point person

---

src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap

Complete Registration --> Complete registration #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Timer.tsx
src/lib/Components/Bidding/Context/TimeOffsetProvider.tsx
src/lib/Components/Bidding/Context/__tests__/TimeOffsetProvider-tests.tsx
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
src/lib/Containers/BidFlow.tsx
src/lib/Containers/RegistrationFlow.tsx
src/lib/Containers/__tests__/RegistrationFlow-tests.tsx

addresses https://artsyproduct.atlassian.net/browse/PURCHASE-208

Use Gravity's system time to consider offset for auction timer

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-256
I'm not sure if I like this fix, but this seems to be working fine...

WIP: Auto-advancing through the fields should scroll down enough

---

src/lib/Components/Bidding/Screens/SelectCountry.tsx

See https://artsy.slack.com/archives/C9YNS4X32/p1531944273000207

Put the search query for country in quotes rather than italicize #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Components/LinkText.tsx
src/lib/Components/Bidding/Components/Markdown.tsx
src/lib/Components/Bidding/Components/__tests__/Markdown-tests.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-296

Disable Conditions of sale link and checkbox while bid is processing

---

README.md

After returning to Emission from some time away, ran into an outdated dep issue that this command fixed.

Update README with full clean step

---

Example/Emission.xcodeproj/project.pbxproj
Example/Emission/ARLabOptions.h
Example/Emission/ARLabOptions.m
Example/Emission/ARRootViewController.m
Example/Emission/EigenLikeAdminViewController.h
Example/Emission/EigenLikeAdminViewController.m

Part 1 of 2. 
Part 2 ( tomorrow ) will include reading from this inside the JS. I got a conference party to crash though 🍡

Adds the labs feature from Eigen into Emission

---

CHANGELOG.md
package.json
yarn.lock

Depends on https://github.com/artsy/emission/pull/1185

[Lib] Upgrade @artsy/palette@2.16.0

---

CHANGELOG.md
src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap
src/lib/Scenes/Home/Components/ForYou/Components/MarketingHeader.tsx
src/lib/Scenes/Home/Components/ForYou/Components/__tests__/__snapshots__/MarketingHeader-tests.tsx.snap

Per Zeplin spec: https://app.zeplin.io/project/5aabc5d2e01881c81138e58e/screen/5b744b54d9c164411cea20e5
Corresponding web PR: 
https://github.com/artsy/reaction/pull/1349

[WFY] Update copy on WFY MarketingHeader

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/Artwork.tsx
src/lib/Components/ArtworkGrids/__tests__/__snapshots__/Artwork-tests.tsx.snap

Left it at 8/8 with the padding, and a TODO.

@damassi => Tweaks to artwork badge display

---

.vscode/extensions.json
.vscode/settings.json

Now that all these extensions are consolidated
#trivial

Recommends the omakase extension and sets cSpell to be hints only

---

CHANGELOG.md
src/lib/Scenes/Home/Components/ForYou/Components/MarketingHeader.tsx

https://artsyproduct.atlassian.net/browse/DISCO-359
Update WFY /collect url to remove A/B test. 
Related: https://github.com/artsy/reaction/pull/1421

[WFY] Update BNMO /collect url

---

CHANGELOG.md
Example/Emission/ARLabOptions.m
src/lib/Containers/WorksForYou.tsx
src/lib/Containers/__tests__/WorksForYou-tests.tsx
src/lib/Scenes/Home/__tests__/index-tests.tsx
src/lib/Scenes/Home/index.tsx

Sibling PR to https://github.com/artsy/reaction/pull/1428

Removes the BNMO feature flags

---

Pod/Classes/ViewControllers/ARFairComponentViewController.h
Pod/Classes/ViewControllers/ARFairComponentViewController.m

Fixes the compilation issues on master, this is included in #1201  but this is just that one change
#trivial #native_no_changes

Makes emission compile in Xcode

---

yarn.lock

[Suggested here](https://github.com/artsy/emission/pull/1211#issuecomment-434762237) to resolve a case where a PR comment wasn't deleted once the build was green.

Upgrades Danger #trivial

---

package.json
yarn.lock

See: 
https://github.com/artsy/emission/pull/1212#discussion_r229896721

Updates Danger again

---

CHANGELOG.md
src/lib/Scenes/City/City.tsx
src/lib/Scenes/City/Components/AllEvents.tsx
src/lib/Scenes/City/Components/__tests__/AllEvents-tests.tsx
src/lib/Scenes/City/__tests__/City-tests.tsx
src/lib/Scenes/Map/Components/FiltersBar.tsx
src/lib/Scenes/Map/Components/__tests__/FiltersBar-tests.tsx
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Map/types.ts

I haven't finished the Objective-C code yet but wanted to get this in. It's not much, but it sets things up to be filled in:

City view data marshalling

---

scripts/merge-graphql-query-map.js

Fixes update metaphysics querymap script

---

CHANGELOG.md
src/lib/Scenes/Fair/Components/FairHeader/index.tsx

- https://artsyproduct.atlassian.net/browse/LD-238

LD-238 - Adds spacer between fair entities

---

README.md
docs/troubleshooting.md

Ran into few issues during install, adding the solutions to troubleshooting doc.

Add docs about troubleshooting installs

---

CHANGELOG.md
src/lib/Components/Markdown.tsx
src/lib/Components/__tests__/Markdown-tests.tsx

This could/should improve the animation performance on fairs

Adds a componentshouldupdate to the Markdown component

---

CHANGELOG.md
src/lib/Scenes/Fair/Components/FairHeader/CountdownTimer.tsx
src/lib/Scenes/Fair/Components/FairHeader/__tests__/CountdownTimer-tests.tsx
src/lib/Scenes/Fair/Components/FairHeader/index.tsx

- https://artsyproduct.atlassian.net/browse/LD-245

Adds display date to CountDownTimer

---

CHANGELOG.md
Example/Emission/ARRootViewController.m
Example/Podfile.lock
Pod/Classes/ViewControllers/ARCityComponentViewController.m
Pod/Classes/ViewControllers/ARComponentViewController.h
Pod/Classes/ViewControllers/ARComponentViewController.m
Pod/Classes/ViewControllers/ARFairComponentViewController.m
Pod/Classes/ViewControllers/ARMapComponentViewController.m
Pod/Classes/ViewControllers/ARMapContainerViewController.h
Pod/Classes/ViewControllers/ARMapContainerViewController.m
package.json
src/lib/Icons/ChevronIcon.tsx
src/lib/Icons/Crosshair.tsx
src/lib/Scenes/City/City.tsx
src/lib/Scenes/City/Components/AllEvents.tsx
src/lib/Scenes/City/Components/FairEventSection/index.tsx
src/lib/Scenes/Fair/Screens/FairDetail.tsx
src/lib/Scenes/Map/Components/CitySwitcherButton.tsx
src/lib/Scenes/Map/Components/FiltersBar.tsx
src/lib/Scenes/Map/Components/ShowCard.tsx
src/lib/Scenes/Map/Components/UserPositionButton.tsx
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Map/MapRenderer.tsx

New Map filter design 

---

package.json
yarn.lock

I've wrapped up the last of the TODOs for [Pull Lock](https://github.com/orta/pull-lock), so gonna get it shipped.

Adds pull-lock 1.0 to the app

---

CHANGELOG.md
src/lib/Icons/Pin.tsx
src/lib/Scenes/Show/Components/Shows/Components/ShowItem.tsx
src/lib/Scenes/Show/Components/Shows/Components/__tests__/__snapshots__/ShowItem-tests.tsx.snap
src/lib/Scenes/Show/Components/Shows/__tests__/__snapshots__/index-tests.tsx.snap

LD-254
Shows an icon on the placeholder, I debated making this a global component but no-one else has needed it so it can wait.

Improve the placeholder for a show

---

CHANGELOG.md
src/lib/Scenes/City/Components/Event/index.tsx

https://artsyproduct.atlassian.net/browse/LD-265

Make sure event name is ellipsis(ed?)

---

src/lib/Scenes/Fair/Components/FairHeader/__tests__/CountdownTimer-tests.tsx

This is the technique they use in the [timer tests](https://github.com/artsy/emission/blob/fcb48de8de7d728cc9a1e29f17e67d7221b0e1e1/src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx).
#trivial

Fix timezone tests

---

CHANGELOG.md
Emission.podspec
Example/Podfile.lock
package.json
src/lib/Components/LocationMap/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/Components/LocationMap/index.tsx

Fixes LD-187
Allows clicking on a map and opening up a set of different maps providers, and lets you copy it for whatever obscure app you use also.

Adds clickable links for a map preview

---

CHANGELOG.md
src/lib/Scenes/Fair/Components/FairBoothHeader.tsx

Fixes [LD-275](https://artsyproduct.atlassian.net/browse/LD-275).

Fixes follow button.

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARCityPickerComponentViewController.h
Pod/Classes/ViewControllers/ARCityPickerComponentViewController.m
Pod/Classes/ViewControllers/ARMapContainerViewController.m
src/lib/Scenes/City/CityPicker.tsx
src/lib/Scenes/City/Components/Event/index.tsx

Fixes [LD-159](https://artsyproduct.atlassian.net/browse/LD-159). Also fixes a crash for shows with missing `cover_image` properties. Also fixes the problem where the checkmark wasn't being displayed in the city picker. 
#native_no_changes #skip_new_tests

Remembers users' city selections

---

src/lib/Scenes/City/Components/TabFairItemRow/index.tsx

- https://artsyproduct.atlassian.net/browse/LD-324
- Also fixes date range
( note key error in gif is fixed in https://github.com/artsy/emission/pull/1394 ) 
#trivial

LD-324 - Fixes link to fair in TabFairItemRow

---

scripts/merge-graphql-query-map.js

/cc @l2succes  cause we failed with our last attempt, but I think me + @ashfurrow got it this time
#trivial

Fix the deploy script when the metaphysics changes are a NOOP

---

src/lib/Scenes/City/City.tsx

Remove log

---

src/lib/Scenes/Fair/Components/FairHeader/index.tsx
src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
src/lib/Scenes/Show/Components/ShowHeader/__tests__/__snapshots__/ShowHeader-tests.tsx.snap

Show 3 artists instead of 2 in an entity list

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARMapContainerViewController.m
package.json

Also fixes the map not re-centring on newly-selected city. Fixes LD-355.

Fixes top buttons re-appearing behind city picker

---

CHANGELOG.md
Example/Podfile.lock
src/lib/Scenes/City/City.tsx
src/lib/Scenes/Map/EventEmitter.ts
src/lib/Scenes/Map/GlobalMap.tsx

Fixes https://artsyproduct.atlassian.net/browse/LD-375

[EventEmitter] Add unsubscribing capabilities.

---

src/lib/Scenes/City/Components/CityTab.tsx

- https://artsyproduct.atlassian.net/browse/LD-377
#trivial

LD-377 - Fixes console error about textAlign

---

src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Map/types.ts

I want to start looking at adding the fairs, so I documented and did some minor refactors to get an idea of what I'm looking at.
#trivial

Minor refactor and a quick document run for GlobalMap

---

CHANGELOG.md
src/lib/Scenes/City/Components/CityTab.tsx

Fixes https://artsyproduct.atlassian.net/browse/LD-362

[CityTab] Increase FlatList’s window size to avoid blank views.

---

Pod/Classes/Data/ARCity.m
src/lib/Scenes/City/Components/CityTab.tsx
src/lib/Scenes/City/cities.ts
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Map/types.ts
src/lib/utils/convertCityToGeoJSON.ts

This is only c384c45 but it contains #1414 because I needed those types
But I believe this fixes LD-350 
#trivial #native_no_changes #skip_new_tests

Remove cluster limits & runtime protection

---

CHANGELOG.md
src/lib/Scenes/Map/Bucket.ts
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Map/types.ts
src/lib/utils/convertCityToGeoJSON.ts

This shows everything for now, about to rebase.

Adds Fairs to the map

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARMapContainerViewController.m
src/lib/Components/Lists/ShowItemRow.tsx
src/lib/Scenes/City/City.tsx
src/lib/Scenes/City/CityPicker.tsx
src/lib/Scenes/City/Components/AllEvents.tsx
src/lib/Scenes/City/Components/BMWEventSection/__tests__/index-tests.tsx
src/lib/Scenes/City/Components/BMWEventSection/index.tsx
src/lib/Scenes/City/Components/Event/index.tsx
src/lib/Scenes/City/__tests__/City-tests.tsx
src/lib/Scenes/Fair/Screens/FairBMWArtActivation.tsx
src/lib/Scenes/Map/Components/ShowCard.tsx
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/utils/track.ts

- https://artsyproduct.atlassian.net/browse/LD-230
- Will need to revisit analytics once all city list views are enabled.
- I've marked a "y" next to rows that are finished in the spreadsheet, and all "green" rows are finished
#native_no_changes

Map & city analytics v1.0

---

data/schema.graphql

- Adds `dayThreshold` and `includeStubShows` to schema
#trivial

Adds dayThreshold and includeStubShows to schema

---

scripts/merge-graphql-query-map.js

Follow-up to https://github.com/artsy/emission/pull/1397.

Fixes querymap script #trivial

---

data/schema.graphql
src/lib/Components/Lists/SavedFairItemRow.tsx
src/lib/Scenes/City/CityFairList.tsx
src/lib/Scenes/City/Components/TabFairItemRow/index.tsx

- Fixes crash in fair list and small styling change
#trivial

Fixes fair list crash

---

src/lib/Scenes/City/Components/AllEvents.tsx
src/lib/Scenes/City/Components/SavedEventSection/index.tsx

[Links to  LD-329](https://artsyproduct.atlassian.net/browse/LD-329)
#trivial

updates copy on All Events tab

---

src/lib/Scenes/Map/Components/ShowCard.tsx

JIRA: https://artsyproduct.atlassian.net/browse/LD-400
#trivial

Fix bugs with cluster card carousel

---

CHANGELOG.md
Example/Podfile.lock
src/lib/Icons/PinFairSelected.tsx
src/lib/Icons/PinSavedOn.tsx
src/lib/Scenes/City/Components/SavedEventSection/index.tsx
src/lib/Scenes/Favorites/index.tsx
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Map/types.ts
src/lib/utils/convertCityToGeoJSON.ts

This PR adds saved fair icon to city map and fixes SVG styling on map pins.
This ticket links to the following Jira tickets
[LD-67](https://artsyproduct.atlassian.net/browse/LD-67)
[LD-425](https://artsyproduct.atlassian.net/browse/LD-425)
[LD-426](https://artsyproduct.atlassian.net/browse/LD-426)
[LD-431](https://artsyproduct.atlassian.net/browse/LD-431)
[LD-419](https://artsyproduct.atlassian.net/browse/LD-419)

City Map Pin SVG fixes

---

CHANGELOG.md
src/lib/Scenes/City/Components/EventList.tsx

Fixes https://artsyproduct.atlassian.net/browse/LD-402

 [City] Make event list scroller not jump.

---

Example/Podfile.lock
src/lib/Scenes/City/CityBMWList.tsx
src/lib/Scenes/City/Components/AllEvents.tsx

- Fixes All tab by removing `scrollEnabled={false}`
- Adds theme around BMW list view
#trivial

Bmw art list section

---

CHANGELOG.md
Example/Podfile.lock
Pod/Classes/ViewControllers/ARMapContainerViewController.m
package.json
src/lib/Components/ScrollableTabBar.tsx
src/lib/Scenes/City/City.tsx
yarn.lock

This updates the styling of the tab bar and begins addressing animation performance issues on the ScrollableTabView. 
TODO:
Before:
After:

Update scrollable tab bar

---

CHANGELOG.md
Example/Podfile.lock
Pod/Classes/ViewControllers/ARMapContainerViewController.m
package.json
src/lib/Components/ScrollableTabBar.tsx
src/lib/Scenes/City/City.tsx
src/lib/Scenes/Map/GlobalMap.tsx

Make sure mapbox attribution is visible

---

scripts/release.js

Update the changelog in the deploy script

---

CHANGELOG.md
Example/Podfile.lock
Pod/Classes/ViewControllers/ARMapContainerViewController.m

I saw the failure on `master`: https://circleci.com/gh/artsy/emission/1183 Not sure how that got by CI. #native_no_changes

Fixes compiler error #trivial

---

CHANGELOG.md
src/lib/Scenes/Fair/Components/FairHeader/index.tsx

Discussed in Slack: https://artsy.slack.com/archives/CFNFWD5F0/p1552580155111900 Jira ticket incoming.

Removes gallery context from fair page

---

CHANGELOG.md
src/lib/Scenes/City/Components/AllEvents.tsx
src/lib/Scenes/City/Components/EventSection/index.tsx

- https://artsyproduct.atlassian.net/browse/LD-457
- City preview bricks only use shows with images

LD-457 - City preview bricks

---

Example/Emission/Info.plist
src/lib/Components/LocationMap/index.tsx

Fixes LD-414 - gonna submit the Eigen side and self-merge for the plist.
#trivial

Google maps fix

---

CHANGELOG.md
src/lib/Scenes/Favorites/Components/Artists/Relay/FavoriteArtists.tsx
src/lib/Scenes/Favorites/Components/Artworks/Relay/FavoriteArtworks.tsx
src/lib/Scenes/Favorites/Components/Categories/Relay/FavoriteCategories.tsx
src/lib/Scenes/Favorites/Components/Fairs/Relay/FavoriteFairs.tsx
src/lib/Scenes/Favorites/Components/Shows/Relay/FavoriteShows.tsx
src/lib/relay/QueryRenderers.tsx

Fixes https://artsyproduct.atlassian.net/browse/LD-415

[relay] Make sure Map/City/Show/Favorites views all use the same environment and store.

---

CHANGELOG.md
src/lib/Components/ScrollableTabBar.tsx
src/lib/Scenes/City/City.tsx

Just a small change to improve tab switching performance a bit. A better solution to come

Optimize tab switching in city view #trivial

---

CHANGELOG.md
Pod/Classes/Data/ARCity.m
data/cityDataSortedByDisplayPreference.json
scripts/generate-cities-objc.js

Makes sure we always have the latest. I also ran the script with the changes.

Deploy script syncs local data with Metaphysics

---

CHANGELOG.md
Example/Podfile.lock
scripts/release.js

Trying to remove more post deployment diff faff.
#trivial

Reduce release churn

---

CHANGELOG.md
src/lib/Scenes/Favorites/Components/Shows/index.tsx

[Links to LD-346](https://artsyproduct.atlassian.net/browse/LD-346)

Updates copy in Shows tab on Favorites

---

src/lib/Components/Lists/ShowItemRow.tsx

- https://artsyproduct.atlassian.net/browse/LD-470
#trivial

LD-470 - Fixes multiple instances of show opening on tap

---

src/lib/Scenes/City/cityTabs.ts
src/lib/Scenes/Map/GlobalMap.tsx

- Museums now appear in all shows on map
- Fixes cluster size for clusters of 5 and less shows to be the same size
- https://artsyproduct.atlassian.net/browse/LD-483
#trivial

LD-483 - Adds museums to all shows

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARMapContainerViewController.m
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Map/MapContainer.tsx
src/lib/Scenes/Map/MapRenderer.tsx
src/lib/Scenes/Map/__stories__/Map.story.tsx

Fixes [LD-495](https://artsyproduct.atlassian.net/browse/LD-495).

User location button hides when user is outside of currently selected city

---

src/lib/Scenes/City/cityTabs.ts

- Checks for bucket.museums before concat
#trivial

Checks for bucket.museums

---

src/__generated__/CitySavedList_viewer.graphql.ts
src/lib/Scenes/Favorites/Components/Shows/index.tsx

[Links to LD-518](https://artsyproduct.atlassian.net/browse/LD-518)
#trivial

Fixes padding on global saves/follows Show list items

---

src/lib/Components/Lists/ShowItemRow.tsx
src/lib/Scenes/City/Components/Event/index.tsx
src/lib/utils/track.ts

- this was a request from abhiti

Removes openShow from tracking #trivial

---

CHANGELOG.md
src/lib/Components/ScrollableTabBar.tsx

Fixes scrollable tab bar on global saves & follows

---

src/lib/Scenes/Show/Screens/MoreInfo.tsx

- Fixes doubled press release in show more info
- https://artsyproduct.atlassian.net/browse/LD-539
#trivial

LD-539 - Fixes doubled press release in show more info

---

src/lib/Scenes/Fair/Components/FairBoothPreview/Components/FairBoothPreviewHeader.tsx

- Coerces string to boolean for RN upgrade
#trivial

Location is now a boolean in FairBoothPreviewHeader #trivial

---

src/lib/Components/Artist/Shows/Metadata.tsx
src/lib/Components/ArtistListItem.tsx
src/lib/Components/ArtworkGrids/Artwork.tsx
src/lib/Components/Bidding/Components/BidInfoRow.tsx
src/lib/Components/Bidding/Components/Checkbox.tsx
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/SelectCountry.tsx
src/lib/Components/Buttons/DarkNavigationButton.tsx
src/lib/Components/EntityList/index.tsx
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Components/LocationMap/index.tsx
src/lib/Components/Show/ShowArtworksPreview.tsx
src/lib/Scenes/City/CityFairList.tsx
src/lib/Scenes/City/Components/AllEvents.tsx
src/lib/Scenes/City/Components/Event/index.tsx
src/lib/Scenes/City/Components/FairEventSection/Components/FairEventSectionCard.tsx
src/lib/Scenes/Fair/Components/ArtworksPreview.tsx
src/lib/Scenes/Fair/Components/FairBoothHeader.tsx
src/lib/Scenes/Fair/Components/FairBoothPreview/Components/FairBoothPreviewHeader.tsx
src/lib/Scenes/Fair/Components/FairHeader/index.tsx
src/lib/Scenes/Fair/Screens/FairDetail.tsx
src/lib/Scenes/Favorites/index.tsx
src/lib/Scenes/Home/index.tsx
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Settings/MyProfile.tsx
src/lib/Scenes/Show/Components/ShowEventSection.tsx
src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx

Fixes all strings instances to boolean for RN

---

CHANGELOG.md
src/lib/Scenes/City/Components/AllEvents.tsx

- BMW shows' save button was not being updated after clicked
- https://artsyproduct.atlassian.net/browse/LD-552

LD-552 - Fixes BMW save button

---

CHANGELOG.md
src/lib/Scenes/Fair/Screens/FairDetail.tsx
src/lib/data/constants.ts

- Fairbooths now only pull 5 shows per page on connection

Fair pagination count

---

CHANGELOG.md
src/lib/Scenes/Map/MapRenderer.tsx
src/lib/relay/middlewares/cacheMiddleware.ts

- Reduces Emission's City cache TTL to 2 hours

Emission map TTL cache

---

Pod/Classes/GraphQL/ARGraphQLQueryCache.m

Fixes assertion exiting the app

Remove assertion for createdAt file

---

scripts/deploy-react-native-podspecs.js

So that it's easy to understand what needs deploying on RN updates

Adds a script for deploying the RN podspecs

---

renovate.json

It's le sad. 
But let's not spam their github 👍

Remove departed artsy friends from renovate 😭

---

CHANGELOG.md
src/lib/Scenes/Artwork/Artwork.tsx

We're doing a beta demo
#skip_new_tests #trivial

[Beta Deploy] Update color from red to green

---

apollo.config.js
src/lib/tests/MockRelayRenderer.tsx
src/lib/tests/renderRelayTree.tsx

[vscode] Configure vscode-apollo

---

package.json
yarn.lock

Removes an unneeded devDep. 
#trivial

[Lib] Remove unneeded @codemods-js/cli package #trivial

---

src/lib/Components/Bidding/Screens/SelectCountry.tsx
src/lib/Components/Consignments/Screens/Location.tsx

As discussed, this shouldn't be necessary for development and in any case we shouldn't offer a key we initially registered to the public.

Try to remove fall-back maps key #trivial

---

src/lib/Components/Picker.tsx

Remove stray console.log #trivial 

---

data/schema.graphql

Similar to https://github.com/artsy/reaction/pull/2557. Updates MP schema with vortex breaking schema changes.

Update MP schema

---

CHANGELOG.md
src/lib/Components/Consignments/Components/BottomAlignedButton.tsx
src/lib/Components/Consignments/Components/DoneButton.tsx
src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
src/lib/Components/Consignments/__stories__/BottomAligned.story.tsx
src/lib/Containers/Inquiry.tsx
src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap

- https://artsyproduct.atlassian.net/browse/PURCHASE-1000

[iOS Bug Bash] - PURCHASE-1000 - Button clip

---

src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx

- https://artsyproduct.atlassian.net/browse/PURCHASE-1261
#trivial

PURCHASE-1261 - Fixes artwork title wrap

---

CHANGELOG.md
src/lib/Components/Bidding/Components/PaymentInfo.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/PaymentInfo-tests.tsx.snap
src/lib/Components/Bidding/Screens/CreditCardForm.tsx
src/lib/Components/Bidding/Screens/__tests__/CreditCardForm-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/CreditCardForm-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/AUCT-470
making a new PR that kicks off a build and Peril will let me know what I should do...

Update copy on credit card registration screen

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/AUCT-471
Another simple copy update.

Update copy on returning registration view

---

src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap

addresses https://artsyproduct.atlassian.net/browse/AUCT-500
See [my comment below](https://github.com/artsy/emission/pull/1738#issuecomment-513883755) for more details. #trivial

Remove .only and fix tests in ConfirmBid-tests.tsx

---

src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx

Just consolidating the `renderer.create(...)` calls... #trivial

Refactor ConfirmBid-tests.tsx

---

src/__generated__/BidderPositionQuery.graphql.ts
src/lib/Components/Bidding/Screens/ConfirmBid/BidderPositionQuery.ts
src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx

blocked by https://github.com/artsy/emission/pull/1743
The danger message is a false alarm as this PR does not include any behavioral change.
#trivial #skip_new_tests

Add more type checks

---

CHANGELOG.md
patches/graphql+0.13.2.patch

[v2] Remove patch to surpress `__id` errors from graphql-js

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/RegistrationResult.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap

addresses https://artsyproduct.atlassian.net/browse/AUCT-508
Just a quick copy update:

Fix copy on registration pending view

---

.autorc
package.json
yarn.lock

Adds .autorc and extends @artsy config

---

.circleci/config.yml

Fixing auto-release script take 2

---

src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx

[InfiniteScrollArtworksGrid] Small refactor cleanup

---

src/lib/Scenes/Artwork/Components/CommercialButtons.tsx

- https://artsyproduct.atlassian.net/browse/PURCHASE-1381
#trivial

PURCHASE-1381 - Handle order mutation error

---

CHANGELOG.md
src/lib/Scenes/Map/GlobalMap.tsx

Fixes https://artsyproduct.atlassian.net/browse/PLATFORM-1688

[City Guide] Fix clicking on single pin on map

---

src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
src/lib/utils/track/schema.ts

- Adds analytics to `CommercialButtons`
#trivial

Adds CommercialButton analytics

---

src/lib/Components/ArtistListItem.tsx
src/lib/Components/WorksForYou/Notification.tsx
src/lib/Containers/WorksForYou.tsx

- https://artsyproduct.atlassian.net/browse/PLATFORM-1706 / https://artsyproduct.atlassian.net/browse/PURCHASE-1437: Fixes crash when artist name clicked on Artist tab 
- Fixes crash if `image.url` is missing in `ArtistListItem`
#trivial

PLATFORM-1706/PURCHASE-1437: Fixes crash when Artist name tapped in Artist tab

---

src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx

- https://artsyproduct.atlassian.net/browse/PURCHASE-1434
#trivial

PURCHASE-1434 - Small typography change

---

src/lib/Components/ArtistListItem.tsx
src/lib/Components/ArtworkGrids/GenericGrid.tsx
src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
src/lib/Scenes/Fair/Screens/FairBMWArtActivation.tsx
src/lib/utils/track/schema.ts

- https://artsyproduct.atlassian.net/browse/PURCHASE-1327
- Fixes analytic types
#trivial

PURCHASE-1327 - Fixes analytic typing

---

src/lib/Components/ScrollableTabBar.tsx

- Fixes crash reported today on tabs
#trivial

Check for scrollview before scrolling

---

package.json
yarn.lock

Now also has operation defined variable validation.
#trivial

[package] Update vscode-apollo-relay to v1.1.0

---

package.json
yarn.lock

[package] Update vscode-apollo-relay to v1.1.1

---

package.json
src/__generated__/CitySectionList_city.graphql.ts
src/lib/Scenes/City/CitySectionList.tsx
yarn.lock

[package] Update vscode-apollo-relay to v1.3.0

---

src/lib/AppRegistry.tsx
src/lib/Components/ArtistListItem.tsx
src/lib/Components/Show/ShowArtistsPreview.tsx
src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
src/lib/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx
src/lib/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
src/lib/Scenes/Artwork/Components/PartnerCard.tsx
src/lib/utils/track/schema.ts

- https://artsyproduct.atlassian.net/browse/PURCHASE-1485
- Schema: https://docs.google.com/spreadsheets/d/1P6qUe7yFPzly5JYicAa6eQ3BAy9s7Bx1_6k-Q5hB-Pw/edit#gid=868762451
#trivial

[Artwork View] PURCHASE-1485 - Analytics fixes and updates

---

src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx

#trivial
https://artsyproduct.atlassian.net/browse/PURCHASE-1488

PURCHASE-1488 increase image carousel base resolution

---

CHANGELOG.md
src/lib/Scenes/Home/index.tsx

Fixes https://artsyproduct.atlassian.net/browse/PLATFORM-1781

[Home] Stop scroll-to-top behaviour on Artists/Auctions tabs.

---

src/lib/Components/Home/ArtistRails/ArtistRail.tsx

[ArtistRail] Fix rendering of ArtistCard

---

src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
src/lib/Components/ArtworkGrids/__tests__/__snapshots__/ArtworkGridItem-tests.tsx.snap

Fixes bid badges aligment

---

src/lib/Components/Inbox/Conversations/__stories__/ConversationSnippet.story.tsx
src/lib/Components/Inbox/Conversations/__tests__/ConversationSnippet-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap

Fixes mock in ConversationSnippet

---

src/lib/Components/Inbox/Conversations/__stories__/ConversationSnippet.story.tsx
src/lib/Components/Inbox/Conversations/__tests__/ConversationSnippet-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/Conversations-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap

- Updates snapshots with updated camelCase field names
#trivial

Updates more snapshots

---

src/lib/Components/Consignments/Submission/__tests__/consignmentSetupToSubmission-tests.ts
src/lib/Components/Consignments/Submission/consignmentSetupToSubmission.ts

https://artsyproduct.atlassian.net/browse/PURCHASE-1514 && https://sentry.io/organizations/artsynet/issues/1233416292/?project=299973&query=is%3Aunresolved&statsPeriod=14d
Switch `dimensions_metric` to `dimensionsMetric`

Fix wrong input param and switch to new fancy shiny cammelCase one #trivial

---

Example/Podfile.lock
patches/react-native+0.59.2.patch
src/lib/Components/Consignments/Components/FormElements.tsx
src/lib/Components/Consignments/Screens/Overview.tsx

https://artsyproduct.atlassian.net/browse/PURCHASE-1510
Makes sure the button is not tappable until all the relevant info has been given.
#trivial

PURCHASE-1510 Disable submit button in consignments flow

---

CHANGELOG.md
src/lib/AppRegistry.tsx
src/lib/Scenes/Artwork/Artwork.tsx
src/lib/Scenes/Artwork/__stories__/Artwork.story.tsx
src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx

Worked on this during today's knowledge share.
#trivial

PURCHASE-1513 Refetches Artwork page query on re-appear

---

src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx

- https://artsyproduct.atlassian.net/browse/PURCHASE-1541
- Ask a specialist now links to `specialist@`
- Adds link to Auction FAQ
#trivial

PURCHASE-1541 - Fixes extralinks

---

Example/Podfile.lock
src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx

- https://artsyproduct.atlassian.net/browse/PURCHASE-1536
#trivial

PURCHASE-1536 - Fixes sale message for closed auctions

---

src/lib/Components/Artist/Articles/Article.tsx
src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
src/lib/Components/Inbox/ActiveBids/ActiveBid.tsx
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
src/lib/Components/Lists/SavedFairItemRow.tsx
src/lib/tests/__tests__/MockRelayRendererFixtures.tsx

- Adds safety around using `image.url` which we were seeing a JS error in Sentry
- https://artsyproduct.atlassian.net/browse/PURCHASE-1547
#trivial

PURCHASE-1547 - Adds safety to image.url

---

CHANGELOG.md
src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx

After testing realized for Bid and Max Bid we don't see any analytics when clicking bid button.
`@track` method was added to two methods that were not used anywhere.
Move track method to `handleRegisterBid` method and conditionally set the proper `action_name`.

Follow up on original attempt to add auction analytics

---

src/lib/Containers/WorksForYou.tsx
src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap
src/lib/Scenes/Home/Components/ForYou/index.tsx

#trivial
- https://artsyproduct.atlassian.net/browse/ME-39

ME-39 - Adds spinner to home page tabs when loading more

---

src/lib/Scenes/Home/index.tsx

#trivial
- https://artsyproduct.atlassian.net/browse/ME-51
- On app launch the WorksForYou was the default tab, we want to keep it consistent with sign up and have the user land on the ForYouTab by default

ME-51 - Load ForYouTab on launch

---

src/lib/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx

- https://artsyproduct.atlassian.net/browse/ME-21
...nothing happens
#trivial

ME-21 - Moving chevron

---

src/lib/Components/Inbox/Conversations/Composer.tsx

- https://artsyproduct.atlassian.net/browse/ME-32
#trivial

ME-32 - Fixes Composer text input clip

---

CHANGELOG.md
src/lib/Components/Buttons/DarkNavigationButton.tsx
src/lib/Components/Buttons/__stories__/Buttons.story.tsx
src/lib/Components/Buttons/__tests__/__snapshots__/DarkNavigationButton-tests.tsx.snap
src/lib/Scenes/Favorites/index.tsx
src/lib/Scenes/Home/index.tsx

- I'd really love to change the name of this component down the road too if we are keeping it.
- https://artsyproduct.atlassian.net/browse/ME-62

ME-62 - Center DarkNavigationButton content

---

src/lib/Components/States/ZeroState.tsx
src/lib/Components/States/__stories__/ZeroState.story.tsx
src/lib/Components/States/__tests__/ZeroState-tests.tsx
src/lib/Containers/WorksForYou.tsx
src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap
src/lib/Scenes/Favorites/Components/Artists/index.tsx
src/lib/Scenes/Favorites/Components/Artworks/index.tsx
src/lib/Scenes/Favorites/Components/Categories/index.tsx
src/lib/Scenes/Favorites/Components/Fairs/index.tsx
src/lib/Scenes/Favorites/Components/Shows/index.tsx

https://artsyproduct.atlassian.net/browse/ME-58

ME-58 fix saved artworks zero state

---

src/lib/Containers/WorksForYou.tsx

https://artsyproduct.atlassian.net/browse/ME-42
Just need to throw away the previous data source and make a new one.

ME-42 Make sure artists feed is up-to-date on refresh

---

Example/Podfile.lock

Includes this fix: https://github.com/artsy/extraction/pull/12
Not sure why `Pulley` keeps churning, I'll take a look later.

Updates Extraction #trivial

---

Example/Emission/ARRootViewController.m
src/lib/Scenes/Artwork/Components/AuctionPrice.tsx

https://artsyproduct.atlassian.net/browse/AUCT-677 🔒

AUCT-677 update buyer's premium copy

---

src/lib/Scenes/Partner/Components/PartnerOverview.tsx

We found this tiny improvement during knowledge share.

hide artists list when no artists

---

src/lib/Scenes/Partner/Components/PartnerHeader.tsx

- Condenses partner header to be slightly smaller
#trivial

Condenses partner header

---

src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
src/lib/Scenes/Partner/Components/PartnerOverview.tsx
src/lib/Scenes/Partner/Components/PartnerShows.tsx

- Adds spinners to the bottom of artworks, artists and shows on the new Partner view

Adds spinners to partner page

---

Example/Emission/ARRootViewController.m
src/lib/Scenes/Partner/Components/PartnerOverview.tsx
src/lib/Scenes/Partner/Partner.tsx

Small cleanup of unused code

---

Example/Emission/AppDelegate.m
Pod/Classes/Core/ARSwitchBoardModule.h
Pod/Classes/Core/ARSwitchBoardModule.m
src/lib/Components/StickyTabPage/StickyTabPage.tsx
src/lib/Components/StickyTabPage/StickyTabScrollView.tsx

[MX-114] Infrastructure for hiding back button on Partner view

---

README.md

I was updating Eigen's docs and noticed that these were out of date.

Adds note about auto-deploys

---

README.md

- Updates point people in `readme`

Updates point people

---

src/lib/Components/Consignments/Screens/Welcome.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx.snap
src/lib/Components/Consignments/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/Components/Inbox/Conversations/ZeroStateInbox.tsx
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/Inbox.tsx
src/lib/Containers/__tests__/Inbox-tests.tsx

- Modernizing these views and move into `FlatList`

Refactor and modernize Consignments/Welcome & Inbox empty state

---

.circleci/config.yml

@ashfurrow noticed we were not running unit tests on master 😬 https://github.com/artsy/emission/commit/27129edb1d4aef158f1cfdd8de19f165e6d7c137#commitcomment-36311454

Run unit tests on master

---

src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx

@kierangillen This fixes that issue you saw during QA
Might want to view the diff with whitespace changes turned off, looks like the recent prettier upgrade changed the indentation of this whole block.

Fix sticky tab header positioning when content is not so high

---

src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/__tests__/partnerName-tests.tsx
src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/partnerName.tsx

Small QA task from https://artsyproduct.atlassian.net/browse/AUCT-771.

Correct the punctuation for e.g. Phillips

---

src/lib/Scenes/Settings/MyProfile.tsx
src/lib/Scenes/Settings/__tests__/__snapshots__/MyProfile-tests.tsx.snap

As discussed on Slack: https://artsy.slack.com/archives/CR1QUK16X/p1578604587001400?thread_ts=1576534180.010600&cid=CR1QUK16X

Changes settings screen to use sentence case #trivial

---

src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
src/lib/Scenes/Settings/MyProfile.tsx
src/lib/Scenes/Settings/__tests__/__snapshots__/MyProfile-tests.tsx.snap

Changes header to Sans font #trivial

---

src/lib/Scenes/Search/Input.tsx

~WIP waiting for artsy/palette#627~
https://artsyproduct.atlassian.net/browse/MX-137

[MX-137] Use XCirlceIcon

---

README.md
docs/adding_new_keys.md

Just some cleanup in docs now that nebula deploys are retired.

Remove nebula mentions from docs

---

src/lib/Scenes/Search/SearchResult.tsx

https://artsyproduct.atlassian.net/browse/MX-153

[MX-153] Truncate search result titles at one line

---

Pod/Classes/ViewControllers/ARShowConsignmentsFlowViewController.m
package.json

https://artsyproduct.atlassian.net/browse/MX-155

[MX-155] set consignments vc background color

---

src/lib/Scenes/Collection/Screens/CollectionHeader.tsx

Fixes bugs reported in these Jira tickets after QAing:
- https://artsyproduct.atlassian.net/browse/FX-1422
- https://artsyproduct.atlassian.net/browse/FX-1600

Collections Metadata QA Fixes

---

Pod/Classes/ViewControllers/ARShowConsignmentsFlowViewController.m

Follow-up from https://github.com/artsy/emission/pull/1993 and https://github.com/artsy/eigen/pull/2997

Fixes Consignments status bar content colour

---

src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap

https://artsyproduct.atlassian.net/browse/FX-1422

Adds conditional padding to collection title

---

src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
src/lib/Components/Consignments/Screens/__tests__/SelectFromPhotoLibrary-tests.tsx

https://artsyproduct.atlassian.net/browse/MX-160

[MX-160] Prevent crash when camera roll permission denied

---

Pod/Classes/Core/ARSwitchBoardModule.m
src/lib/NativeModules/SwitchBoard.tsx
src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx

This PR changes the CCPA request's email compose window to include the following as body text in the email:
```txt
Hello, I'm contacting you to ask that...
```

Specifies email body in privacy requests

---

Makefile

- Sync makefile node version with nvmrc

Sync makefile node version with nvmrc #trivial
