artsy/emission

README.md

There's probably a reason why it's not in there :P, but I blindly followed the readme instructions, and then had the simulator suggest that I should probably run `npm install`. Thought it might be worth putting in the instructions?

[Readme] add setup step

---

lib/components/artist/articles/article.js
lib/components/artist/articles/index.js
lib/components/artist/related_artists/index.js
lib/components/artist/related_artists/related_artist.js
lib/containers/artist.js

[RelatedArtists] Added a RelatedArtists component

---

lib/components/artist/shows/index.js
lib/components/artist/shows/large_list.js
lib/components/artist/shows/metadata.js
lib/components/artist/shows/small_list.js
lib/containers/artist.js

Added new shows metadata to fragment

---

Pod/Classes/Core/RCTScrollView+EnclosingScrollView.m
lib/components/artist/articles/article.js
lib/components/artist/articles/index.js
lib/components/artworks/index.js
lib/components/opaque_image_view.js

Dynamically sized image fetching.

---

Pod/Classes/OpaqueImageViewComponent/AROpaqueImageView.h
Pod/Classes/OpaqueImageViewComponent/AROpaqueImageView.m
Pod/Classes/OpaqueImageViewComponent/AROpaqueImageViewManager.m
lib/components/opaque_image_view.js

- Only show placeholder color if the image needs downloading. Otherwise you might get to see the color for a very short period, which isn’t the nicest.
- Fade image in.

[ImageView] Refinements

---

Pod/Classes/ViewControllers/ARArtistComponentViewController.h

Needs to match the superclass’ version.

Fix incorrect nullability override.

---

Pod/Classes/Core/ARSwitchBoardModule.m

Fixes #88.
The issue ended up being that the API I was using to map a React ‘component tag’ to a view was not the fast path. In some cases it would just not work at all, I’m unsure why, but haven’t delved into that further. I found a different API that does nothing async, so we get an immediate result and I also chose to get rid of further async dispatching in our switchboard module.

[SwitchBoard] Fix tap handling lag.

---

lib/components/artist/artworks/index.js
lib/components/opaque_image_view.js

Fixes #39.
This change makes it so that when orientation changes on iPad, it fetches new images of the right size.

[ImageView] Always update imageURL after layout changes.

---

lib/components/artist/artworks/grid.js

Turns out that it was trivial to fetch a page multiple times, leading to duplicate works.

[Artworks] Do not fetch the same page multiple times.

---

lib/components/artist/artworks/artwork.js

This artwork doesn't have a partner associated with it, and was crashing upon load (I added a null check inside the view to check; before it wouldn't render anything before the crash):
Now it only renders a `SerifText` view for the partner name if the partner exists:
Fixes #182 
Pending https://github.com/artsy/eigen/issues/1732

Fixed partner name crasher for artworks in grid

---

Example/Emission.xcodeproj/project.pbxproj
lib/containers/artist.js

Fix for iOS 8 crasher

---

lib/modules/events.js
lib/modules/switch_board.js

This is a temporary solution for a crash that we can't reproduce (#179). We should look into better ways to keep track of components going forward.

Fix for findNodeHandle crasher

---

data/schema.graphql
data/schema.json
lib/components/artist/articles/index.js
lib/components/artist/header.js
lib/components/artist/related_artists/index.js
lib/components/artist/shows/large_list.js
lib/components/artist/shows/medium_list.js
lib/containers/artist.js
npm-shrinkwrap.json
package.json

Fixes #181
This finally makes it so that all objects are uniquely identified, regardless of type, and that Relay uses `__id` for that purpose instead of `id`.

Relay Node support.

---

.flowconfig
Example/Podfile.lock
lib/components/artist/related_artists/index.js
lib/components/artist/shows/large_list.js
lib/components/artist/shows/metadata.js
npm-shrinkwrap.json
package.json

With the addition of `alignItems: flex-start`, everything is beautiful again:
Just like they said: https://github.com/facebook/react-native/releases/tag/v0.28.0

Upgraded React Native version and fixed Related Artists layout issue

---

lib/components/artist/shows/index.js

Fixes this problem:
So our Current & Upcoming list looks like this instead:

[Shows] Fixed bug where current and upcoming shows were not properly wrapping

---

lib/components/artist/artworks/index.js
lib/components/artwork_grids/artwork.js
lib/components/artwork_grids/generic_grid.js
lib/components/artwork_grids/infinite_scroll_grid.js
lib/components/home/artwork_rail.js

This grid is exactly like the existing infinite scroll grid without the scroll-to-reload behavior. I've also moved the `artist/artworks` components to a new `artwork_grids` directory so we can use them in both home and artist contexts.

Made a generic artworks grid for home rail

---

Example/Emission/Configuration.h.sample
lib/relay/config.js

Now that I know how we can ensure the required show data for the artist view is available on staging, let’s go back to using staging by default during development.
The issue was that ElasticSearch is not synced/re-indexed on staging after a DB copy. For now I know how to kick-off a job manually, so let me know if/when you need this.

[Relay] Use staging metaphysics in dev mode.

---

lib/components/home/artwork_rails/artwork_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js
lib/containers/home.js

[Home][ArtworkRail] Header Visuals

---

Dangerfile.js
dependencyci.yml
npm-shrinkwrap.json
package.json

Ok, so, our shrinkwrap was out-of-date (still contained removed test packages) and we were missing the `concurrently` package.
Two of our dependencies (`react-native`storybook` and `react-test-renderer`) have version requirements on common dependencies that are unsatisfiable, which means that [npm will not shrinkwrap](https://github.com/npm/npm/issues/10836). However, they work fine at runtime with our current versions.
After going down the rabbit hole for a while, I settled on fixing it by hand-editing the `package.json` files of these two dependencies to bump the version requirements that were troublesome such that they would satisfy. After that I was able to shrinkwrap again, of which this is the result.
I suspect that there will be similar issues in the future when trying to …

[package] Add concurrently back and clean-up shrinkwrap.

---

Example/Emission/AppDelegate.m
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m
lib/relay/config.js

This PR separates the ‘debug’ and ‘use staging/production’ configuration so that it’s possible to e.g. run a debug build using production.

[Config] Add `useStagingEnvironment` option.

---

lib/components/home/artwork_rails/artwork_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js

I tested these in quicksilver and they work so I don't have to make any new routes after all! 😄 
Fixes https://github.com/artsy/eigen/issues/1818

[Home][ArtworksRail] Favorites route + fix for WorksForYou

---

CHANGELOG.md
lib/components/artwork_grids/generic_grid.js
lib/components/home/artwork_rails/artwork_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js
lib/containers/home.js

The `<RefreshControl>` component provided by RN looks and feels great out-of-the-box, but I'm having some Relay trouble.
The `forceFetch` approach in this pr will update all `artwork_modules` that have new `id`'s after the initial Home rendering. This is great for gene rails, which are changed often, and the Related Artist rail, which returns a new set of works and a new artist each time. I'm having trouble with the Recently Saved rail because its `id` does not change even though the works in its child `Grid` container can. I've been reading a lot about Relay but I'm not entirely sure why calling `forceFetch` on the parent Home container doesn't check for changes in the children. I did take a look at the `RootContainer` and its `forceFetch` variable, but I'm not sure what exactly I can do …

[Home] First go at pull-to-refresh

---

lib/components/artwork_grids/generic_grid.js

Otherwise a component for a different artwork (with a different image
aspect ratio) might get re-used for the wrong artwork, leading to
incorrectly scaled images.
Fixes #289.

[Artworks] Use unique artwork component keys. #tiny

---

lib/components/home/artwork_rails/artwork_rail_header.js

This just removes an API call that’s not needed.

[Home] Suggested artists should be new, no need to fetch follow status. #tiny

---

.vscode/settings.json

I’m not sure why JS files were set to be recognised as the `flow` type. It doesn’t appear to exist and JS files would get recognised as plain text files.

Vscode fine tuning

---

CHANGELOG.md
package.json

I was already recommending that you globally install  `typings` in the docs
So having it in our npm deps was superfluous. You can fix this I think with `npm prune` after installing this version.
#trivial

Remove typings from dev deps

---

CHANGELOG.md
Emission.podspec
Example/Emission.xcodeproj/project.pbxproj
Example/Podfile
Example/Podfile.lock

Fixes https://github.com/artsy/eigen/issues/1833
* The required `RCTImage` subspec was only added to the Emission Example app, not the Emission podspec which meant that Eigen did not include that module.
* It turns out that RN does look in the Emission framework bundle when integrated into Eigen, so these assets can be included in the pod as normal.

Fix missing asset

---

lib/components/artist/header.js
lib/components/buttons/inverted_button.js
lib/components/home/artwork_rails/artwork_rail_header.js
lib/components/tab_view.js
lib/containers/artist.js

I've updated the `inverted_button` component to be more malleable since it's used in many different places.
It shows up on both iPhone & iPad now:
And it doesn't look weird on iPad anymore:
Fixes #257 & #285 
Also makes artist view controller more in line with its original spec: https://github.com/artsy/eigen/issues/1132

Fixed inverted button width in artworks header and disappearance in artist cards #tiny

---

CHANGELOG.md
lib/components/home/artist_rails/artist_card.js

Fix #217 and #303. 
@sarahscott apparently you need to explicitly set the `numberOfLines` to 1 so it truncates. Then, you can specify the truncation method (start, middle, end) with `ellipsizeMode` according to [docs](https://facebook.github.io/react-native/docs/text.html#ellipsizemode).

[Artist Rail] Fix showstoppers 

---

CHANGELOG.md
lib/containers/home.js

Oops, seems I exaggerated the amount of memory usage before this change, nonetheless it’s a 30% reduction and, more importantly, the home view now tries to load those rails that are currently on screen instead of possibly those all the way down.
* Before: 135MB
* After: 92MB
----
In addition I made it so that the refresh control is only removed from screen until all Relay requests are finished.

[Home] Reduce memory usage

---

.vscode/extensions.json
docs/running-emission-in-eigen.md

Also adds extension recommendations for Emission inside VS Code, as I had that laying around

Add docs for running eigen locally

---

Example/Podfile
Example/Podfile.lock
Pod/Classes/LoadFailureComponent/ARLoadFailureViewManager.m

The crash occurred because the load failure view would not actually have
a `onRetry` callback while Relay is retrying, but the load failure view
would stop animating prematurely allowing you to tap the retry button
again.
Now the animation does not stop prematurely, you cannot tap the button
while it is still retrying, but you can when Relay failed again.
ARLoadFailureView fix https://github.com/artsy/extraction/pull/8
Fixes https://github.com/artsy/eigen/issues/1867

[LoadFailure] Fix crash that occured when attempting to retry 2nd time.

---

lib/components/home/artist_rails/artist_rail.js

Fix #309 
Cards now bleed to the edge:
There's still additional space at the end of the rail:

[Artist Rail] Fix right margin cutoff of cards by adding spacer view #trivial #tiny

---

CHANGELOG.md
lib/components/artwork_grids/artwork.js

Fixes https://github.com/artsy/eigen/issues/1927
This is simply an educated guess, but it’s a pretty good one.
It’s probably artworks in genes for which we have no associated artists. The existing artwork component didn’t take that into account yet, because previously it was only used for artworks on an artist view, those obviously all have an associated artist.

[Artwork] Don’t crash if there is no artist.

---

.vscode/launch.json
CHANGELOG.md
Example/Emission/AppDelegate.m
lib/components/artist/about.js
lib/components/buttons/navigation_button.js

Fixes the ugly button on iPad, and the URL we redirect to

[Artist] Grab the artist ID so it can be used in the auction results URL

---

CHANGELOG.md
lib/components/artist/shows/large_list.js

Layout was relying on `Dimensions` and this was looking weird on-device; the `layoutEvent` approach works really nicely.

[Artist] Fix for incorrect layout on-device in Artist Shows component

---

Pod/Classes/SwitchViewComponent/ARSwitchViewManager.m

Instead of AutoLayout, which was causing conflicts in Artist and Gene pages, but wouldn't allow Gene rotation on iPad.

[SwitchView] Moves our RN Switch View coordinator to use frame layouts

---

CHANGELOG.md
lib/components/home/artwork_rails/artwork_rail.js
lib/components/home/artwork_rails/artwork_rail_header.js

Fixes #381.
This makes it so that the expand button is part of its parent’s frame, which, as pointed out by @majak, will make it so RN won’t remove the parent view yet:
For context, RN just looks at the frames of the scroll view’s first subviews, not their descendants: https://github.com/alloy/react-native/blob/0.34.1-with-scrollview-fix/React/Views/RCTView.m#L291-L293

[Home/Artworks] Don’t remove (collapsed) artwork rail too early.

---

lib/components/home/artwork_rails/artwork_rail.js

Fix #354.
Looks like it wasn't the asset (they were correct). It was just being stretched in the `<image>` view, so I've added `resizeMode: center`, which keeps the original image ratios etc.

[Home] Add resize mode property to chevron image

---

lib/containers/home.js

For #378. 
Current order:
- Recommended works
- Followed artists
- Related artists
- Followed galleries
- Saved works
- Live auctions
- Current fairs
- Followed genes
- Generic genes
@alloy - it still puts in the artist rail after 2 artwork rails. Is that ok for now / was there a plan to change that in the future? (e.g. in the new order, we sometimes may want a few other rails before showing trending artists, but it's on a case by case basis).

[Home] Move saved works rail further to the top

---

lib/components/related_artists/index.js

Fixes https://github.com/artsy/eigen/issues/2024
I thought this was addressed but I realized it's one of those layout bugs that can only really be seen on-device. I think this is a pattern we should adopt everywhere because it really doesn't seem like `Dimensions` is a reliable source for layout.

[RelatedArtists] Use layoutEvent instead of Dimensions

---

lib/containers/__tests__/__snapshots__/artist-tests.js.snap
lib/containers/__tests__/artist-tests.js

@xtina-starr first emission pr review 🎉 . All it does is add some tests to our Artist view:
Many of our tests are similar to what you use in force with the exception of snapshots. The snapshots are the [React trees generated by Jest](https://facebook.github.io/jest/blog/2016/07/27/jest-14.html) and they're useful for catching changes in the component. Since these are the first snapshots for the Artist container, they're not really that interesting, but over time the [diffs become more useful](https://github.com/artsy/emission/pull/409/files#diff-b4f897fde7641a36650c3d7e54682bad).

[Testing] Added test coverage to Artist container

---

.vscode/settings.json

I added this setting for us to get a consistent flow working in the vscode extension, sure #18 is happening, but better to get this in until then.

Use node_modules flow in vscode

---

.gitignore
.travis.yml
package.json

Before:
```js
Test Suites: 28 passed, 28 total
Tests:       1 skipped, 53 passed, 54 total
Snapshots:   32 passed, 32 total
Time:        21.435s
```
Second run:
```js
Test Suites: 28 passed, 28 total
Tests:       1 skipped, 53 passed, 54 total
Snapshots:   32 passed, 32 total
Time:        5.293s, estimated 18s
```
I noted in #457 that Tests are slow, and they are when you first run them on a fresh clone. This PR means that we can cache the transpiled Jest test objects.

Use a determinate cache folder, which can be cached by Travis in tests

---

dangerfile.js
dangerfile.ts
package.json
tsconfig.json
yarn.lock

Adds the following:
* Any touched (new/modified) react components warn if they are not somewhere inside the storybook stories
* Any touched app files fails if there are no corresponding test files (not changes) - you need to specify that you are not writing tests in the PR body/title
---
WIP as I'm not sure it'll compile etc, I did it offline

Update Dangerfile for noting tests, and stories on a PR

---

CHANGELOG.md
Example/Podfile.lock

No changes from artsy-dev side, updates it with https://github.com/artsy/Artsy-OSSUIFonts/pull/10 and https://github.com/artsy/Artsy-OSSUIFonts/pull/9

Update fonts for OSS consumers

---

CHANGELOG.md
src/lib/containers/home.tsx

Same as #466, but this merges what went into [the 1.2.2 release](https://github.com/artsy/emission/tree/v1.2.2) back into master.
Related to https://github.com/artsy/eigen/issues/2237

[Home] Move active bids module to the top of the feed.

---

Example/Emission/ARRootViewController.h
Example/Emission/ARRootViewController.m
Example/Emission/AppDelegate.m
Example/Emission/AuthenticationManager.h
Example/Emission/AuthenticationManager.m

Exposes the `AuthenticationManager` to the `ARRootViewController` so that it can call logout from the same context.

[Dev] Adds the ability to log out to the app

---

Example/Emission.xcodeproj/project.pbxproj

This converts the code-signing to use [fastlane match](https://artsy.github.io/blog/2017/04/05/what-is-fastlane-match/) so that the build can be deployed via https://github.com/artsy/emission-nebula/pull/1
Self-merging as it shouldn't affect devs working day to day.

[Dev] Use match's Emission profiles for signing.

---

CHANGELOG.md
src/lib/containers/__tests__/__snapshots__/works_for_you-tests.tsx.snap
src/lib/containers/works_for_you.tsx

The `ListView` was going rogue, so now the `ScrollView` handles all scrolling behavior.
Fixes #526

[WFU] Bug fix for strange scrolling behavior

---

CHANGELOG.md
src/lib/components/artwork_grids/__tests__/__snapshots__/artwork-tests.tsx.snap
src/lib/components/artwork_grids/__tests__/artwork-tests.tsx
src/lib/components/artwork_grids/artwork.tsx

Adds bid info for artworks in a sale. Here's a screenshot:
Fixes https://github.com/artsy/emission/issues/487 .
<details>
<summary>The pre-push hook was giving me trouble but I wanted to get this up so I can access it on other machines. I'll take a look at the error tomorrow.</summary>
```
Found '/Users/ash/bin/emission/.nvmrc' with version <6.9>
N/A: version "6.9 -> N/A" is not yet installed.
You need to run "nvm install 6.9" to install it before using it.
Found '/Users/ash/bin/emission/.nvmrc' with version <6.9>
N/A: version "6.9 -> N/A" is not yet installed.
You need to run "nvm install 6.9" to install it before using it.
> husky - npm run -s prepush
yarn run v0.21.3
$ tsc --noEmit --pretty
62       const numberOfBids = artwork.sale_artwork.bidder_positions_count
~~~~~~~~~~~~ …
```

Adds bid information for artworks in sale.

---

CHANGELOG.md
src/lib/components/home/artwork_rails/artwork_rail.tsx

A repeat of https://github.com/artsy/emission/pull/469 which was merged into a 1.2.3 release (that was never merged into master). Fixes #528. Skip New Tests.

Fixes display of artworks in non-expanding grids in artwork rails

---

CHANGELOG.md
Emission.podspec
Example/Emission.xcodeproj/project.pbxproj
Example/Emission/ARAdminTableViewCell.m
Example/Emission/ARAnimatedTickView.m
Example/Emission/AppDelegate.m
Example/Emission/AuthenticationManager.m
Example/Emission/EigenLikeAdminViewController.m
Example/Emission/UnroutedViewController.m
Example/Podfile
Example/Podfile.lock
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m
index.ios.js
package.json
src/lib/error_reporting.ts
yarn.lock

Currently need to use this until it’s merged and released https://github.com/getsentry/react-native-sentry/pull/50. It’s important that we don’t forget to configure Eigen to use this fork as well!
Closes #511

Adds Sentry for React Native

---

Emission.podspec
Example/Podfile.lock
package.json
yarn.lock

My PR got merged and released, so this just switches back from my fork.

[package] Switch back to upstream Sentry SDK. #trivial

---

.vscode/settings.json
CHANGELOG.md
Example/Emission/index.storybooks.js
src/data/colors.ts
src/data/fonts.ts
src/lib/components/buttons/__stories__/buttons.story.tsx
src/lib/components/consignments/__stories__/consignments.story.tsx
src/lib/components/consignments/__stories__/typography.story.tsx
src/lib/components/consignments/typography/index.tsx
src/lib/components/text/__stories__/typography.story.tsx
src/storiesRegistry.js
src/storiesRoot.js

Builds on top of #543 - so, once that's merged I'll move this PR to point at `consignments` instead of the other PR. 
Adds typography setup, trying to get the general design down before writing specific views as it has it's own UI theme

[Consignments] Adds Storyboards and some typography helpers

---

Example/Emission.xcodeproj/project.pbxproj

Looks like we need to change this setting since Swift is being used inside a Pod:
[As deploys were failing](https://github.com/artsy/emission-nebula/issues/3#issuecomment-304456477)
#trivial<hr data-danger="yep"/>
<details>
<p>&nbsp;</p>
<pre><code>git fetch origin pull/571/head:orta-571-checkout
git checkout orta-571-checkout
yarn install
</p>
<p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the phone to get the Admin menu.</p>
<p>If you see <i>"Use Staging React Env" </i> - click that and …

[Dev] Embed Swift libraries

---

CHANGELOG.md
Example/Emission/ARRootViewController.m
Example/Emission/EigenLikeNavigationController.m
Example/Emission/index.ios.js
package.json
src/lib/components/storybooks/index.tsx
src/lib/components/storybooks/section_browser.tsx
src/lib/components/storybooks/story_browser.tsx
src/lib/components/storybooks/styles.tsx
src/storiesRegistry.js
yarn.lock

This means we can move away from these root view controllers in the app entirely, letting the JS control a lot more of the Emission app's flow.
* Re-jiggers the back button to look inside the top view controller for other navigations
* Updates styled-components to the official 2.0 release, now that it's out
Skip New Tests - not really relevant for the dev side of this.<hr data-danger="yep"/>
<details>
<p>&nbsp;</p>
<pre><code>git fetch origin pull/569/head:orta-569-checkout
git checkout orta-569-checkout
yarn install
</p>
<p>Then run <code>xcrun simctl launch booted net.artsy.Emission</code> once a the simulator has finished …

Adds support for browsing storybooks from the app

---

Example/Emission.xcodeproj/project.pbxproj
Example/Emission/Emission-Bridging-Header.h
Example/Emission/UnusedSwiftFile.swift

It looks like using Swift requires a few more xcproj changes, so I let Xcode do it instead and added an empty file.
#trivial<hr data-danger="yep"/>
<details>
<p>&nbsp;</p>
<pre><code>git fetch origin pull/572/head:orta-572-checkout
git checkout orta-572-checkout
yarn install
</p>
<p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the phone to get the Admin menu.</p>
<p>If you see <i>"Use Staging React Env" </i> - click that and restart, then follow the next step.</p>
<p>Click on <i>"Choose an …

Add an unused Swift file to ensure the app is usable in release with a Swift library

---

Example/Emission.xcodeproj/project.pbxproj

I've been keeping longer term notes in https://github.com/artsy/emission-nebula/issues/3
This stops the CocoaPods warning:
#trivial<hr data-danger="yep"/>
<details>
<p>&nbsp;</p>
<pre><code>git fetch origin pull/573/head:orta-573-checkout
git checkout orta-573-checkout
yarn install
</p>
<p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the phone to get the Admin menu.</p>
<p>If you see <i>"Use Staging React Env" </i> - click that and restart, then follow the next step.</p>
<p>Click on …

Undoes the work in #571 to allow CocoaPods to set the BED_SWIFT_STANDARD_LIBRARIES

---

.gitignore
.travis.yml
package.json
scripts/deploy_commit.sh

Bundles the JS from head of every PR and places it into an S3 bucket with the name `[PR_ID].js`. Meaning that we can make assumptions from inside Emission about the JS existing. Ergo: we can have testflight Emission testing PRs.
New commits on the same PR will overwrite the JS.

[Dev] Deploy the head commit for a PR to our S3 bucket

---

CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
Example/Emission/ARDefaults.h
Example/Emission/ARDefaults.m
Example/Emission/ARRootViewController+AppHub.m
Example/Emission/ARRootViewController+PRs.h
Example/Emission/ARRootViewController+PRs.m
Example/Emission/ARRootViewController.m
Example/Emission/AppDelegate.h
Example/Emission/AppDelegate.m
Example/Emission/AuthenticationManager.m
Example/Emission/EigenLikeAdminViewController.m
Example/Emission/EmissionPRChooseViewController.h
Example/Emission/EmissionPRChooseViewController.m
Example/Emission/LoadingSpinner.h
Example/Emission/LoadingSpinner.m
Example/Emission/PRNetworkModel.h
Example/Emission/PRNetworkModel.m

Allows anyone using the app to pick any current PR, assuming it has passed CI enough to upload the JS from #588 
Here's the flow:
The app normally looks like this
You want to look at the JS for a PR, so you click "Use a PR of Emission":
The grey'd out ones are unavailable to use because the JS isn't there, shouldn't be many in the future - but if we ship failing typescript then it won't bundle.
You pick one:
App restarts, and it shows a spinner while it downloads the JS from S3
This happens every time, so if the PR updates, you just kill the app and load it back up. Now the main menu looks like this:
And in this case, in the storybook browser, you'll get the stories for that PR, in my case that's the "Consignments - bottom aligned".
---
So why the S3 instead of apphub for PRs? 
Mainly, …

[Dev] Allow any PR to be used as a build inside Emission

---

.vscode/extensions.json
src/lib/components/consignments/components/artist-search-results.tsx
src/lib/components/consignments/components/artwork-consignment-todo.tsx
src/lib/components/consignments/components/bottom-aligned-button.tsx

I dunno what best practices are in styled-components yet, but I added an extension that will color the text correctly.
In this PR, I also changed all of the consignments components to use `x-y` instead of `xY` to be consistent with reaction-force, and added a `;` - as that fixes the syntax colouring :)
Before:
After:

[Dev] Adds a recommended styled-components vscode extension - #trivial

---

package.json
yarn.lock

Main update for us is that it adds a status report at the bottom showing whether green or red, but won't fail the build on a dangerfiile fail (the same behaviour as ruby Danger)
#trivial

[Dev] Update danger

---

package.json
src/lib/components/consignments/components/__tests__/__snapshots__/toggle-tests.tsx.svg
src/lib/components/inbox/conversations/__tests__/__snapshots__/zerostate_inbox-tests.tsx.svg
src/lib/components/inbox/conversations/__tests__/zerostate_inbox-tests.tsx
yarn.lock

looks a lot more like 
#trivial
---
You can see all the changes in https://github.com/orta/jest-snapshots-svg/pull/16

Improve SVG renderings

---

CHANGELOG.md
src/lib/components/inbox/conversations/__stories__/artwork_preview.story.tsx
src/lib/components/inbox/conversations/__stories__/conversation-snippet.story.tsx
src/lib/components/inbox/conversations/__stories__/inbox.story.tsx
src/lib/components/inbox/conversations/__stories__/index.ts
src/lib/components/inbox/conversations/__tests__/__snapshots__/artwork_preview-tests.tsx.snap
src/lib/components/inbox/conversations/__tests__/artwork_preview-tests.tsx
src/lib/components/inbox/conversations/__tests__/conversation_snippet-tests.tsx
src/lib/components/inbox/conversations/__tests__/conversations-tests.tsx
src/lib/components/inbox/conversations/artwork_preview.tsx
src/lib/components/inbox/conversations/conversation_snippet.tsx
src/lib/components/inbox/conversations/index.tsx
src/lib/components/inbox/typography/index.tsx
src/lib/containers/__tests__/__snapshots__/conversation-tests.tsx.snap
src/lib/containers/__tests__/conversation-tests.tsx
src/lib/containers/__tests__/inbox-tests.tsx
src/lib/containers/conversation.tsx

[MSG] Added ArtworkPreview to Conversation

---

.gitignore
CHANGELOG.md
Example/Podfile.lock
data/schema.graphql
data/schema.json
package.json
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/Previews/ArtworkPreview.tsx
src/lib/Components/Inbox/Conversations/Previews/ImagePreview.tsx
src/lib/Components/Inbox/Conversations/__stories__/ArtworkPreview.story.tsx
src/lib/Components/Inbox/Conversations/__tests__/ArtworkPreview-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/Message-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Components/OpaqueImageView.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/Conversation-tests.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap
src/lib/relay/config.tsx
src/lib/relay/routes.tsx

This uses the updated schema from https://github.com/artsy/metaphysics/pull/680
It doesn't have the real Relay fragment yet...but the existing stuff does work (`raw_text` instead of `snippet`), and we now have `is_from_user` coming back from Metaphysics. I need to go back and do that in a more 'proper' way, but that should be transparent to Emission anyway.

@sarahscott => [Messaging] WIP on updating messages connection/fragment

---

dangerfile.ts

Danger is failing on files we don't have tests for and decided to skip on because the capitalization has changed. This fixes that.

[Dev] Updates the Dangerfile to handle different cases of files

---

CHANGELOG.md
src/lib/Containers/Conversation.tsx

Related to #645.
It’s not the final solution yet, but good enough for first beta.

[Messaging] Force fetch messages when loading the conversation view.

---

CHANGELOG.md
Example/Emission/Info.plist
Pod/Classes/ViewControllers/ARInquiryComponentViewController.m
src/lib/Containers/Inquiry.tsx

Fix for #667 
It works well on the Emission app on phone, I can't test it within Eigen. I think it will keep the black statusbar at top, but that would be fine I think :).

[MSG] Take out statusbar from inquiry modal

---

CHANGELOG.md
src/lib/components/artwork_grids/__tests__/__snapshots__/artwork-tests.tsx.snap
src/lib/components/artwork_grids/__tests__/artwork-tests.tsx
src/lib/components/artwork_grids/artwork.tsx

This PR changes Emission to no longer show opening/current bid price when the sale associated with the artwork has closed. This also modifies existing test coverage to explicitly state the existing tests were for open sales, and changes the stub `sale_message` to "Contact Gallery", to help avoid confusion around snapshot data and test names (i.e.: avoid the test named "doesn't show price info" having "$875" located _anywhere_ in the snapshot).
Initially this fix was done in [metaphysics](https://github.com/artsy/metaphysics/pull/689) but that proved problematic, as both force and parts of Emission rely on the `is_in_auction` flag remaining `true` even if the auction has closed. So we need to be a little more clever.
This fix is high priority for the auctions team; this PR is into a new …

Fixes display of auction price info

---

CHANGELOG.md
Example/Emission/main.m

It would fail due to the unused `testBundlePath` variable after stripping all assertions.

[Example] Fix archive build.

---

CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
Example/Podfile.lock
src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/ArtworkPreview-tests.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/ArtworkPreview-tests.tsx.snap

A cautionary tale.
This is a fix for artworks without dates - `this.props.artwork.date` was an empty string in this case instead of a `null`, resulting in this bug:

[MSG] Fix for silly bug in ArtworkPreview #trivial

---

Makefile
README.md

I had to re-install my repo from scratch after getting #632 merged, due to caps issues (that PR predated the first major capitalisation changes) 
Setting up the project takes a bunch of commands, and every time I blow the repo, I forget the commit hooks. So I've automated that away. Opted for `make oss` as that's consistent with other Artsy mobile projects.

Add an automated setup script

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/Artwork.tsx
src/lib/Components/ArtworkGrids/__tests__/__snapshots__/Artwork-tests.tsx.snap
yarn.lock

This is work for https://github.com/artsy/auctions/issues/531 and the Emission equivalent of Eigen's https://github.com/artsy/eigen/pull/2402
Not sure about the yarn.lock file changes – please take a look.

Changes post-sale artwork supplementary info

---

CHANGELOG.md
data/schema.graphql
data/schema.json
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/__tests__/Message-tests.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/Conversation-tests.tsx

Already looking better re: forwards/signatures!

@joeyAghion => Switch to use body instead of raw_text to render messages

---

CHANGELOG.md
src/lib/Components/Consignments/Components/DoneButton.tsx
src/lib/Components/Consignments/Components/TextArea.tsx
src/lib/Components/Consignments/Components/__tests__/TextArea-tests.tsx
src/lib/Components/Consignments/Components/__tests__/__snapshots__/TextArea-tests.tsx.snap
src/lib/Components/Consignments/Screens/Artist.tsx
src/lib/Components/Consignments/Screens/Overview.tsx
src/lib/Components/Consignments/Screens/Provenance.tsx
src/lib/Components/Consignments/Screens/__tests__/Provenance-tests.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Provenance-tests.tsx.snap
src/lib/Components/Consignments/__stories__/Consignments.story.tsx

There is one problem with this PR but it may be something with React Native we need to fix. The placeholder text is limited to one line:
When inspected in Reveal, placeholders are implemented internally to RN as a `UILabel` but the multiline property of the text input isn't passed through. 
Not sure if that's a blocker for this PR; I'm keen to hear next steps.

Adds Provenance for Consignments flow

---

src/setupJest.ts

I finally get some peace and quiet in the test runner
Most of these errors are fixed in the latest version of RN - so we can delete this on the next update.

Remove annoying logs around proptypes and createClass from RN codebase

---

CHANGELOG.md
Example/Emission/AppDelegate.m
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m
dangerfile.ts
src/lib/relay/config.tsx

Switches out the old init functions, and replaces it with a compulsory `AREmissionConfiguration`. 
Converts the URLs for grav/metaphysics to be DI'd in too.
This will need the same changes in Eigen on the next deploy. Should just be a matter of consolidating the existing env vars into the object.

Convert AREmission to be created with an AREmissionConfiguration, and add googleMapsAPIKey

---

src/lib/Components/OpaqueImageView.tsx

This PR resolves a minor storybook bug in displaying a single/multi-item article.
In OpaqueImageView the placeholder background color is processed with processColor if needed, but passed into props as a regular hex color string if not. This causes an error in the storybook.

remove default placeholderBackgroundColor string from props

---

dangerfile.ts
package.json

Moves the dangerfile to be only Emission specific things right now. Yarn + Spellcheck are coming from peril.

Remove the yarn plugin from dangerfile as peril will handle this

---

.travis.yml
scripts/deploy_apphub.sh

AppHub hasn't worked in months, so I've moved CI to do it as a part of the normal CI run - rather as a separate job.

Try deploying inside travis run instead of in the deployment section

---

CHANGELOG.md
Example/Emission/ARRootViewController+AppHub.m
Example/Emission/ARRootViewController.m
Example/Emission/AppDelegate.m
Example/Emission/EigenLikeAdminViewController.m
src/lib/Components/Inbox/Conversations/__tests__/Conversations-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Containers/Conversation.tsx

We have betas being released *mostly* automatically now (sometimes Xcode fails, so it needs too be re-built). Both in terms of the native code via TestFlight, and master JS commits via AppHub as of last Friday.
So, I downloaded a copy and played around with it. I think it's in a pretty reasonable state but it uses a lot of dev terminology which could be simplified.
So here's what a beta version looks like now:
If you wanted to choose a PR build:
(the tick indicates that it's definitely available to use)
Then you end up with a much simpler UI:
This is because there's no guarantee that any of the other things will work. You get access to the storybooks and you're good to go. Reverting from the PR build brings you back to a similar main menu.
---
I also removed the additional view …

[Dev/Admin] Update the admin/beta/dev UI

---

package.json
src/lib/Components/Consignments/Components/__tests__/__snapshots__/Toggle-tests.tsx-looks-good-as-an-svg.svg
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx-shows-3-sets-of-questions-when-there's-no-edition-info.svg
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx-shows-and-additional-2-inputs-when-there's-edition-info.svg
yarn.lock

Updates the SVG renderer.
In looking at the lockfile: I feel like `esdoc` was removed from a dependency (might have been a one of my danger plugins,  I remember doing something like this) and then this wasn't `yarn remove`'d - resulting in the new lockfile.

[dev] Update Jest SVG renderer #trivial

---

.travis.yml
scripts/deploy_apphub.sh
scripts/deploy_commit.sh

Separates the Danger/Build/Lint runs from the deployment runs. I think they're also running when they shouldn't - so I took another stab at making them only run at the right place
#trivial

[Dev] Separate deploy runs from CI runs

---

Example/Emission/AppDelegate.h
Example/Emission/AppDelegate.m
Example/Emission/UnroutedViewController.m
Pod/Classes/Core/AREmission.h
Pod/Classes/Core/AREmission.m

Adds support for showing pages in a WKWedbView - there's a slack discussion about _why_ artsy is slow [here](https://artsy.slack.com/archives/C02BAQ5K7/p1504886479000256) - same problem we see in Eigen, and this is a fresh implementation.
Only notable other change is that the config is now a readable property on AREmission externally. It's read-only, so that's fine by me.

[Beta] Unrouted pages now go through to force

---

CHANGELOG.md
Pod/Classes/DottedLineComponent/ARDottedLineManager.h
Pod/Classes/DottedLineComponent/ARDottedLineManager.m
src/lib/Components/DottedLine.tsx
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/__stories__/DottedLine.story.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap
storybook/storyLoader.js

tracked in #677 
This PR was previously #729 from my fork erikdstock/emission
Skip New Tests
It adds a styed dotted line component to be used as a separator between ConversationSnippets:

Dotted line component

---

CHANGELOG.md
data/schema.graphql
data/schema.json
package.json
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/__tests__/Message-tests.tsx
src/lib/Containers/Conversation.tsx

This is 'blind' as it uses all the in-progress PR's, but the end result is that everything renders the same (:+1:) as it should, due to all the fallbacks 😅 
This renders the conversation's `initial_message`, which is _just_ the user-submitted content, for the first message in a thread. That first message is 'special' in that we're already rendering it differently- including previews of the conversation item in question.
For the other messages, they are just rendering `body`, which has been updated in https://github.com/artsy/metaphysics/pull/733 to use the user-submitted text where possible.
Pretty simple!
This will fix our issues around sanitizing our own messages (like invoice requests, the initial messages, etc.), which basically completes the 'message sanitization' showstopper- those …

@ashkan18 => [Messaging] Better rendering of message text

---

src/lib/Containers/Conversation.tsx

I noticed after pulling master, the mutation to mark a message as unread wasn't working, even the `id` existed in `RelayProps`, it wasn't in the container fragment. This just adds it to the fragment, which gets that all working again
trivial
Skip New Tests

@l2succes => Include id in conversation fragment

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/__tests__/Message-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/Messages-tests.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap
src/lib/Components/Inbox/Typography/index.tsx
src/lib/Containers/Conversation.tsx
src/lib/Containers/__tests__/__snapshots__/Conversation-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap

Closes: https://github.com/artsy/emission/issues/753
Misc UI fixes:
- It fixes the UI layout of `ConversationSnippet` component as the rows are off by a few pixels
Before:
After:
- It also fixes the separator styling in the message component, we were missing the padding around it and the last row should not have a separator under it.
- It also moves the loading indicator inside of the messages list view so that it doesn't always appear if the user is scrolling slower than the time needed to load the next page.
It also includes a re-bind of the `space` key in Emission. As of now, we aren't able to hit space as it's used as a toggle for hiding/showing the black back button in the simulator. After this PR, the binding will `ctrl+space` and `space` will return to its default binding.
This …

[Messages] Misc UI fixes and space key remapping

---

package.json
yarn.lock

Release notes [here](https://github.com/NYTimes/react-tracking/releases/tag/v5.0.0)
Basically: it adds the use of `state` within the track decorators 🎉

[Dependencies] Updated react tracking to 5.0.0

---

CHANGELOG.md
src/lib/Containers/Inquiry.tsx
src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap

The response rate was hardcoded and isn't available in metaphysics (from my search). As requested during planning meetings, we'll remove it now and add this information in the next phase.
Instead of completely ripping it out (it causes alignment issues with the cancel button), I've cheekily made it an empty string...

[Inquiry] Hide partner response rate for now

---

.gitignore
CHANGELOG.md
Example/Emission/AppSetup.m
Example/Emission/index.ios.js
package.json
src/lib/Components/Artist/__stories__/ArtistArticles.story.tsx
src/lib/Components/Inbox/Conversations/__stories__/ArtworkPreview.story.tsx
src/lib/Containers/__stories__/Gene.story.tsx
src/lib/Containers/__stories__/Inquiry.story.tsx
src/lib/Containers/__stories__/MyAccount.story.tsx
src/lib/utils/track.ts
webpack.haul.js
yarn.lock

* https://github.com/callstack/haul
* Looks like we’ll loose a little packaging performance, but not too much and probably does not outweigh the amount of time we spent during upgrades to get our setup to work http://blog.nparashuram.com/2017/04/react-native-packager-vs-haul.html#results
* TODO We need to make automatically launching a custom debugger (React Native Debugger.app) work, someone should PR that to the Haul repo.
Skip New Tests

[packager] Fix release builds by switching from Metro to Haul.

---

package.json
src/lib/Components/Consignments/Submission/geminiUploadToS3.ts
src/lib/Components/Consignments/Submission/uploadPhotoToGemini.ts

Introduced in #787 
I've fixed this happening again by adding `yarn relay` to the CI build.
#trivial

Fix relay compilation errors on master

---

.travis.yml
scripts/deploy_master.sh

Re: #803 
It's  _real_ hard to work without some real metadata, so this is just the S3 uploading part of #803 - so that it can go through the full lifecycle ( check it out in travis on build 8.4.0 on the master build once this is merged)

Just add the deploy master metadata

---

Example/Emission/ARRootViewController.m
Example/Emission/AppSetup.m
Example/Emission/CommitNetworkModel.h
Example/Emission/CommitNetworkModel.m

Looking pretty good 
Looks like I forgot that obj-c is not JavaScript and that we can't just provide interfaces to NSDictionaries and everything'll be fine. So this adds some model parsing, and I verified a bunch of the work in #803 now that I have proper metadata.

Deploy work polish

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/index.tsx

This might be the crash we've intermittently been seeing in Emission.
I came across it during the analytics work, I inquired a few times in a row, and I feel like one got sent out with an empty message body / not fully loaded message. This shouldn't at all be an issue, I just remember the inquiry screen flashing up. I could not reproduce what it is that I had submitted. 
But it ended up meaning that on Matt's test account there's this one corrupted message (lack of better explanation), that ends up in this error:
And I put a quick guard up (see code changes from this PR).
Given that Emission now loads the latest in master, I noticed that it was crashing when logging in with the test account and opening the Inbox, but if you check out the analytics PR for example (where the crash fix lived …

[Crash] Fix case where node can be null and accessing last_message results in crash

---

Makefile
README.md

When I looked at:
> Ensure that the React version required by Emission has been published to [our spec-repo][spec-repo].
In the README, I wasn't really sure where to start with that, so I figured it out and automated it 👍

Adds a makefile command for updating the RN specs

---

CHANGELOG.md
src/lib/Containers/Inbox.tsx

**The error message caused by `this.props.me.conversations_existence_check` being `null`:**
**After the null check:**

[Crash] guard against conversations_existence_check being null

---

CHANGELOG.md
src/lib/Scenes/Home/index.tsx

Weird spaces to the rescue!
Fixes #[CE650](https://github.com/artsy/collector-experience/issues/650)
Previous context to this issue [in this PR](https://github.com/artsy/emission/pull/826), including some images that measure the offset/glitch etc. 
So, when you increase letterspacing, this little gap / added spacing at the end of your text component grows also. This makes it seem off centre, but apparently is [expected behaviour](https://stackoverflow.com/questions/23044432/css-negate-additional-space-added-to-last-letter-by-letter-spacing-property). 
Ideally you would be able to indent text through styling, and this would be applied appropriately at the start of a new paragraph. Alas, this is not available in styling of RN. It seems [possible within Core …

[Home] Fix/hack tab labels to be centered

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Inbox-tests.tsx.snap

Fixes #[CE640](https://github.com/artsy/collector-experience/issues/640)
- max width for iPad + centered content
- replace dotted line with solid line (😥)
Also replaced colors and fonts with enums for `ConversationSnippet`. Will do this as I touch old files. 
iPhone:
iPad (pro), P/L :

[QA] Inbox for iPad

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Composer.tsx
src/lib/Components/Inbox/Conversations/Message.tsx
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Composer-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Messages-tests.tsx.snap

Fixes https://github.com/artsy/collector-experience/issues/639
iPhone has stayed the same:
iPad Portrait:
iPad Landscape:
FYI:
The no-connection banner has also been shrunk to 708 max width:
(please ignore the attachments being so wide, I took this screencap before I had fixed that)

[QA] Update composer/message thread screen for iPad

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
src/lib/Components/Inbox/Conversations/Preview/Attachment/PDFPreview.tsx
src/lib/Components/Inbox/Conversations/Preview/Attachment/__tests__/__snapshots__/PDFPreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/Preview/InvoicePreview.tsx
src/lib/Components/Inbox/Conversations/Preview/ShowPreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/ArtworkPreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/InvoicePreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/ShowPreview-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap

Fixes most of https://github.com/artsy/collector-experience/issues/636
So... in code, the border is `1px` everywhere. On the simulator, I'm getting the extra pixel on the top line (see screenshots below), on device it's indeed the right border. It seems like a drawing glitch or something, but there isn't much in straight up CSS that I can do. We can create a separate ticket to investigate further? 
Show attachment margins:
Artwork attachment margins:
Invoice attachment margins:
Short artwork title:
Long artwork title:
(please note, the truncation has slightly changed. Sorry @katarinabatina this was the only way I could make it work..)

[QA] Message attachments

---

CHANGELOG.md
src/lib/Components/Home/ArtistRails/ArtistRail.tsx
src/lib/Components/Home/SectionTitle.tsx
src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarouselHeader.tsx
src/lib/Scenes/Home/Components/ForYou/Components/__tests__/__snapshots__/FairsRail-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/index.tsx
src/lib/Scenes/Home/Components/SectionTitle.tsx

Fixes https://github.com/artsy/collector-experience/issues/662
Afterzzz:
Snuck in this little thing that was bugging me ^^^^^^^ View all had an additional space, causing it to _just_ not be aligned with the top bit. (Unless this was intentional? though it didn't seem like it from the design specs in the issue) cc @katarinabatina 
To specify: I moved it left, so it aligns with the headers. The little thingy in sketch was me checking whether it was misaligned or just my imagination 😄.
Skip New Tests

[Home] QA on header text sizes and spacing

---

CHANGELOG.md
Example/Podfile.lock
Pod/Classes/ViewControllers/ARGeneComponentViewController.m
package.json
src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
src/lib/Containers/Gene.tsx
src/lib/NativeModules/SwitchBoard.tsx
yarn.lock

* I’ve removed cases where `setState` is being used in a promise and we subsequently catch all errors that can come out of the promise, which can apparently [leave React in a bad state](https://github.com/facebook/react/issues/8579#issuecomment-267312367). Going forward we should either just `console.error(…)` them so they show up in Sentry or be selective about which errors we catch and rethrow all others.
* The Sentry version we were using [has a bug](https://github.com/getsentry/sentry-cocoa/pull/192). To be able to update Sentry in Eigen we need to also update the RN client.
* The Gene container was crashing when it was initialised without filter defaults, which would happen when Eigen’s switchboard would route a Gene URL that did not contain any of the required filter parameters.
- …

More crash related fixes

---

src/lib/Components/ArtworkGrids/Artwork.tsx

https://sentry.io/artsynet/eigen-staging/issues/274707594
I have no clue how it could get here after all these `if` statements, but this is the only place I could find that accesses `bidder_positions_count`. Hopefully this log will give us some data we can use to reproduce the issue.

[Artwork] Try to pinpoint sale artwork related crash. #trivial

---

CHANGELOG.md
src/lib/Components/Consignments/Components/TextInput.tsx
src/lib/Components/Consignments/Components/Toggle.tsx
src/lib/Components/Consignments/Components/__tests__/__snapshots__/BottomAlignedButton-tests.tsx.snap
src/lib/Components/Consignments/Components/__tests__/__snapshots__/SearchResults-tests.tsx.snap
src/lib/Components/Consignments/Components/__tests__/__snapshots__/TextInput-tests.tsx.snap
src/lib/Components/Consignments/Components/__tests__/__snapshots__/Toggle-tests.tsx.snap
src/lib/Components/Consignments/Screens/Metadata.tsx
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/FinalSubmissionQuestions-tests.tsx.snap
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Location-tests.tsx.snap
src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Metadata-tests.tsx.snap

fixes https://github.com/artsy/emission/issues/850 and https://github.com/artsy/consignments/issues/97
Done:
- return key is now 'next'
- move order of fields so 'category' is last
- toggle now stays black
- done button doesn't float
- placeholders light up on focus (and dim _on blur_)
- updated some margins around the picker

[Consignments] Metadata screen QA

---

src/lib/Components/Inbox/ActiveBids/ActiveBid.tsx
src/lib/Components/Inbox/ActiveBids/__stories__/ActiveBids.story.tsx
src/lib/Components/Inbox/ActiveBids/__tests__/ActiveBid-tests.tsx
src/lib/Components/Inbox/ActiveBids/index.tsx
src/lib/Containers/Inbox.tsx
src/lib/Containers/__tests__/Inbox-tests.tsx
storybook/storyLoader.js

Fixes https://github.com/artsy/emission/issues/864
Fixes https://github.com/artsy/collector-experience/issues/658
Skip New Tests
#trivial
We needed to update the query to reflect more accurate data: 
```
most_recent_bid {
__id
}
```
Also added a storybook entry under `Inbox/ActiveBids`.

[Inbox => Bugfix] Active Bids component retrieving incorrect data

---

CHANGELOG.md
Example/Emission/AppDelegate.m
Pod/Classes/Core/ARSwitchBoardModule.h
Pod/Classes/Core/ARSwitchBoardModule.m
src/lib/Components/ArtworkGrids/Artwork.tsx
src/lib/Components/ArtworkGrids/GenericGrid.tsx
src/lib/Components/ArtworkGrids/InfiniteScrollGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/ArtistForSaleArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/ArtistNotForSaleArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/GeneArtworksGrid.tsx
src/lib/Components/ArtworkGrids/RelayConnections/SaleArtworksGrid.tsx
src/lib/Components/ArtworkGrids/__tests__/Artwork-tests.tsx
src/lib/NativeModules/SwitchBoard.tsx
storybook/storyLoader.js

In Eigen the ArtworkVC is a special case against routed VC in two ways:
1. It can be wrapped in a Fair
2. It can accept multiple artworks and paginate between them
In moving to Emission, we lost the ability to do number 2. This brings it back. This adds a new API to the Emission switchboard for routing artworks specifically when you click one within a set like via `GenericGrid` or `InfiniteScrollGrid`. 
This will need work in Eigen when Emission is updated, but it'll be a trivial one liner. Just pass these options to [this function](https://github.com/artsy/eigen/blob/master/Artsy/App/ARSwitchBoard+Eigen.h#L37).
I swear I made an issue for this, but I can't find it anymore. Been annoying me for years :P
Skip New Tests

[Polish] Adds support for sending Artwork sets through to Eigen

---

CHANGELOG.md
src/lib/Components/Inbox/ActiveBids/index.tsx
src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Containers/Inbox.tsx
yarn.lock

Before, when the `Inbox` tried to force fetch its child `Conversations` container, we got an error related to pagination because `Conversations` is a `PaginationContainer` and [maintains its own cursor](https://github.com/artsy/emission/blob/master/src/lib/Components/Inbox/Conversations/index.tsx#L125).
I got around this by making `refreshConversations` and `refreshActiveBids` methods that the `Inbox` can call upon pull-to-refresh. The `ActiveBids` container is now a `RefetchContainer` and can be updated with a normal force fetch.
Skip New Tests

[inbox] fix for inbox pull-to-refresh

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARWorksForYouComponentViewController.m
src/lib/Containers/WorksForYou.tsx
src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap

Turns out the `onEndReached` detection was set on the wrong view.
Part of https://github.com/artsy/collector-experience/issues/698

[WFU] Only load 1 page at a time.

---

CHANGELOG.md
src/lib/Components/OpaqueImageView.tsx
src/lib/Scenes/Home/Components/Sales/Components/SaleListItem.tsx
src/lib/Scenes/Home/Components/Sales/Components/__tests__/SaleListItem-tests.tsx
src/lib/Scenes/Home/Components/Sales/Components/__tests__/__snapshots__/SaleListItem-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/__tests__/index-tests.tsx

A flag called `skipGemini` was [added to the image component](https://github.com/artsy/emission/pull/630), which was seemingly only done to work around a problem with [Gemini not being able to read images from `https` sources](https://artsy.slack.com/archives/C04DU9H0L/p1498517025120402). However, the issue was [apparently](https://artsy.slack.com/archives/C0GNAB0US/p1498763267827192) resolved with [this PR](https://github.com/artsy/gemini/pull/242).
The flag was never removed and got used in new auction related code https://github.com/artsy/emission/commit/5dde988d4af49dc8e150e845c3aac8779a5a8407#diff-741b505d177ba9a6e497cd077987ab45R47
Skip New Tests

[ImageView] Get rid of `skipGemini` flag

---

CHANGELOG.md
src/lib/Components/Home/ArtistRails/ArtistRail.tsx

I couldn't reproduce this issue but I added this little check anyway to make sure it probably can't happen.
Fixes https://github.com/artsy/collector-experience/issues/766 (sort of)
Skip New Tests

[home] do not render artist rail if it does not have artists

---

src/lib/Components/Consignments/Screens/Overview.tsx

Resolves: https://sentry.io/artsynet/eigen-staging/issues/413385206/
This was due to our nil checking not being enforced in Emission as `toUpload` could be an falsey value.
#trivial

Adds nil protection to a check for the length of images to upload to s3

---

src/lib/Components/Inbox/Conversations/index.tsx
src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarouselHeader.tsx

A little cleanup from https://github.com/artsy/emission/pull/874
Danger: 
trivial 
Skip New Tests

[Cleanup] Add error logs and remove comment #trivial 

---

CHANGELOG.md
src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx

Verifies the photo is data we expect, then adds it at the beginning and adds the photos uri to the selected objects.

[Consignments] Pre-fixes and select the newly taken camera image to the photo selector

---

CHANGELOG.md
src/lib/Containers/Gene.tsx

I think a React Native update meant that a value being `undefined` instead of being sent as `null` does not get passed to the native code at all. This means that checks in Eigen that the data is correct would fail. So now if we have undefined, we send the default values.

[Gene] Pass defaults for medium/price to native refine hook

---

Emission.podspec
dangerfile.ts
package.json
scripts/deploy_master.sh

Adds a native code versioning system, so that we can know when we've broken native compatibility with the JS. Right now this is passed through both the Podspec and via the [master JSON file](https://s3.amazonaws.com/artsy-emission-js/master-metadata.json) 
Also fixes https://github.com/artsy/emission/issues/869 - given that no-one responded I figured it was time to migrate them to be consistent.

Adds support for a native code versioning system

---

src/lib/utils/errors.tsx
src/lib/utils/renderWithLoadProgress.tsx

Adds a `console.error` to a failing Relay query. 
This will show a red screen in dev mode when a Relay query totally fails ( e.g. not status 200 ) which happens when you make a bad request e.g.  `{"errors":[{"message":"Cannot query field \"__id\" on type \"FilterArtworks\"."}]}`
You can't rely on [this code](https://github.com/artsy/emission/blob/master/src/lib/metaphysics.ts#L20-L30) because by this point Relay has caught the error and has asked you to re-render.
#trivial #skip_new_tests

Improve network error reporting in Emission

---

CHANGELOG.md
src/lib/Components/Consignments/Screens/Edition.tsx
src/lib/Components/Consignments/index.tsx

Fixes #https://github.com/artsy/collector-experience/issues/785
Skip New Tests

[consignments] edition number field is now a string

---

src/lib/Scenes/Home/Components/Sales/__tests__/index-tests.tsx
src/lib/Scenes/Home/Components/Sales/index.tsx

This concludes https://github.com/artsy/collector-experience/issues/703. While the ZeroState component existed, it wasn’t actually being shown yet.
#trivial

[Home/Auctions] Show the ZeroState component when there are no sales.

---

CHANGELOG.md
data/schema.graphql
data/schema.json
package.json
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/UpdateConversation.ts
src/lib/Components/Inbox/Conversations/__stories__/ConversationSnippet.story.tsx
src/lib/Components/Inbox/Conversations/__tests__/ConversationSnippet-tests.tsx
src/lib/Containers/Conversation.tsx
src/lib/relay/config.tsx

And also to mark a message as being viewed.
This uses the branch in https://github.com/artsy/metaphysics/pull/873 , all the Impulse stuff is already on staging.
Tangentially, that Metaphysics PR also offers the `total_unread_count`, which precipitated this refactor.

@l2succes => Switch to use new unread methodology for the indicator

---

CHANGELOG.md
Pod/Classes/EigenCommunications/ARNotificationsManager.m

Fixes https://github.com/artsy/collector-experience/issues/782
An `NSURL` object looks like a string when you inspect it, which is why I didn’t notice this sooner (and notification info objects are not strictly typed) and the JS bridge would just serialise it to an empty JS object.
Now we convert it to a string before passing it to the JS bridge.

[Invoice] Convert NSURL to NSString before passing over JS bridge.

---

CHANGELOG.md
src/lib/Containers/WorksForYou.tsx
src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/__tests__/index-tests.tsx
src/lib/Scenes/Home/Components/Sales/index.tsx

Related to https://github.com/artsy/collector-experience/issues/855
This only adds pull-to-refresh to these views, rather than a more comprehensive data invalidation scheme, but that can probably wait till post v4.0.0.

Add pull to refresh to artists and auctions

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
src/lib/Components/Inbox/Conversations/Preview/__tests__/ArtworkPreview-tests.tsx

Fixes https://github.com/artsy/collector-experience/issues/875

[Inquiry] Don’t crash when tapping artwork component.

---

src/lib/Components/Buttons/Button.tsx

Fixes https://github.com/artsy/collector-experience/issues/849
This button relies on the presence of an `onPress` prop to be enabled/disabled; before, this check only happened in the constructor. Now it should check to see if its status has changed in `componentDidUpdate`.
This shows the button being enabled and then disabled based on consignments information (ignore animation warnings):

Make sure buttons update when their enablement has changed #trivial

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/InfiniteScrollGrid.tsx

Fix a bug where infinite scroll doesn't know how to stop unless you use a finished callback

---

src/lib/AppRegistry.tsx
src/lib/Components/Gene/Header.tsx
src/lib/Components/Home/ArtistRails/ArtistRail.tsx
src/lib/Containers/Gene.tsx
src/lib/Scenes/Favorites/__stories__/Favorites.story.tsx
src/lib/Scenes/Favorites/index.tsx
src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarouselHeader.tsx
src/lib/utils/track.ts

Fix https://github.com/artsy/collector-experience/issues/885
Tracks:
- Tab switches in Saves and Follows
- Follow of artist on artist rail in Home
- Follow of suggested artworks by an artist in Home
- Gene screen view
- Gene refine tap
- Gene tab switching (between works and about)
- Gene follow / unfollow
✨ 
I think that's all folks!

[Analytics] For home, saves and follows, and gene events

---

CHANGELOG.md
src/lib/Components/Consignments/Screens/Metadata.tsx
src/lib/Components/Consignments/Screens/__tests__/Metadata-tests.tsx

Fixes https://github.com/artsy/collector-experience/issues/894
When you start selecting the categories, painting is now set in the state without you doing anything as the onselect trigger on happens when you change selection.

[Consignments] Sets the default option when you first select a category

---

CHANGELOG.md
src/lib/Components/Consignments/Components/ArtworkConsignmentTodo.tsx
src/lib/Components/Consignments/Screens/Overview.tsx

Wraps up https://github.com/artsy/collector-experience/issues/895
Height and width were the only two ones we were still missing :)
We now check for:
```
this.state.artist &&
this.state.location &&
this.state.metadata &&
this.state.metadata.category &&
this.state.metadata.title &&
this.state.metadata.year &&
this.state.metadata.medium &&
this.state.metadata.height &&
this.state.metadata.width &&
this.state.editionScreenViewed
```
As per:

[Consignments] Add height and width as requirements for submission to match force

---

CHANGELOG.md
data/schema.graphql
data/schema.json
src/lib/Scenes/Home/Components/Sales/Components/LotsByFollowedArtists.tsx
src/lib/Scenes/Home/Components/Sales/Components/__tests__/LotsByFollowedArtists-tests.tsx
src/lib/Scenes/Home/Components/Sales/__tests__/__snapshots__/index-tests.tsx.snap
src/lib/Scenes/Home/Components/Sales/__tests__/index-tests.tsx

Fixes https://github.com/artsy/collector-experience/issues/904
Initially we were checking for `is_biddable` in returning sale works by followed artists but this only applied to lots that were _immediately_ biddable. What we should be checking is whether a sale `is_open`.

[Home/Auction] Update LotsByFollowedArtist filter logic 

---

CHANGELOG.md
src/lib/Scenes/Home/index.tsx

Fix https://github.com/artsy/collector-experience/issues/909
Issue was that when setting state, I was also calling analytics (and incorrectly setting the state of the tab). Actually, the `if` statement above takes care of it. If it goes to the Artists WFY page, then from that state change the analytics will fire anyway. No need to keep it in the `setState` below.

[Analytics] Get rid of double fire upon entering background state

---

src/lib/Scenes/Home/Components/Sales/index.tsx

Sorts Auction list by `TIMELY_AT_NAME_ASC` rather than `TIMELY_AT_NAME_DESC`:
Danger: #trivial

[Bugfix] Swap Home/Auctions sort order #trivial

---

CHANGELOG.md

Changed my mind about not allowing a changelog entry for https://github.com/artsy/emission/pull/952

Update the changelog for post-1.4.0

---

CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
Example/Emission/ARTopMenuViewController.h
Example/Emission/ARTopMenuViewController.m
Example/Emission/AppDelegate.m
Example/Emission/EigenLikeNavigationController.m
src/lib/Scenes/Home/index.tsx

Now the status bar is provided at the root level of the VC hierarchy, so individual screens shouldn't have to care about it at all.
Previous to this PR, there wouldn't be that white bar.

Emulate how eigen handles status bars

---

CHANGELOG.md
src/lib/Containers/Artist.tsx
src/lib/Containers/Gene.tsx
src/lib/Containers/__tests__/Artist-tests.tsx
src/lib/utils/track.ts

It’s not clear why `this.selectedTabTitle().toLowerCase` was causing crashes,
but in case it was related to `componentDidUpdate` that is now gone.
https://artsyproduct.atlassian.net/browse/IN-61 #resolve 🤞 

[Artist] Switch legacy analytics tracking to react-tracking.

---

CHANGELOG.md
src/lib/Components/TabBar.tsx

Updates the tab bar to not overflow their contents

---

CHANGELOG.md
data/schema.graphql
data/schema.json
src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
src/lib/Components/Inbox/Conversations/Messages.tsx
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Conversations-tests.tsx.snap
src/lib/Components/Inbox/Conversations/index.tsx

https://artsyproduct.atlassian.net/browse/IN-56 #resolve
We will be filtering for completely blank messages (i.e. no attachments or body) in metaphysics, but in a worst case, they look like this, which is acceptable IMO:

[Messages] Allow blank-body messages, but filter for completely blank messages in fragment

---

CHANGELOG.md
src/lib/Components/Inbox/Conversations/Messages.tsx

Related to https://artsyproduct.atlassian.net/browse/IN-56

[msg] Do not render messages without bodies or attachments

---

data/schema.graphql
data/schema.json
src/lib/Scenes/Home/Components/Sales/Components/LotsByFollowedArtists.tsx

Seeing unrelated lots in lots by followed artists page.
Follow up on changes in [Gravity](https://github.com/artsy/gravity/pull/11539) and [MP](https://github.com/artsy/metaphysics/pull/923) we need to now set `is_auction` to `true` when asking for lots in live auctions by followed artists.
*Depends on https://github.com/artsy/metaphysics/pull/923*

Add is_auction and set it to true for lots by followed artists

---

Example/Emission/AppDelegate.m

This makes sure Emission's AppDelegate set its user agent.

[dev] Make sure we set a user agent #trivial

---

CHANGELOG.md
Example/Podfile.lock
docs/debugging.md
package.json
src/lib/relay/config.tsx
yarn.lock

This fixes an issue related to the new delta patcher, silences the new but alpha React life-cycle deprecation warnings, and removes the hardcoded polyfill in dev mode to inspect network activity in the debugger in favour of using the ‘Enable Network Inspector’ option in the React Native Debugger app’s contextual menu.

Update to latest React Native patch release

---

Emission.podspec

this is much faster than reaching out to the command line util, which has to spawn a new ruby process for each podspec.
Is has to be verified that this actually works as-is, because in my implementation I had to prefix the podspec files with the root variable (here from `EMISSION_ROOT`), because otherwise it couldn't find the them. But since the ipc method hadn't that either, I kept it without the root prefix for now.

use ruby api to retrieve spec details

---

CHANGELOG.md
Example/Emission/ARRootViewController.m
Example/Podfile.lock
Pod/Classes/ViewControllers/ARBidFlowViewController.h
Pod/Classes/ViewControllers/ARBidFlowViewController.m
src/lib/AppRegistry.tsx
src/lib/Components/Bidding/Screens/BidFlow.tsx
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
storybook/storyLoader.js

This creates an empty bid flow component and exports it as a `UIViewController` subclass for Eigen. Nothing fancy, and we'll probably move to something [like this](https://github.com/artsy/emission/blob/a9e835051d0373c789b0288f1fe45cbb3ee8c985/src/lib/Components/Consignments/index.tsx#L57-L70) in the near future but this is a good starting point.
Once this is merged, we can cut a release of Emission and update Eigen. 
Paired with @sepans on most of this.
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-34 and https://artsyproduct.atlassian.net/browse/PURCHASE-35

Bid flow component

---

CHANGELOG.md
src/lib/Components/Buttons/Button.tsx
src/lib/Components/Buttons/__stories__/Buttons.story.tsx
src/lib/Components/Buttons/__tests__/InvertedButton-tests.tsx
src/lib/Components/Buttons/__tests__/__snapshots__/InvertedButton-tests.tsx.snap
src/lib/Components/Buttons/index.tsx

Right now, the `<Button>` component accepts the `style` prop that allows for styling the button container. But since it is [passed into the `<AnimatedView>` component](https://github.com/artsy/emission/blob/7cfcbd3c6b550925bc59bce75a66d6f2d7c3e76b/src/lib/Components/Buttons/Button.tsx#L154), it actually doesn't allow for styling [the headline in the button](https://github.com/artsy/emission/blob/7cfcbd3c6b550925bc59bce75a66d6f2d7c3e76b/src/lib/Components/Buttons/Button.tsx#L150) (or the styles on the headline are taking the precedence so we cannot override them).
In the new bidding flow, we are going to have to [set the font size of the button to `14`](https://app.zeplin.io/project/5ab94282c124db8d58365b47/screen/5ac66d5c15dd161833080c10) (which is currently [set to …

Add the ability to specifically style the button headline

---

CHANGELOG.md
Example/Podfile.lock
Pod/Classes/Core/AREmissionFontsLoader.m
src/lib/Components/Text/__stories__/Typography.story.tsx
src/lib/data/fonts.ts

Previous PR: https://github.com/artsy/emission/pull/1020
This adds commonly used typefaces in the new bidding flow:
* GaramondBold
* GaramondBoldItalic
* GaramondRegular
* GaramondSemibold
* Unica77LLItalic
* Unica77LLMedium
* Unica77LLMediumItalic
* Unica77LLRegular

Adds commonly used typefaces to storybook

---

CHANGELOG.md
src/lib/Components/Bidding/Components/MaxBidPicker.tsx
src/lib/Components/Bidding/Components/__tests__/MaxBidPicker-tests.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/MaxBidPicker-tests.tsx.snap
src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBid-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/BidFlow-tests.tsx.snap

I noticed that after selecting a new bid increment, that the picker would always snap back. This PR adds state to the `SelectMaxBid` component. I think that it makes sense to put the state here, since we'll need to access it to forward on to the subsequent confirmation screen. But open to suggestions!
This work was done in the course of https://artsyproduct.atlassian.net/browse/PURCHASE-41

Fixes bid picker not staying on selected index

---

README.md

We should point this repo to emission-nebula for the next time someone goes looking for an answer to "how is Emission deployed to TestFlight?"

Adds note about emission-nebula.

---

CHANGELOG.md

The changelog has historically used an H2 for master and H3's for releases. But this convention was broken [in this release](https://github.com/artsy/emission/commit/eaebfb8e9d8066d80993478d487d848e02c1bca2), which our automated deploy script relies on:
https://github.com/artsy/emission-nebula/blob/f8bd8465cd6e2e13038020099119dfaef22c983d/fastlane/Fastfile#L61
This PR does two things:
- Corrects the 1.4.6 header.
- Changes master to use H3 too, so this won't be likely to happen again.
If merged, I'll make a corresponding change in emission-nebula to make sure this still works.

Corrects Changelog header format

---

CHANGELOG.md
Example/Emission/AppDelegate.m
Example/Emission/UnroutedViewController.m
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmFirstTimeBid-tests.tsx.snap

This is one of two required pull requests for conditions of sale. The other is here: https://github.com/artsy/eigen/pull/2599 This is a WIP because we still need to scope the `/conditions-of-sale` route to _only_ condition of sale links from Emission components (we'll add a query string to avoid other links to `/conditions-of-sale` being presenting modally).
Work tracked against [PURCHASE-60](https://artsyproduct.atlassian.net/browse/PURCHASE-60).

Show conditions of sale

---

.gitattributes

#trivial
Noticed these files showing diffs in #1025, so omitting those now too.

[git] Hide query maps from GitHub diffs.

---

CHANGELOG.md
src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarouselHeader.tsx
src/lib/Scenes/Home/Components/ForYou/Components/__tests__/ArtworkCarouselHeader-tests.tsx

EV-117 #merged
Due to some messy parts of our schema around the home page artwork modules and their context, we now have some context types that have the `__id` field for no good reason. However, our current Relay version will query for that regardless, if it exists, and this leads to `followedArtistContext` always being an object, albeit sometimes with nothing more than `{ __id: null }`.
There is no good way to fix this in MP without breaking schema compatibility, this will at least fix the issue going forward.

[Home/ForYou] Fix crash when following artist from ‘related artist’ rail

---

CHANGELOG.md
package.json
src/lib/Components/Bidding/Components/MarkdownRenderer.tsx
src/lib/Components/Bidding/Components/__tests__/MarkdownRenderer-tests.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/MarkdownRenderer-tests.tsx.snap
yarn.lock

Parses and renders markdown to handle markdown messages from [metaphysics](https://github.com/artsy/metaphysics/pull/1031).
Currently only works for **text (paragraphs)** and **links** to avoid over generalization.
Markdown is parsed using [Simple Markdown](https://github.com/Khan/simple-markdown) which allows overriding markdown rendering rules to customize it for emission native components. Also unlike other markdown parsers it can return react object instead of string which is very useful here since react native doesn't have something like `dangerouslySetInnerHTML`.

Simple native markdown renderer

---

Example/Podfile

Because we don't want smart quotes to be too smart and take over the entire earth 😉
Also, `pod install` was suggesting removing it:
#trivial

Replace smart quotes with normal quotes

---

CHANGELOG.md

This PR is step two of [the release process](https://github.com/artsy/emission#deploying-emission), but I'm making a PR because the changes are all mangled (we kept adding to 1.5.0 even after its release, when new entries should have gone in an `Upcoming` section). I've tried to reconcustrct the changelog based on [this diff](https://github.com/artsy/emission/compare/v1.5.0...develop-1.5.x) but I want a second set of eyes.

Changelog bump for 1.5.1 release

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-114
This PR adds a checkbox to the "Confirm your bid" screen.
* Right now it doesn't persist the flag so the checkbox will always show up, let me know if there's already a mutation endpoint we could use to do so.
* The button is disabled by default and enabled once the user checks it off, not sure if the animation is appropriate here though. cc: @briansw
* This also includes minor style tweaks

Show checkbox if you are unregistered (and verify copy)

---

CHANGELOG.md
src/lib/Components/Buttons/InvertedButton.tsx
src/lib/Components/Buttons/__tests__/InvertedButton-tests.tsx
src/lib/Components/Buttons/__tests__/__snapshots__/InvertedButton-tests.tsx.snap

This is similar to https://github.com/artsy/emission/pull/1006, but there seems to be two different `<InvertedButton>`s, one with the ability to show a spinner and the other without. This PR adds the ability to style the text to the one with the spinner.

Add the ability to style the text in the inverted button with spinner

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARComponentViewController.h
Pod/Classes/ViewControllers/ARComponentViewController.m
Pod/Classes/ViewControllers/ARHomeComponentViewController.h
Pod/Classes/ViewControllers/ARHomeComponentViewController.m
src/lib/Scenes/Home/index.tsx

Using the `page` prop of `ScrollableTabView` to set the page upon prop changes.
(Now branched off the right version)

[Home] Add support for changing tabs from native code (for 1.4.x)

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARComponentViewController.h
Pod/Classes/ViewControllers/ARComponentViewController.m
Pod/Classes/ViewControllers/ARHomeComponentViewController.m

This adds a new method to `ARComponentViewController` that sets the props of the `rootView` if the view is loaded, _or_ sets the `initialProps` for the `rootView` if it hasn't been loaded yet. I don't see any Objective-C tests for Emission so I didn't add any, but something to think about longer term.
This is useful for when we want to switch tabs on the home component controller when the app is launching (for example, from a push notification).

Adds prop-setting

---

src/lib/Components/Bidding/__stories__/BidFlow.story.tsx

Right now, we use the `<ConfirmBidScreen>` component that depends on relay. This has made visual testing a bit more difficult than it should since it could fail to load when the sale artwork that the hard-coded `saleArtworkId` points to does not exist. This PR will make the book more stable and easier to test by making it no longer dependent on external resources.
We may want to replace the other relay-based components with plain React components, except the `<BidFlowRenderer>` that's used in the actual flow, but let's see how this goes before we go too far.

Use <ConformBid> component that does not depend on relay in storybook #trivial

---

CHANGELOG.md
src/lib/Scenes/Home/__stories__/Home.story.tsx
src/lib/Scenes/Home/__tests__/index-tests.tsx
src/lib/Scenes/Home/index.tsx

Making sure that we: 
- are dispatching analytics at the right time (when tabs are changed, and when `viewDidAppear` happens after the VC wasn't visible)
- set the right `PageName` prop by adding a separate method used by `screenTrack` and `fireHomeScreenAnalytics`

[Analytics] Update home analytics for tab changes and inital tab props

---

README.md
docs/map_to_emission.md

In a recent Purchase team retrospective, we identified an opportunity to better document Emission. Developers rely on existing code as a foundation for writing new code, but not knowing which code should be used as a foundation impacts developer confidence. 
This map's goal is to be a living document that will accumulate links to pull requests, discussions, blog posts, etc, that relate to Emission's development. This initial PR is only a very small start – I didn't even try to make this comprehensive, just a few things that came to mind immediately. 
@mennenia I'd like to know what else should be included – I'm happy to be delegated to, or we can pair, or you can take over.

Adds Map 🗺 to Emission

---

CHANGELOG.md
src/lib/Scenes/Home/index.tsx

Based off [@ashfurrow's comment](https://github.com/artsy/eigen/pull/2612#issuecomment-390775648), using the `Page` prop is indeed cautioned against. 
Originally we went for this, as changing tab through just the `initialPage` prop wasn't working, however we are now switching to the recommended `goToPage` function. (thanks @ashfurrow!) 
🎉

[Home] Update home tab switching method 

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Input.tsx
src/lib/Components/Bidding/Components/__tests__/Input-tests.tsx

This PR addresses an edge case where the parent component of an `<Input>` component updates the `error` prop but the border color wasn't updated properly.
I tried to use [the new `getDerivedStateFromProps` callback](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) but seems like we aren't on the latest version of React Native, so I just used the `componentWillReceiveProps()`. The new test does not depend on the internals of the component, so it should not be difficult to migrate to `getDerivedStateFromProps` after react upgrade.

The <Input> component should update the border color when the parent component updates the error prop

---

tsconfig.json

because exclude has precedence, there's no point in having it in include too

remove dangerfile.ts from TS include

---

CHANGELOG.md
Pod/Classes/OpaqueImageViewComponent/AROpaqueImageView.m

On-device, the latest 1.5.2 of Emission fails to load a lot of the images on screen:
I took a look at the logs with the `CG_CONTEXT_SHOW_BACKTRACE` and `CGBITMAP_CONTEXT_LOG_ERRORS` environment variables set and it showed the following error:
```
2018-05-30 16:27:35.166254-0400 Artsy[9156:3906813] [Unknown process name] 
CGBitmapContextCreate: unsupported parameter combination:
8 bits/component; integer;
32 bits/pixel;
RGB color space model; kCGImageAlphaNoneSkipFirst;
kCGImageByteOrder32Little byte order;
1631 bytes/row.
Valid parameters for RGB color space model are:
16  bits per pixel,		 5  bits per component,		 kCGImageAlphaNoneSkipFirst
32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipFirst
32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipLast
32 …
```

Corrects problem with AROpaqueImageView showing empty images

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx
src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
src/lib/utils/track.ts

First round! 
Includes screen events for Max Bid, Confirm Bid, and Billing Address. 
Also has place bid events. 
@erikdstock I realised we had forgotten the other confirm bid screen (`ConfirmBid.tsx`), so I added events there, and seeing as it already had some network code, there's a success track also :).

[Analytics] For the new bidflow

---

src/lib/Components/Bidding/Screens/ConfirmBid.tsx

We can always use a plain variable when you do not have to trigger `render()` so the polling logic does not depend on the React lifecycle.

Use a plain variable when triggerring render() is not required #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Components/__tests__/__snapshots__/MarkdownRenderer-tests.tsx.snap
src/lib/Components/Bidding/Components/__tests__/__snapshots__/Title-tests.tsx.snap
src/lib/Components/Bidding/Elements/Theme.tsx
src/lib/Components/Bidding/Elements/Typography.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BidResult-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmFirstTimeBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBid-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/BidFlow-tests.tsx.snap

Fixes: https://artsyproduct.atlassian.net/browse/PURCHASE-95
Source: [Artsy type system](https://www.notion.so/artsy/Typography-d1f9f6731f3d47c78003d6d016c30221)
Styled system uses line heights relative to the font size in [this example](https://github.com/jxnblk/styled-system/blob/462283dcc7d819c38f7419991e6a0fd29ae182c8/docs/theming.md) but it appears to be working with absolute pixel values. Used absolute pixel values to make it consistent with Artsy's type system above.

Adds line-height to the type system

---

src/lib/Components/Bidding/Components/__stories__/Checkbox.story.tsx
src/lib/Components/Bidding/Components/__stories__/Input.story.tsx
src/lib/Components/Bidding/Components/__stories__/Markdown.story.tsx
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
storybook/storyLoader.js

The `BidFlow.story.tsx` has grown since we added it in the first sprint and I think it's time to extract some of the storybooks for smaller components.
Let me know if you have any feedback!

Re-organize storybooks for the new bidding flow #trivial

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARBidFlowViewController.h
Pod/Classes/ViewControllers/ARBidFlowViewController.m
src/lib/AppRegistry.tsx
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
src/lib/Containers/BidFlow.tsx
src/lib/Containers/__tests__/BidFlow-tests.tsx
src/lib/Containers/__tests__/__snapshots__/BidFlow-tests.tsx.snap
src/lib/relay/QueryRenderers.tsx

This work is tracked in [PURCHASE-174](https://artsyproduct.atlassian.net/browse/PURCHASE-174).
This PR was originally going to add a new native view controller, but I decided that reusing the existing Objective-C class was a better choice, but does lead to a little more complexity in the query renderer. Here's the breakdown:
- Expand the existing `<BidFlow>` component to support a registration flow based on a new `intent` prop.
- That makes the `artworkID` a nullable prop, so the query renderer `<BidFlow>` needs to handle missing artwork IDs too. I made a `TODO`.
- There's a possible edge case where the intent is `"bid"` but the `artworkID` is null, which would indicate programmer error, but something I wanted to bring up.
I [verified with …

Register flow infrastructure

---

src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx

I noticed that the five tests in `Timer-tests.tsx` were consistently taking longer than ten seconds to complete. I took a look and it appears that calls to [`advanceTimersByTime()`](https://github.com/facebook/jest/blob/3ce87434570d23be061648162488ca5599e40651/packages/jest-util/src/fake_timers.js#L260) does an amount of work that scales linearly with the amount of time to advance by (at least in our case, using `setInverval()`). When calling with `20 * MINUTES`, we're really calling `advanceTimersByTime(1200000)` 😅 
This PR reduces the amount of time the test takes to run to about 1s by reducing the number of minutes to advance time by to `1`, along with some adjustments to test data (to make sure time advances still cascade from seconds to minutes to hours). Let me know what I can …

Decreases timer tests duration #trivial

---

README.md
docs/adding_new_keys.md

This PR adds an explanation of the steps to add and expose a key via `cocoapods-keys`.

Document adding key

---

Pod/Classes/GraphQL/ARGraphQLQueryCache.m

Down from a day to an hour.
#native_no_changes

Reduces the default TTL for GraphQL queries in Emission

---

README.md

The Relay.MD file was removed by @orta here : https://github.com/artsy/emission/commit/6f0be7b23b88353893638c5236aad1829c78269c#diff-e3e2a9bfd88566b05001b02a3f51d286

Remove "Understanding Relay" Section

---

Makefile
README.md
package.json
yarn.lock

Hi,
when running "make setup && make oss" it installs node 10.4.1 and npm 6.1.0, but package.json specifies 8.4.x and 5.4.x, and thus the install breaks.
I updated package.json to point to 10.4.x and 6.1.x, and that seems fine. Added to PR.
Yarn is installed in /usr/local/bin, the pre-commit and pre-push hooks assumes this is in path. When using Tower it was not. Adding "export PATH=$PATH:/usr/local/bin" into the hooks remedied this. Added to PR.
Another thing, compared to the manual install, these automatic steps didn't build Cocoapods. Not sure they should, but thought I'd mention it.
Not sure as to why I had to enter my GitHub credentials during the "bundle exec pod install" step, was that intended?
Cheers
Niklas

Fresh install feedback

---

src/lib/Components/Bidding/Components/MaxBidPicker.tsx
src/lib/Components/Bidding/Components/__tests__/MaxBidPicker-tests.tsx
src/lib/Components/Bidding/Screens/BidResult.tsx
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx
src/lib/Components/Bidding/Screens/CreditCardForm.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
src/lib/Components/Bidding/Screens/__stories__/BidResult.story.tsx
src/lib/Components/Bidding/Screens/__tests__/BidResult-tests.tsx
src/lib/Components/Bidding/types.d.ts

We've been adding many many types since we started working on the bidding flow. Now it's time to consolidate and organize types all in `src/lib/Components/Bidding/types.d.ts`.
Let me know if there's any feedback!

Consoldiate types #trivial

---

CHANGELOG.md
src/__generated__/Registration_sale.graphql.ts
src/lib/Components/Bidding/Components/Timer.tsx
src/lib/Components/Bidding/Components/__stories__/Timer.story.tsx
src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
storybook/storyLoader.js

This PR updates the auction timer component to respect a `start_at` and an `is_preview` flag to be passed in order to show the time until an auction starts (only exercised during the registration flow).
For context, I adapted the logic here: https://github.com/artsy/force/blob/master/src/desktop/components/react/auction_block/utils/upcoming_label.js
Using the `is_preview` flag means we can avoid using system or device time for comparison. But! Brings up the (I think still unanswered?) question of what we should do when the timer _ends_ in any of our cases. On the web right now, we refresh the page to show you the new state. I'm not sure what we want to do here but we can follow up outside of this PR.

Adds support for preview sales to the auction timer

---

src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx
src/lib/Components/Bidding/Screens/CreditCardForm.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmFirstTimeBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/CreditCardForm-tests.tsx

This PR makes a few small changes (and was born out of my initial exploration into getting us fancy errors after stripe tokenization). I'll document my findings here:
- It _seems_ like most of the errors that would cause tokenization to fail are captured in the built-in form validations on the credit card form (things like an invalid cc number, cvc, or expiration date are already handled for us). 
- I moved the credit card tokenization on the `CreditCardForm` to that component so we get feedback on that screen if something goes wrong, but a follow-up will be to make sure we're catching networking errors and showing something generic on that screen. I'll update the story to be more explicit about this.
- I updated the `ConfirmFirstTimeBid` screen to require `billingAddress`, …

#trivial Updates to bid flow: require billing address/cc to be present before placing bid; move tokenization to cc form

---

src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmFirstTimeBid-tests.tsx

#trivial
This is a very blunt tool right now and might be missing some edge cases. It updates the auction screen's registration status (via NSNotificationCenter) upon receiving any bid result in the ConfirmBid screen.
I'm not sure if i'm missing anything & would like to add more tests- Also considered exporting constants for these Eigen notification names since we'll likely use them in another place on the registration flow, (and LAI bids in the future?) but holding back on that for now.

Update auction registration status on bid

---

.travis.yml

This extra check on master isn't needed because you're on master and always have secret env vars

Ensures that JS is uploaded

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap

After pressing spacebar, users will have their shift keys enabled already for them to enter in their info. 
Work tracked here: https://artsyproduct.atlassian.net/browse/PURCHASE-223

Autocapitalizes words on billing address inputs

---

src/lib/Components/Bidding/Components/PaymentInfo.tsx
src/lib/Components/Bidding/Components/__tests__/PaymentInfo-tests.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/PaymentInfo-tests.tsx.snap
src/lib/Components/Bidding/Elements/Grid.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/CreditCardForm.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap

This PR extracts the payment info (which wraps the `BillingAddress` and `CreditCardForm` components), since it's re-used between the registration flow and the bid flow.
The parent of those components has to hold the truth about the credit card token and billing address, since we create the credit card + (bid or register) in one go on that big button. So there's still a little repeated logic but it's not too bad.
I also updated the credit card form to accept props and pre-fill the card number based on what you'd entered before, if you click the "Edit" button to go back.
Note that we don't handle _anywhere_ the ability to halfway-save your billing address or credit card info. Not sure if that's an issue, but will make sure to follow up in case that becomes a need.
Made this #trivial since …

Extract payment info into a separate component #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Timer.tsx
src/lib/Components/Bidding/Components/__stories__/Timer.story.tsx
src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap

This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-210
Basically, when the state of an auction changes (or in our case, when the timer runs out), we want to update the label on the timer to reflect the new state.
In order to make this clearer, I extracted `AuctionTimerState` as its own enum and used that to define the `nextState` and `currentState`. The logic looks similar between these two methods but is slightly different so it made sense to keep them separate. But happy for ideas on how to make this make more sense!

Refactors timer to update on state change

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Markdown.tsx
src/lib/Components/Bidding/Components/Title.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/Title-tests.tsx.snap
src/lib/Components/Bidding/Elements/Typography.tsx
src/lib/Components/Bidding/Screens/BidResult.tsx
src/lib/Components/Bidding/Screens/__stories__/BidResult.story.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/CreditCardForm-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBid-tests.tsx.snap
src/lib/Containers/__tests__/__snapshots__/BidFlow-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-225
This PR removes the spacing between the icon and the message on the bid result screen. Below is a screenshot for a successful bid but this applies to any message pattern.

Fixes a style issue where the spacing of the messages looks weird on “Outbid” payoff screen

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Buttons/PrimaryBlack.tsx

Fix [Purchase 211](https://artsyproduct.atlassian.net/browse/PURCHASE-211)
_Note_ this merges into the [primary black button branch/PR](https://github.com/artsy/emission/pull/1120) (as it depends on that work)
Looks like:

[Bidflow] Disabled Button State

---

CHANGELOG.md
data/schema.graphql
data/schema.json
src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
src/__generated__/Registration_me.graphql.ts
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx

This PR addresses https://artsyproduct.atlassian.net/browse/PURCHASE-171
It uses the `me: has_credit_cards` to determine whether or not to show the payment info inputs or not on the registration screen.
The follow-up PRs to this will add the actual mutations.

Registration screen supports a user having a credit card on file

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/BidResult.tsx

I noticed that the white spaces in the `messageForPollingTimeout.desription` were interpreted as an actual space in the parsed markdown `Text`s. This PR removes them so the message will show up without a weird offset.

Properly format error message for the PENDING state

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Timer.tsx
src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx
src/lib/Components/Bidding/Elements/Typography.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-228
The timer's text style and order were updated about two weeks ago and this PR addresses the change.

Users see updated timer text style

---

CHANGELOG.md
Example/Podfile.lock
package.json
src/lib/Components/Bidding/Screens/CreditCardForm.tsx
yarn.lock

This PR fixes the default placeholder fields in our credit card form. It relied on a change to tipsi-stripe, which now merged also means we can update our package.json to use the official version rather than my fork.

Cc form placeholders #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Components/BidInfoRow.tsx
src/lib/Components/Bidding/Components/PaymentInfo.tsx
src/lib/Components/Bidding/Components/__tests__/__snapshots__/PaymentInfo-tests.tsx.snap
src/lib/Components/Bidding/Elements/Typography.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-181
* Prefer `Credit card` over `Credit Card`
* The margin between the checkbox and the Place bid button should be 20px when alreadt agreed and 40px when needs to show a checkbox
* Changed the margin for each row to be 20px so all the elements will be accommodated well in iPhone SE's smaller screen

There should be more space visually between conditions of sale checkbox and place bid button

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Timer.tsx
src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-149
Here is a screenshot for what it look like in the PR:

User should see the minutes in the auction timer when the sale does not on the hour

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/CreditCardForm.tsx
src/lib/Components/Bidding/Screens/__tests__/CreditCardForm-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/CreditCardForm-tests.tsx.snap
src/lib/Components/Buttons/BottomAlignedButtonWrapper.tsx
src/lib/Components/Consignments/Components/DoneButton.tsx

This PR updates the credit card form in the bidding flow to:
- Focus on the cc form when the component is rendered
- Have a button that slides up with the keyboard and is disabled when the inputs aren't valid.
Screenshot:
gif:

Fixes to the credit card form keyboard

---

src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/RegistrationResult.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx

This PR adds the "glue", meaning it hooks up the transition between the registration screen and the results screen.
@mennenia 's [PR](https://github.com/artsy/emission/pull/1137) added a nice abstraction around the `RegistrationResult` screen. Since the use-case is a bit simpler here (we're not trying to map error messages returned from MP with ones defined in Emission), it works nicely to have all of the statuses and messages defined in the `RegistrationResult` component. We can just pass the `status` and it will handle all of the display.

Updates registration view to advance to correct result screen #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx

@sweir27 - this line notifies the sale screen that the registration status has been updated. We had the name wrong due to a misreading of [this line](https://github.com/artsy/eigen/blob/master/Artsy/Constants/ARAppConstants.m#L19-L20) in emission:
```objc
NSString *const ARAuctionArtworkRegistrationUpdatedNotification = @"ARAuctionArtworkRegistrationUpdated";
```

fix incorrect notification name

---

src/lib/Components/Bidding/Components/Input.tsx
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
src/lib/Components/Consignments/Components/BottomAlignedButton.tsx

This PR:
- Updates the billing address form so you can scroll the elements above the keyboard
- Updates the billing address form to have "next" as the CTA and to advance to the next field when it is pressed
It was a little tricky to get that second part working. Major props to @orta for getting me started/helping (we do a similar thing on the consignments view).
I also found some weird behavior around the border colors on the input view, which I fixed by making sure we're passing through the `onBlur` as a differently-named-prop so we still get the default handler on the `TextInput`.
It's unfortunately difficult to test these things since I don't think we have `focus` and `blur` available in our test environment (in fact jest throws a warning saying so).

Billing address keyboard optimizations #trivial

---

src/lib/Components/Bidding/Screens/RegistrationResult.tsx
src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx

I copied exactly [what we do](https://github.com/artsy/emission/blob/master/src/lib/Components/Bidding/Screens/BidResult.tsx#L60) for the `BidResult` component, without the special case for it being a live sale since we don't handle that case separately.

Continue button on the registration flow dismisses the modal #trivial

---

src/lib/Components/Bidding/Screens/BidResult.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap

This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-150
I removed the `refreshSaleArtwork` call between the `ConfirmBid` screen and the `BidResult` screen. As we are no longer giving you a CTA to "Bid above x", we don't need updated information just yet and this can save us a network call.

Adjust bid button copy on outbid and confirm bid screens #trivial

---

src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/CreditCardForm.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/CreditCardForm-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx

This PR addresses https://artsyproduct.atlassian.net/browse/PURCHASE-195 by explicitly catching errors from Stripe's API.
Note that we are not _charging_ the cards that we tokenize (so most of the potential checks won't surface at this stage), and Stripe will successfully tokenize any card that passes the same validations that are implemented for free in the form element we're using. Therefore, the errors that we're catching are more likely to do with us being unable to access stripe's API at all and as such there's not really a need to clear the credit card form when this happens.
Here's a helpful stackoverflow answer that discusses the types of validations Stripe does while tokenizing (same as what the form implements): https://stackoverflow.com/a/50878951
Already discussed this …

Handle errors returned from Stripe during tokenization #trivial

---

src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
src/lib/Components/Bidding/Screens/SelectMaxBidEdit.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/SelectMaxBidEdit-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBidEdit-tests.tsx.snap
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx

The goal of this PR is to address https://artsyproduct.atlassian.net/browse/PURCHASE-236 -- you should be able to navigate between the `ConfirmBid` screen and the `SelectMaxBid` screen in order to update your bid, without all of your information being lost in between.
@yuki24 and I went through many potential implementations of this. This is what seemed to be simplest (a potential more ideal version in the _future_, if the interaction becomes more complex, would be to introduce something like redux to hold state globally).
This PR:
- Adds a new component `SelectMaxBidEdit` which is _not_ relay-based. It shows the `MaxBidPicker` and updates the `selectedBidIndex` on the `ConfirmBid` component.
- Changes the `ConfirmBid` component to store `increments` and a `selectedBidIndex` instead of a …

Allow for editing the max bid once on the ConfirmBid screen without losing information #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Elements/types.d.ts
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/SelectCountry.tsx
src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/SelectCountry-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectCountry-tests.tsx.snap
src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
src/lib/Components/Bidding/types.d.ts

This is a spike on https://artsyproduct.atlassian.net/browse/PURCHASE-251
This adds a new `<SelectCountry>` component. The visual part of mostly done, but the parent `<BillingAddress>` component needs to pass a callback function to the child to get the country field updated.

WIP: User can navigate to Select country screen and type a country name

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx

This updates the ConfirmBid screen to not show a ',' in the case of no date on the "title, date" line.
My solution is straightforward but I'm not sure if my tests are practical.
Example:
With date: 
New story with `null` date:

account for null date in artworks

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx

I noticed the following edge case:
1. Go to Your billing address screen
2. Tap on Add billing address button without filling out any fields
3. Make sure the country field has an error message
4. Tap on the country field and select country
5. Observe
The field does not get updated and displays an error even when the country name is properly displayed in the field.
The error message for the country field should disappear.

Make sure to re-validate the country field on country selected

---

src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
src/lib/tests/mockTimezone.tsx

I borrowed this completely from what we do in the `ConfirmBid` flow (which I _think_ works as confirmed by @erikdstock yesterday).
Addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-254

Notify eigen on completion of registration #trivial

---

src/lib/Components/Bidding/Components/__stories__/Markdown.story.tsx
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/__stories__/BidResult.story.tsx
src/lib/Components/Bidding/Screens/__tests__/BidResult-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap

This PR:
- gets rid of references to "Bid again to take the lead." (only in mocks/stories, but it no longer reflects reality so seemed important to remove)
- updates the postal code field to have a "next" button and when pressed, to bring up the country picker per https://artsyproduct.atlassian.net/browse/PURCHASE-257

[Bidding flow] Make country picker pop up automatically after pressing "next" from the postal code field #trivial

---

src/lib/relay/QueryRenderers.tsx

This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-249
The bid/registration flows are slightly different than the others because we are explicitly sending props in our query renderer (as they are different from what's received). This caused us to always [skip](https://github.com/artsy/emission/blob/master/src/lib/utils/renderWithLoadProgress.tsx#L33) showing the `Spinner` on those views unless we explicitly pass the render function with null values here.

Show spinner when pulling up bidding and registration flow #trivial

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap

Fixes [PURCHASE-239](https://artsyproduct.atlassian.net/browse/PURCHASE-239).
Here's before:
And here's after:

Sets artwork and artist name labels on ConfirmBid component to use only one line

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-260
This PR just updates the `<BillingAddress>` and `<Registration>` components to not call any callbacks or just inject a null navigator when `isLoading` is true so users won't be able to launch other screens.

User should not be able to click into the billing address/cc/max bid edit forms while your bid is being placed

---

CHANGELOG.md
Pod/Classes/EigenCommunications/ARNotificationsManager.m
package.json

#trivial 
cc @ashfurrow - The changes you requested to prevent eigen ui updates from running off the main thread.

dispatch notifications on the main thread

---

src/lib/Components/Bidding/Screens/BidResult.tsx

As we found yesterday, the pattern of dismissing the modal view controller and pulling up a new one in a single method doesn't work as we expected (which actually makes some sense). This updates that button to either pop the live auctions view on top of the current one, or dismiss it entirely (but never both).

Fix the "Continue" button on the "Live bidding has started" screen #trivial

---

CHANGELOG.md
src/lib/relay/QueryRenderers.tsx

I took a stab at [Purchase-297](https://artsyproduct.atlassian.net/browse/PURCHASE-297). Based on what I read in [the docs](https://facebook.github.io/relay/docs/en/query-renderer.html), this is how Relay expects us to indicate that we want to bypass the cache for this query. **However**, I was unable to reproduce the original bug at all (it appears intermittent). My guess is this has something to do with debug vs. production builds of the app.
So, this PR _should_ fix the bug _in theory_, but we should test in the next beta to be sure.

Ignores cache when loading BidFlow query

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx

This PR fixes a slight omission from #1172 where the conditions of sale link was enabled in the case where the user had previously accepted them and now checkbox was rendered. [Here](https://github.com/artsy/emission/pull/1172/files#diff-8a3a841add9adeac68c88de41a452cc4R446) is the line of code.
Self-assigning because everyone else is out and this is trivial. Wonder if merge on green works in PR bodies?

Disables condition of sale link if the user has previously accepted them #trivial

---

README.md
docs/troubleshooting.md

Adds a new `docs/troubleshooting.md` guide and includes a recently confusing issue around requiring media assets. 
#trivial

[Docs] Add troubleshooting.md

---

CHANGELOG.md
src/lib/Containers/WorksForYou.tsx
src/lib/Containers/__tests__/WorksForYou-tests.tsx
src/lib/Scenes/Home/__tests__/index-tests.tsx
src/lib/Scenes/Home/index.tsx

**Addresses:** https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&modal=detail&selectedIssue=DISCO-327
Hide Home view `"Sell works from your collection through Artsy"` consigments sash if `enableBuyNowMakeOffer` lab feature is on.
**TODO**: Swap the lab feature out for an Echo feature flag.

[BNMO Home] Hide consignments sash

---

README.md

I got pretty far along in the setup process before realizing Xcode wasn't installed; it'd be good to catch that earlier, by mentioning it as a prerequisite.

Mention that Xcode is a prereq

---

CHANGELOG.md
Example/Emission.xcodeproj/project.pbxproj
Pod/Classes/VideoComponent/ARVideoManager.m
package.json

I was looking at Eigen's Sentry logs and came across [this new crash from 4.3.2](https://sentry.io/artsynet/eigen/issues/748150611/?query=is:unresolved):
```
Application threw exception CALayerInvalidGeometry: CALayer position contains NaN: [nan 110]
```
(It's only happened to one user so far.)
I took a look at the code and it looks like in some edge cases, we might be dividing by zero to calculate the aspect ratio. I put in a check for `isnan` first, hopefully this will fix it.

Fixes crash from possible division by zero

---

CHANGELOG.md
Example/Emission/ARLabOptions.m
docs/adding_a_lab_option.md
src/lib/Containers/__tests__/index-tests.tsx
src/lib/Scenes/Home/__tests__/index-tests.tsx
src/lib/Scenes/Home/index.tsx
src/lib/options.ts

Brings back the consignments sash and lets it be something we can toggle via Echo if needed. In doing this I also added some docs on how the lab options work.
This is for DISCO-460

Brings back the consignment banner to the home component

---

Emission.podspec
Example/Podfile

Tightens up the dependencies in the Emission podspec to the exact versions of the JS that's emitted.

Tighten the native dependencies for Emission

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/Artwork.tsx
src/lib/Components/ArtworkGrids/__tests__/Artwork-tests.tsx

I was looking through Eigen's Sentry and found [this crash](https://sentry.io/artsynet/eigen/issues/587358816/events/latest/). It's been around about 5 months and happens occasionally. There isn't a lot of detail in the crash report, but based on the breadcrumbs, users see this crash on the home screen. This PR adds some extra checking to the data that comes from Relay. Here's the situation:
> What if we have an artwork that has a sale, and that sale is an artwork, but the `sale_artwork` property on the `artwork` object is `null`?
I don't know under what circumstances that would happen, but based on the breadcrumbs this is the most likely source of the crash. The fix is to simply get `sale_artwork` from `artwork` and check it for `null` first. Thoughts?

Adds extra checking around sale artwork messaging in artwork grids

---

src/lib/Scenes/Fair/index.tsx

Fixes a crash triggered when accessing the Fair screen
#trivial

Pass through partnerType to LocationMap on Fair

---

.vscode/extensions.json

This should hopefully recommend to uninstall, or maybe not load it - I'm actually unsure.

Update extensions.json to remove the old GraphQL extension

---

.circleci/config.yml

[The docs](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-474/index.html) list iPhone 6 (10.3.1) as an installed simulator, but the build is [failing](https://circleci.com/gh/artsy/emission/171) with:
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
{ platform:iOS Simulator, OS:10.3.1, name:iPhone 6 }
```
First step is to list the installed simulators.

Lists simulators in native CI runs #trivial

---

CHANGELOG.md

Some CHANGELOG entries were posted under the wrong release section....this commit updates that.
#trivial

moves CHANGELOG entries to correct release

---

Example/Gemfile
Example/Gemfile.lock

Switches a flaky Gemfile reference to a better repo location now that @ashfurrow's PR has been merged. 
We'll want to clean this up further once Square cuts an actual new release of the gem.

Fix gemfile reference to cocoapods-check

---

CHANGELOG.md
src/lib/Scenes/Fair/Components/FairHeader/index.tsx
src/lib/Scenes/Fair/Screens/FairDetail.tsx

- Checks in the view for `fair.profile` before rending profile values
- Moves Fair countdown higher

Checks for fair.profile on render and styles countdown

---

Example/Gemfile
Example/Gemfile.lock

I did a `bundle update cocoapods-check` now that https://github.com/square/cocoapods-check/pull/13 got merged and released. It updated CocoaPods too, which, why not.

Updates CocoaPods/cocoapods-check #trivial

---

Example/Emission.xcodeproj/project.pbxproj

@ashleyjelks was seeing the following error, which I managed to reproduce locally:
```
[!] Unable to determine Swift version for the following pods:
- `FBSnapshotTestCase` does not specify a Swift version and none of the targets (`EmissionTests`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```
The solution was to add a Swift file to the test target, then delete it (because Swift files can't be integrated into our Xcode project directly... yet). I also removed the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` which was left over from an earlier version of CocoaPods.

Fixes pod install #trivial

---

CHANGELOG.md
src/lib/Components/ScrollableTabBar.tsx
src/lib/Scenes/Favorites/index.tsx

This PR removes the Fairs tab button from the Favorites scrolling tab. 

removes Fairs tab from Favorites view

---

src/lib/Components/Buttons/CaretButton.tsx
src/lib/Components/Buttons/__tests__/CaretButton-tests.tsx
src/lib/Components/Buttons/__tests__/__snapshots__/CaretButton-tests.tsx.snap
src/lib/Scenes/Fair/Components/__tests__/__snapshots__/ArtistsExhibitorsWorksLink-tests.tsx.snap

Change the positioning of the caret button to fit design specs

---

CHANGELOG.md
package.json
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap
src/lib/Components/Markdown.tsx
src/lib/Components/__tests__/Markdown-tests.tsx
yarn.lock

This never worked, so now if anyone creates a new item in the markdown config a test will fail if they don't remember to do the `...default`.
Fixes LD-214

Fixes rendering markdown in Fair/Show (but also everywhere else

---

CHANGELOG.md
src/lib/Components/Show/ShowArtworksPreview.tsx

Fix for the artwork count in a show

---

src/lib/Scenes/Fair/Components/FairHeader/index.tsx

Fixes logo size to contain #trivial

---

src/lib/Components/LocationMap/index.tsx

- The title now will take into account fairs, and is always the same as the text copied. 
- Google maps now only gets lat/lng and under the hood that is shown as an address (on the site at least)
- Better handling of no postal code existing
#trivial

Improvements to fair handling for map preview taps

---

src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap
src/lib/Components/Markdown.tsx
src/lib/Components/__tests__/Markdown-tests.tsx
src/lib/Scenes/Fair/__stories__/Fair.story.tsx

Adds more options in the markdown renderer, without them the react library falls back to react-dom types which aren't available and so the app crashes
#trivial

Adds more markdown rendering options

---

CHANGELOG.md
src/lib/Scenes/Fair/Components/FairHeader/index.tsx

For example: https://www.artsy.net/affordable-art-fair-battersea-spring-2019

Fixes fair view crash on fairs with no profiles #trivial

---

Example/Emission/AppDelegate.m

- Show routing was broken in emission if `/` was used before `show` e.g. `/show/${id}`. This PR fixes this issue.

Updates show routing for emission to not break if / is used before href

---

CHANGELOG.md
src/lib/Scenes/Map/MapContainer.tsx

Follow-up to LD-295 / #1377. This is a workaround until LD–309 is addressed.

Fixes render failure with missing city coords.

---

CHANGELOG.md
src/lib/Components/TabBar.tsx
src/lib/Components/__stories__/TabBar.story.tsx
src/lib/Scenes/City/City.tsx
src/lib/Scenes/Home/Components/__tests__/__snapshots__/TabBar-tests.tsx.snap
src/lib/Scenes/Home/index.tsx
src/lib/Scenes/Map/Bucket.ts
src/lib/Scenes/Map/Components/FiltersBar.tsx
src/lib/Scenes/Map/GlobalMap.tsx
src/lib/Scenes/Map/__stories__/Map.story.tsx
src/lib/Scenes/Map/types.ts
storybook/storyLoader.js

This brings the main Home tab inline with the design in palette making the two consistent
I looked at turning these both into a single component, but the version in Home and the component in the City are pretty far away in implementation, so I'm bailing on that for now. 

Ensure the tab is consistent throughout Emission

---

CHANGELOG.md
src/lib/Scenes/City/Components/EventSection/index.tsx
src/lib/Scenes/Map/MapRenderer.tsx

This PR fixes two warnings I was seeing in dev builds: missing `viewer` prop for `GlobalMap` and duplicate keys in the `EventSection` component. 

Fix a few warnings

---

CHANGELOG.md
src/lib/Scenes/City/cities.ts

This is a one-off change to bring Emission's city data inline with [Metaphysics' version](https://github.com/artsy/metaphysics/blob/master/src/schema/city/city_data.json) of the same.
A further enhancement would be to consolidate this source of truth via the build process, an item which is ticketed elsewhere.

Sync city coordinates with Metaphysics

---

CHANGELOG.md
Example/Podfile.lock
src/lib/Components/Lists/ShowItemRow.tsx

This PR handles narrow iphone screens so the Saved Shows text does not get truncated off the screen on smaller iphone devices. PR involved a refactor to the Flexbox code that contained the Saved Shows contents. 

Narrow iphone fix

---

dangerfile.ts

Every PR now has the "skip new tests" directive, so let's just ignore it for now. We can re-enable after submitting LD.

Skips new tests on all PRs #trivial

---

Emission.podspec

This JSON can be picked up in Eigen, and used to provide better visibility into the Emission integration in Eigen.
```
~/d/p/a/i/emission  $ pod ipc spec Emission.podspec
{
"name": "Emission",
"version": "1.8.14",
"summary": "React Native Components used by Eigen.",
"homepage": "https://github.com/artsy/emission",
"license": "MIT",
"authors": {
"Artsy Mobile": "mobile@artsy.net"
},
"source": {
"git": "https://github.com/artsy/emission.git",
"tag": "v1.8.14"
},
"platforms": {
"ios": "8.0"
},
"source_files": "Pod/Classes/**/*.{h,m}",
"preserve_paths": "Pod/Classes/**/*.generated.objc",
"resources": "Pod/Assets/{Emission.js,assets}",
"dependencies": {
"Artsy+UIColors": [
],
"Artsy+UIFonts": [
">= 3.0.0"
],
"Extraction": [
">= 1.2.1"
],
"Pulley": [
],
"SDWebImage": [
">= 3.7.2",
"< 4"
], …
```

Adds more metadata to the Podspec

---

CHANGELOG.md
src/lib/Icons/PinSavedOn.tsx
src/lib/Icons/PinSavedSelected.tsx
src/lib/Scenes/Map/GlobalMap.tsx

This PR adds UI changes to indicate when a user has selected a single show or cluster point in the City view.
[Links to LD-67](https://artsyproduct.atlassian.net/browse/LD-67)

Select pin ld67

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARMapContainerViewController.m

Now it won't accidentally rotate when you show someone else the map
#native_no_changes

Don't allow the map to rotate

---

src/lib/Scenes/City/CityPicker.tsx
src/lib/Scenes/City/Components/SavedEventSection/index.tsx
src/lib/Scenes/Map/GlobalMap.tsx

About this PR:
To handle showing and removing the checkmark icon from a city name on the City, we save a selectedCities field to state.  
This state is updated twice when a user interacts with the modal: once to show the icon on the selected city, and then again after the touch event to clear the icon and remove the modal. 
Since this.setState is an asynchronous function, I am passing the second call to it as a callback to be called after the first call completes. 
#trivial

Move set state to callback

---

CHANGELOG.md
Example/Podfile.lock
Pod/Classes/ViewControllers/ARMapContainerViewController.m

Fixes [LD-443](https://artsyproduct.atlassian.net/browse/LD-443). It also disables user interaction on the city picker until its presentation animation is complete. #native_no_changes.

Only ever show one city picker at a time

---

CHANGELOG.md
src/lib/Components/Lists/ShowItemRow.tsx
src/lib/Scenes/Map/Components/ShowCard.tsx

This PR reverts a change where the Saved button was removed from all instances of the Show Item Row component.
Now the button is only removed from this component on the Show Card in the Global Map view.

Revert remove save shows

---

CHANGELOG.md
src/lib/Scenes/Fair/Screens/FairDetail.tsx

Fix using `openingHours` on `Fair`, while `fair` has `Location` which can have `openingHours`, looks like we are using `hours` field of a fair which is a markdown text.
This was caused by #1478

Fix fair hours

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARMapContainerViewController.m

This fixes the drawer interaction, hopefully once and for all:
The was broken by our switch to `ScrollableTabView` and #1476. The solution is complicated. But basically, the new tab view implementation has _a bunch_ of vertical scroll views (the old one replace the contents each time). This means that our `ARLocalDiscoveryCityGotScrollView` notification can't look for a reliable vertical scroll view (since the one it finds might be offscreen later). It also allows vertical bouncing, which is the behaviour we're seeing on the current beta. 
The solution is to find the city content scroll view, then walk up the hierarchy to find its containing `UIScrollView`. This is the horizontally-scrolling (vertically-bouncing) `ScrollableTabView`. We could just disable scrolling, but remember that we …

Fixes drawer UX

---

Pod/Classes/ViewControllers/ARMapContainerViewController.m
dangerfile.ts

Old behavior: When we had the drawer closed (or half closed) you could see things like shows and fairs in the drawer, but couldn't click on them.
This caught both people I tested the app on, (and myself) which we figured was a bug. So I asked owen and he also figured we should make it interactable but not scrollable. 
New behavior: manually sets all of the scroll enableds down the view tree instead of having a hard stop pretty high up the tree.
- Also makes the native check for danger only be affected by header changes, this shouldn't get a warning.

Tappable items in when pulley is semi-closed

---

CHANGELOG.md
src/lib/Scenes/Map/Components/ShowCard.tsx
src/lib/Scenes/Map/GlobalMap.tsx

Fixes the following crash: https://sentry.io/organizations/artsynet/issues/933653125/
Related: https://artsyproduct.atlassian.net/browse/LD-407
We were getting inconsistent zoom outs as the user was switching cities because of a race condition.
Two different zoom levels were being applied
1. when a user switches filters
2. when a user switches cities via the picker
Here we remove the filter switch zoom out as it was causing issues as they were being applied almost at the same time when switching cities. Also speeds up the zoom out animation a bit.
A better long term fix will be to set bounds to contain all pins on the map to make sure there's always something visible on the map.
#trivial

Fixes zoom outs when switching cities and fix cluster crash

---

CHANGELOG.md
src/lib/Scenes/City/Components/BMWEventSection/index.tsx

We reproduced this in the simulator by setting the `dev` query string param to `false`: 
https://github.com/artsy/emission/blob/d053d5335fe9b335759b6bb9d9f11e605b1b8e74/Example/Emission/AppSetup.m#L76
The `CaretButton` was wrapped  in a `Sans` component, but it actually contains a `Sans` component, so that double-`Sans` was causing no text to display.
Fixes [LD-418](https://artsyproduct.atlassian.net/browse/LD-418).

Fixes missing "view all shows" link in sponsored content sections

---

src/lib/Scenes/City/Components/EventList.tsx

Adds margins to View when there are no saved shows, fairs, or galleries to render on the City card.
#trivial

Noscroll padding

---

CHANGELOG.md
src/lib/Components/Lists/ShowItemRow.tsx

Saw this in Sentry: https://sentry.io/organizations/artsynet/issues/935448722/events/49426017214/

Fixes crash on stub shows with no partner profile image

---

src/lib/Scenes/Fair/Screens/FairDetail.tsx

The data being pushed to section had `{ hours: 'text' }` while component was assuming it's getting only `text`

Fix fair [Objct object] for hours issue #trivial

---

Example/Podfile.lock
scripts/release.js

Ensure a `pod install` after a release doesn’t lead to new changes to the lock file.

Update pods during release

---

CHANGELOG.md
Example/Podfile.lock
Pod/Classes/ViewControllers/ARMapContainerViewController.m
src/lib/Scenes/City/City.tsx

The problem was occurring when we the tabs changed and a new scroll view was added to the view hierarchy. I tested this on device to make sure it worked.

Updates drawer sub-scrollview enabled state when tabs change 📱

---

CHANGELOG.md
src/lib/Scenes/City/City.tsx
src/lib/Scenes/Map/GlobalMap.tsx

Will comment inline about reduced city render pass. Otherwise this PR replaces inline function props to be stable, just on the odd chance that we're re-rendering trees more than necessary as these functions will never be the same across render passes.

Fewer city render passes

---

Example/Emission.xcodeproj/project.pbxproj
Example/Emission/Emission.entitlements

Sibling to https://github.com/artsy/artsy-eigen-web-association/pull/25
Doesn't actually do the work though, just makes it feasible once ^ is deployed.

Sets up the creds for webcredential sharing

---

CHANGELOG.md
src/lib/relay/QueryRenderers.tsx
src/lib/relay/createEnvironment.ts

This is a follow-up from #1502. 
The query renderers in `QueryRenderers.tsx` all use the same environment, but it is not the `defaultEnvironment`:
https://github.com/artsy/emission/blob/150ed9f7eefbf3494fcd81e11c5fccce7f5d5cf6/src/lib/relay/QueryRenderers.tsx#L57
But that environment is different from the environment used in our map component: 
https://github.com/artsy/emission/blob/150ed9f7eefbf3494fcd81e11c5fccce7f5d5cf6/src/lib/Scenes/Map/MapRenderer.tsx#L25
Leading to [LD-488](https://artsyproduct.atlassian.net/browse/LD-488). 
There seem to be only two production Relay environments left, and this PR will unite them into one. I've added a comment to the `createEnvironment.ts` file for now, and have added tooling discussion to prevent this in the future to our list of Front-End iOS …

Fixes LD saving events inconsistencies

---

src/lib/Components/Lists/ShowItemRow.tsx

This PR narrows the middle column in the Favorites show by 15px so that the Saved button isn't clipped by smaller devices.
[Links to an issue reported in LD=481](https://artsyproduct.atlassian.net/browse/LD-481) 
#trivial

narrows show detail column by 15 px to fit saved button in view

---

CHANGELOG.md
src/lib/Components/ScrollableTabBar.tsx
src/lib/Scenes/Favorites/index.tsx

This PR corrects text overflow issues that happened in the Favorites view on smaller sized iPhone devices. It also changes the order of the tabs that appear in the favorites view.
[Links to LD-481](https://artsyproduct.atlassian.net/browse/LD-481)

Fix UI issues in Saves and Follows on non iPhone X devices

---

src/lib/Scenes/City/Components/AllEvents.tsx
src/lib/Scenes/City/Components/BMWEventSection/index.tsx

This PR changes the title of the BMW Section on the City show card.
[Links to LD-494:](https://artsyproduct.atlassian.net/browse/LD-494)
#trivial

Copy update in BMW section title

---

CHANGELOG.md
src/lib/relay/middlewares/__tests__/cacheMiddleware-tests.ts
src/lib/relay/middlewares/cacheMiddleware.ts

This PR changes the caching middleware on Emission to no longer store GraphQL responses that contain `errors` in the on-device cache. I have tested this locally against metaphysics.
Fixes [LD-502](https://artsyproduct.atlassian.net/browse/LD-502).

Relay no longer caches GraphQL responses which contain errors field

---

src/lib/Scenes/Map/GlobalMap.tsx

Implements: https://artsyproduct.atlassian.net/browse/LD-489
Workaround/fix for: https://artsyproduct.atlassian.net/browse/LD-438
(Update: Note that Jun and I have also adjusted min zoom and default zoom in this PR as well.)
This adds a maxZoom to the map. Before this you could zoom in so far that you were looking at nothing but a pin and a vast gray featureless expanse (see LD-489). Now you will be limited at a max zoom of 17.5, which basically ensures that you will see some street grid.
(This also appears to have a side effect of fixing LD-438.)
#trivial

Configure a maxZoom for map component

---

src/lib/Components/Lists/ShowItemRow.tsx
src/lib/Scenes/City/CityFairList.tsx
src/lib/Scenes/City/Components/EventList.tsx
src/lib/Scenes/City/Components/TabFairItemRow/index.tsx
src/lib/Scenes/Favorites/Components/Shows/index.tsx
src/lib/Scenes/Map/Components/ShowCard.tsx

This PR moves control of margin and padding around Show and Fair List Items to its parent container rather than keeping them on the Show and Fair List Item components themselves.
It also obviates the need to add hacky props like `addMargin` and `noMargin` to the Show and Fair List Item components.
#trivial

Remove conditional sizing

---

CHANGELOG.md
src/lib/Scenes/Map/GlobalMap.tsx

Iteration on https://artsyproduct.atlassian.net/browse/LD-407
When interacting with the map, it's possible to get into a permutation of custom **zoom**, **heading** (rotating away from north), and **pitch** (tilting away from camera-pointing down)
For example, facing down Canal St towards the Manhattan Bridge.
Currently when we switch to another city, we reset the zoom, but leave the heading and pitch unchanged, which leads to an unexpected initial experience:
We can instead reset all three — zoom, pitch and heading in order to restore a neutral initial vantage point into the new city.
Furthermore, by taking advantage of an easing animation with a generous duration, we can also mitigate the perceived delays associated with the initial fetch of a new city's data.
Putting that all together …

Reset zoom, pitch and heading  upon city switch

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARMapContainerViewController.m
package.json

If the user leaves the Map view and comes back, two things happen:
- our top button flash top positions 
- cards get hidden by the drawer
This PR fixes this behavior

[Map] Do not reset safeAreaInsets back to 0

---

src/lib/Scenes/Show/Screens/MoreInfo.tsx

- https://artsyproduct.atlassian.net/browse/LD-521
#trivial

LD-521 - Adds opening reception header to stub shows #trivial

---

dangerfile.ts

This reverts commit 60f0a86bc422f7aa6e163111f6317606b779a514.

Adds back Danger rule requiring tests for new files #trivial

---

CHANGELOG.md
src/lib/Scenes/City/Components/EventSection/index.tsx

- The `opening soon` and `closing soon` sections in the `All` tab had a second unnecessary sort which was distorting the order, this fixes this issue by removing it.

Removes second sort on brick shows

---

CHANGELOG.md
src/lib/Scenes/Map/GlobalMap.tsx

Fixes [LD-533](https://artsyproduct.atlassian.net/browse/LD-533).
The problem was that we were only ever sending the error (and never sending once the error was completed). I added a check where we only send if the values are different, and I want to take a look at using a similar approach with calculating+emitting bucket results (marked by a TODO right now).
This also needs a test, hoping to pair with @kierangillen on the `EventEmitter` mocking stuff tomorrow morning.

Fixes City not re-rendering after a MP request is successfully retried

---

CHANGELOG.md
src/lib/Scenes/City/Components/Event/index.tsx

This PR fixes the UI bug causing the Save button on smaller screen iPhones to extend beyond their containers.
[Links to LD-546](https://artsyproduct.atlassian.net/browse/LD-546)
[Here's a good post to explain my rationale for implementing the fix this way](https://gedd.ski/post/the-difference-between-width-and-flex-basis/)

Fixes button overflow on smaller devices

---

CHANGELOG.md
Pod/Classes/Core/ARCocoaConstantsModule.m
src/lib/relay/createEnvironment.ts

So MP can use that as the default timezone for datetimes that should be rendered in the user’s local time (for instance the start time of a live auction).
Most importantly, this will allow us to fix _some_ issues outside of an app release, in the future.
This mimics Reaction https://github.com/artsy/reaction/blob/0aba9cc92bc99464bf1e4209301bd78eba7f39be/src/Artsy/Relay/createRelaySSREnvironment.ts#L70

[metaphysics] Pass local timezone to MP

---

CHANGELOG.md
src/lib/AppRegistry.tsx
src/lib/Scenes/Favorites/Components/Artists/index.tsx
src/lib/Scenes/Favorites/Components/Artworks/index.tsx
src/lib/Scenes/Favorites/Components/Categories/index.tsx
src/lib/Scenes/Favorites/Components/Fairs/index.tsx
src/lib/Scenes/Favorites/Components/Shows/index.tsx

Related to [DISCO-978](https://artsyproduct.atlassian.net/browse/DISCO-978). Here's what's up:
- I removed the yellow boxes from our dev experience, with links back to why we're ignoring those warnings.
- I added pull-to-refresh controls to the favs tab components (Works, Artists, Shows, etc). The control doesn't work on empty data sets, so there's still room for improvement, but having a pull-to-refresh on the fav artworks page is an important step forward.
- ~I specified the Home and Favs tabs to pre-render sibling components on load. This means that, when the app launches on the home tab (artists sub-tab), the WFY and Auctions sub-tabs will load in the background, making the app feel more responsive.~
That last one is the most contentious – I'm hoping to get a 👍 from @orta to make sure …

Removes yellow boxes, adds pull-to-refresh controls, pre-renders sibling tabs for Home+Favs

---

Emission.podspec
Example/Podfile.lock
Example/Pods/Pods.xcodeproj/project.pbxproj
package.json
yarn.lock

This was [discussed on Slack](https://artsy.slack.com/archives/C02BAQ5K7/p1557936869065400). Since we have a dependency on `react-native-navigator-ios`, that dependency should be reflected in the podspec. I've also forked Orta's changes of the repo to my account.
Prettier's done a job on the podspec, too.

Adds react-native-navigator-ios to Podspec, points to Ash's fork #trivial

---

CHANGELOG.md
Example/Pods/Pods.xcodeproj/project.pbxproj
src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx

Our recent upgrade of React Native caused a problem where photo selection in the consignments screen wasn't working. We still use `CameraRoll` (part of RN) as opposed to [`react-native-cameraroll`](https://github.com/react-native-community/react-native-cameraroll), but they had a similar problem. It seems RN recently switched fro AVFoundation for asset-querying to the new Photos framework. [The fix mentioned here](https://github.com/react-native-community/react-native-cameraroll/issues/18#issuecomment-478175321) fixes things in the simulator, and I think it _should_ work. I'll test the beta, of course.

[AUCT-382] Fixes consignment photo selection

---

CHANGELOG.md
Pod/Classes/Core/ARCocoaConstantsModule.m
src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx
src/setupJest.ts

Thank you to @l2succes for pairing on this!
This PR exposes `currentLocale` and `AREnabled`, based on settings from a user's native environment.
It also updates the `ArtworkActions` component to consume the `AREnabled` flag and use it to hide/show the "View in Room" button.

PURCHASE-1121: Adds flags for AREnabled and CurrentLocale to support artwork view

---

src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
src/lib/relay/createEnvironment.ts
src/setupJest.ts

Follow-up from #1599. This removes some unneeded ` || {}` and adds a stub value for `NativeModules.Emission` in the Jest setup.

Removes extraneous guards, improves Jest setup #trivial

---

package.json

Omakase by default [creates](https://github.com/omakase-js/omakase/blob/master/packages/cli/src/generator/templates/Component.test.tsx.ejs) tests with `.test.tsx` format and emission is currently only picks up `-tests` files.
pick all `*tests.(ts|tsx|js)` files.

Allow .tests to also be picked up by jest

---

Example/Podfile.lock

This is the equivalent PR to Eigen's https://github.com/artsy/eigen/pull/2837 and updates the Artsy fonts pod to a new patch version. This new version includes [a change](https://github.com/artsy/Artsy-OSSUIFonts/pull/18) to prevent Artsy staff from having the open source versions of our fonts cached, which has caused problems in the past. This changes makes the font pod installation fail loudly if `hokusai` is installed but the closed-source fonts couldn't be downloaded (ie: the developer running `pod install` works for Artsy so they should _only_ have the closed-source fonts installed).
There are updates to the `tipsi-stripe` and `react-native-navigator-ios` checksums – pretty sure those are okay, but have been churning lately. I'll keep an eye on them.

Updates Fonts pod #trivial

---

Emission.podspec

The variable name `path` seems very safe to use here, but it turns out it is not. This entire code of podspec will be `eval`-ed by the `Pod._eval_podspec` method, which, literally, uses the `eval` method. In `_eval_podspec`, there is [an argument called `path`][1], which happens to be used in `Emission.podspec` as well. As a result of this, setting a value to `path` in a podspec file overrides  `path` (the argument).
And if you are lucky (or unlucky) and the execution fails, this `_eval_podspec` rescues an exception and attempts to generate a message with the assumption that the `path` responds to `:basename`. However, since the `path` has been ovrriden by the `Emission.podspec`, it is no longer ture and the call ends up raising another exception.
We could work around this by just using a …

Avoid naming conflict with a variable name in cocoapods-core

---

src/lib/Scenes/Artwork/Artwork.tsx

- Fixes Artwork view when `layer` is `null`
#trivial

[Artwork] Checks for layer before calling it

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/SelectCountry.tsx

App crashes when back-spacing country-select name. This is happening on App Store build so I want to get a fix in so we can release this week.
- Login with a user that has no credit card on file.
- Create a timed auction.
- Register for the sale through the app.
- In the Billing Address screen, tap "Country" to go to the country select screen.
- Start typing.
- Backspace until the text field is empty.
- The country select screen shows no countries until text is entered
- The app crashes when the text field contents are cleared.
---
The crash is caused by the expression `query && !isLoading && (<Components ... />)` in the case that `query = ""` and `isLoading = true`. In this case, JavaScript short-circuits `&&` after `!isLoading` and the whole expression evaluates to `""`, and React …

Fixes crash with empty country selection

---

CHANGELOG.md
Example/Emission/AppDelegate.m
Example/Podfile.lock
Example/Pods/Pods.xcodeproj/project.pbxproj
Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
package.json

This was already the case, and the changed parameter names have no effect on _this_ code, though it'll make it more obvious. See conversation here: https://github.com/artsy/eigen/pull/2856#discussion_r299645729

Changes method parameter names to make the units for width+height in inches

---

src/lib/Scenes/Artwork/Components/ArtworkActions.tsx

__Before:__
__After:__
#trivial

PURCHASE-1224: "View in room" button should be centered

---

src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx

While testing something unrelated I ran across an invariant issue where `edition_of` returned an empty string.
This is related to a lot of other fixes that @kierangillen did in https://github.com/artsy/emission/pull/1559
See https://github.com/facebook/react-native/issues/20764 for more context.
#trivial

Ensure `edition_of` is never an empty string

---

CHANGELOG.md
src/lib/Scenes/Map/GlobalMap.tsx

This code was [recently refactored](https://github.com/artsy/emission/commit/a73a34de3abfc1e6df2176a1b6a903726b7fed83) by @alloy  but I don't quite understand how this was _ever_ working. The ref we were storing was always `undefined`. According to [the docs](https://reactjs.org/docs/refs-and-the-dom.html), the call to `.root` is unnecessary. @ds300 ran into a similar problem here: https://github.com/artsy/emission/pull/1700/files#r300014570
In any case, this is working now! h/t to @ansor4 for debugging this with me.

[GROW-1392] Fixes crash and map UX for city guides

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx

During the bug bash I wanted to look into this: https://sentry.io/organizations/artsynet/issues/587358816/events/2fed3e7952624a95a408e8113d194e7b/?project=157493&query=is%3Aunresolved This Sentry error is a bucket for all "undefined/null is not an object" errors, which is annoying, but I wanted to look into this.
The code _should_ work:
```tsx
const { sale, sale_artwork } = artwork
const inRunningAuction = sale && sale_artwork && sale.is_auction && !sale.is_closed
if (inRunningAuction) {
const currentBid = sale_artwork.current_bid
return currentBid && currentBid.display
}
```
Like, it shouldn't crash. So what's up? Well I looked at the bundled Emission and it gets transpiled into this:
```tsx
var e = this.props.artwork,
t = e.sale;
if (t && t.is_auction && !t.is_closed) {
var a = …
```

Fixes spurious, intermittent crash from home feed

---

src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx

Used existing link that the consignments banner uses. Doesn't appear to open modally in Emission but behavior in Eigen should be the same as the banner and present modally. 
#trivial

[PURCHASE-1262] Consignment landing page should open in modal instead of as a new page sliding in

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/RegistrationResult.tsx
src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap

finishes https://artsyproduct.atlassian.net/browse/AUCT-472
This is a simple change, but there's a question of whether or not the icon should be removed: https://artsyproduct.atlassian.net/browse/AUCT-472, so let's wait until we know the answer.

WIP: AUCT-472: Update copy on registration pending view

---

CHANGELOG.md
src/__generated__/BidFlowSelectMaxBidRendererQuery.graphql.ts
src/__generated__/ConfirmBid_sale_artwork.graphql.ts
src/__generated__/QueryRenderersBidFlowQuery.graphql.ts
src/__generated__/SelectMaxBidRefetchQuery.graphql.ts
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx
src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx

finishes https://artsyproduct.atlassian.net/browse/AUCT-473
* Adds `image { url(...) }` to the GraphQL query to retrieve a URL to the `small` image of the artwork
* Replaces the `<Containers>` with a `<ScrollView>` so smaller screens can host all these elements without getting them squashed
* Updates tests, snapshots and storybooks to reflect the design change
* The `“A valid credit card is required for bidding.”` message has already been added as part of https://github.com/artsy/emission/pull/1730 so we get that for free everywhere else

Add image thumbnail to the confirm bid screen 

---

CHANGELOG.md
src/lib/Scenes/Artwork/Artwork.tsx

When integrated with Eigen, the Artwork component had a persistent 20px white bar on top. This PR fixes that by moving the spacing from the containing box to the padding of the scrollview itself.
| Before  | After  |
|---|---|
| <img width="559" alt="Screen Shot 2019-07-17 at 16 09 12" src="https://user-images.githubusercontent.com/498212/61408910-21200300-a8af-11e9-96a1-6c1b7ace2210.png">  | <img width="559" alt="Screen Shot 2019-07-17 at 16 08 08" src="https://user-images.githubusercontent.com/498212/61408917-25e4b700-a8af-11e9-98fb-0e3cf82e94e2.png">  |
And it looks good on iPhone X, too:
Although, it looks like Eigen is still adding a black bar at the top, under the notch. I'd bet this is because we're nesting the view controllers, so it'll be a change in Eigen to get those removed.

Fixes top padding on artwork view

---

src/lib/Scenes/Artwork/Artwork.tsx
src/lib/Scenes/Artwork/Components/CommercialInformation.tsx

While I was QAing I noticed a couple of bugs:
- Some artworks have non-public artists. We were failing to load pages in those cases due to a missing `biography_blurb`
- Added a `contentInset` which seems to be the way to add spacing after a `FlatList` (otherwise the bottom part of `OtherWorks` was being cut off).
- Fixed an issue where we had extra spacing if there was no "partner" line
Before:
After:
#trivial

Fixes odd spacing and one case where an artwork wasn't loading

---

src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx

__Before:__
__After:__
#trivial

[PURCHASE-1261] Artwork date should always appear on same line as title

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx

fixes https://artsyproduct.atlassian.net/browse/AUCT-499
blocked by https://github.com/artsy/emission/pull/1741
eThis is the actual fix for the bug. Basically the issue is that `result.position.id` was not replaced even after we switched to MP v2. As a result of this, `undefined` is passed on to the polling query which causes the server to return an error. This PR replaces all the occurances of `id` in the `<ConfirmBid>` component.
I have another PR that adds more type checks to mitigate the same type of risks: https://github.com/artsy/emission/compare/master...add-more-type-checks

Fixes an issue where placing a bid hangs

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx

finishes https://artsyproduct.atlassian.net/browse/AUCT-501
blocked by https://github.com/artsy/emission/pull/1742
tested with the diff of:
```diff
diff --git a/src/lib/Components/Bidding/Screens/ConfirmBid.tsx b/src/lib/Components/Bidding/Screens/ConfirmBid.tsx
index c001482c2..7222f6a07 100644
--- a/src/lib/Components/Bidding/Screens/ConfirmBid.tsx
+++ b/src/lib/Components/Bidding/Screens/ConfirmBid.tsx
@@ -294,7 +294,7 @@ export class ConfirmBid extends React.Component<ConfirmBidProps, ConfirmBidState
const { result } = results.createBidderPosition
if (result.status === "SUCCESS") {
-      this.bidPlacedSuccessfully(result.position.internalID)
+      this.bidPlacedSuccessfully(result.position.id)
} else {
this.presentBidResult(result)
}
@@ -317,7 +317,7 @@ export class ConfirmBid …
```

Display an error message when polling fails

---

Pod/Classes/ViewControllers/ARArtworkAttributionClassFAQViewController.m
src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
src/lib/Scenes/ArtworkAttributionClassFAQ/__tests__/ArtworkAttributionClassFAQ-tests.tsx

In the Availability section, we want to update the spacing between availability, partner name, and consignment link according to the spec below. We also need to adjust the font size for the consignment link down to Sans2 (12px size / 16px line-height)
__Before:__
__After:__
For auctions (bidding closed state), when partner name is not available, we should move the consignment text up (20px spacing between “Bidding Closed” and “Want to sell a work by this artist?…”)
No changes made. Outer wrapper padding has been removed from child components already
Added safeAreaInsets to Artwork Attribution Class FAQ page and adjusted padding to Sam's specifications.
#trivial

[PURCHASE-1328, PURCHASE-1257, PURCHASE-1349] Small changes to padding and font size 

---

CHANGELOG.md
src/lib/Components/RetryErrorBoundary.tsx
src/lib/Components/__tests__/RetryErrorBoundary-tests.tsx
src/lib/Components/__tests__/__snapshots__/RetryErrorBoundary-tests.tsx.snap
src/lib/Scenes/Artwork/Artwork.tsx

This PR adds a new RetryErrorBoundary component and uses that component to wrap the Artwork page in a `LoadFailureView`. I settled on the same approach that `QueryRenderer` itself uses (a `render` prop) but I'm open to feedback on the component name and its API. This should work with a modified `renderWithProgress` that will show a [custom skeleton loading page](https://artsyproduct.atlassian.net/browse/PURCHASE-1278).
This PR is a work-in-progress because:

WIP: [PURCHASE-1276] Adds RetryErrorBoundary, adds to Artwork page

---

CHANGELOG.md
Example/Podfile.lock
src/lib/Components/Home/ArtistRails/ArtistCard.tsx
src/lib/Components/Home/ArtistRails/__tests__/__snapshots__/ArtistCard-tests.tsx.snap

[Artist/Card] Fix shadow and performance warning.

---

CHANGELOG.md
src/lib/Components/Bidding/Components/Input.tsx
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap

During last week's Auctions QA session, I tried to register for a sale on an iPhone. I realized that the billing address inputs lacked `textContentType`, which is a property that tells iOS what data goes in each input field. This allows users to tap (for example) their name to get it input into the name field; this drastically improves the user experience of entering an address. 
Here's what it looks like in the simulator (`SIM-VALUE` would be replaced by the user's actual data, on-device): 
During this work, I noticed that the `StyledInput` component was not well-typed, so I added some type annotations to get type-checking and autocomplete working:

Add input textContentType for registration BillingAddress

---

CHANGELOG.md
Example/Podfile.lock
src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx
src/lib/Components/__tests__/Markdown-tests.tsx
src/lib/utils/renderMarkdown.tsx

**Tested on-device!**
We found that `mailto` links (included in markdown) were causing the app to crash when clicked into.
`mailto` links need to be handled differently than normal links. This PR updates our `markdownRenderer` to correctly call the `Linking` react-native module when a mailto link is provided.

PURCHASE-1309: Fixes mailto links rendered in markdown

---

CHANGELOG.md
Example/Emission/AppDelegate.m
Pod/Classes/Core/ARSwitchBoardModule.h
Pod/Classes/Core/ARSwitchBoardModule.m
package.json
src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
src/lib/Components/ArtworkGrids/GenericGrid.tsx
src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/lib/NativeModules/SwitchBoard.tsx

This PR removes the concept of an "artwork set", which is used by Eigen to provide left-to-right swiping between artworks in a grid. 
This is a companion PR to https://github.com/artsy/eigen/pull/2884, which it is blocking. 

[PURCHASE-1143] Removes artwork set functionality

---

CHANGELOG.md
Pod/Classes/ViewControllers/ARMediaPreviewController.m
package.json

I've included a comment here to explain what's up. Here's the Sentry crash: https://sentry.io/organizations/artsynet/issues/1025682704/?project=157493&query=is%3Aunresolved

[PURCHASE-1316] Fixes intermittent crash on opening message attachment previews

---

src/lib/Scenes/Artwork/Components/ContextCard.tsx
src/lib/Scenes/Artwork/Components/__tests__/ContextCard-tests.tsx

- https://artsyproduct.atlassian.net/browse/PURCHASE-1409
- Fixes context card with new `__typenames` which was creating empty space
#trivial

PURCHASE-1409 - Fixes ContextCard with new MPv2 typename field

---

src/lib/Scenes/Artwork/Components/ArtworkActions.tsx

https://www.notion.so/artsy/View-in-Room-shrink-image-551dd04f9efd4e4c8f58a20a6ebc795c
Artworks appear stretched and distorted when using view in room
We were passing height and width to presentAugmentedRealityVIR in the wrong order. I switched them and corrected the problem.
__Before:__
__After:__
[PURCHASE-1407]: https://artsyproduct.atlassian.net/browse/PURCHASE-1407
#trivial

PURCHASE-1407: Artwork dimensions distorted in view in room

---

src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx

- https://artsyproduct.atlassian.net/browse/PURCHASE-1436
- Checks for dimensions and materials before rendering `Sans` element
#trivial

PURCHASE-1436 - Small tombstone fix

---

Pod/Classes/Core/ARDynamicScreenDimensions.m
src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomView.tsx
src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/__tests__/ImageCarouselFullScreen-tests.tsx
src/lib/Scenes/Artwork/Components/ImageCarousel/geometry.ts

Couple of small things
1. Screen dimensions updates seemed to be subject to a race condition on my iPad simulator at least. Calling `getScreenDimensions` synchronously with the `orientationChanged` callback was returning the pre-rotation values. So i moved the call onto the main thread right before the event is fired across the bridge.
2. Images whose maximum resolution is smaller than the viewport were being blown up to fill the screen in the full screen carousel. On iPad this could look *really* bad so I prevented it from happening.
#trivial

Carousel fixes

---

Example/Emission/ARRootViewController.m
src/lib/Scenes/Artwork/Components/CommercialEditionSetInformation.tsx

- Edition set selection was rendering off page, adds wrap to the flex wrapper to allow the edition sets to wrap
#trivial

Fixes edition set wrap

---

src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx

[PURCHASE-1358]
Back button and bottom nav were overlapping the attribution class FAQ. I added more padding to its container.
__Before:__
__After:__
[PURCHASE-1358]: https://artsyproduct.atlassian.net/browse/PURCHASE-1358
#trivial

[PURCHASE-1358] Attribution class FAQ is cut off

---

CHANGELOG.md
src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
src/lib/Components/ArtworkGrids/GenericGrid.tsx

Follow-up from https://github.com/artsy/eigen/pull/2896 We have been incorrectly tracking `tap` events on GenericGrid's layout events. This PR moves the tracking to the `ArtworkGridItem`, including passing down some props for tracking from `GenericGrid`. I've verified that this is working in Eigen, running these local Emission changes.

[PURCHASE-1414] Removes errant tap events tracking on scroll layout

---

Pod/Classes/OpaqueImageViewComponent/AROpaqueImageViewManager.m
src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
src/setupJest.ts

https://artsyproduct.atlassian.net/browse/PURCHASE-1411
This is a potential fix for the issue where only the first two images were loading for people in certain situations.
Without being able to reliably reproduce the issue we need to make guesses about what's causing it.
The image carousel is implemented as a FlatList which initially only renders two items, and then is supposed to start rendering more items as the user starts scrolling.
One possible problem is that the FlatList is not rendering further items as the user scrolls.
<em>Note: given what I saw over zoom in the QA session I suspect this could have been the case, because the background remained completely white rather than showing a 'loading' placeholder as it would have done if the images were simply taking too long to …

PURCHASE-1411 Prefetch images

---

Pod/Classes/OpaqueImageViewComponent/AROpaqueImageView.m
Pod/Classes/OpaqueImageViewComponent/AROpaqueImageViewManager.m
src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
src/lib/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx
src/setupJest.ts

This reverts #1835 😬 That PR was fine, it's just that to really squash this bug I want to try a different approach. This PR achieves the same effect of preloading all carousel images, but while also _rendering_ all images.
After talking to @alloy I became convinced that preloading alone would not solve the issue we have seen, and that the problem is almost certainly `FlatList` which has been allegedly quite buggy historically, especially around whether or not lazily-rendered items appear.
The evidence I have for this is that both times when this kind of bug has appeared and I have seen it with my own eyes, the loading 'placeholder' background was not being show. It was just white. If this issue were caused by not prefetching images, we would expect to see a grey box with a loading spinner …

Render all carousel images

---

src/lib/utils/renderWithLoadProgress.tsx

Follow up from artsy/metaphysics#1936
The above issue was tricky to debug because the error was being swallowed by `renderWithLoadProgress`.
`renderWithLoadProgress` does invoke `console.error` but only for errors with a specific shape. It turned out that our error yesterday didn't match that shape. So I moved the `console.error` invocation to make it more inclusive for _all_ errors 🌈 
#trivial

Report all data load errors when not in tests

---

src/lib/Components/Bidding/Screens/BillingAddress.tsx

Currently, clicking "Next" to navigate to the next field in the bid flow's billing address form causes the app to crash with the error `RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 't.addressLine1.root.focus')`
Fixed it by removing the reference to `root`. This component hasn't been touched meaningfully in a while, so I'm not sure what made this break all of a sudden.
#trivial

PURCHASE-1464 [BidFlow] Fixes bug when clicking Next between fields in Billing Address form

---

scripts/ci-skip-native-if-possible.js

I noticed that #1837 (which has only JS changes) was running native CI ([in this build](https://circleci.com/gh/artsy/emission/2823)). We have a yarn script to skip native CI on pull requests that have no native code changes, but it wasn't working. What was happening was, if native code got changed on master, that would "count" as a changed native file on every PR (unless they rebased). This change restricts the git diff to the most common ancestor commit of the PR's branch (ie: the commit it branched off of master from). #trivial

Restricts git diff range on CI skip check

---

src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx

@kierangillen saw some crashes in the app when staging was flaky that were related to certain artworks not having full image data. Here we add a fail-safe so the app will not crash if that happens again, it will just not render any images.
https://artsyproduct.atlassian.net/browse/PURCHASE-1484
#trivial

PURCHASE-1484 prevent crashes when staging image data is corrupt

---

src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx

As @alloy pointed out on slack, some iOS devices have a pixel ratio of 1:3 so we should ask the user's device how much to scale the image by.
#trivial

Use screen pixel density rather than constant

---

src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/DeepZoom/deepZoomGeometry.ts

in #1863 we updated the image carousel thumbnail to use the device's pixel ratio to decide image resolution, but forgot to update the deep zoom overlay to do the same. This PR basically makes it so that if you zoom in (either very slowly or with perfect network) you can't tell when one layer ends and the other begins. Whereas before there would be noticeable points while zooming when the image would become more detailed.
#trivial

Adjust deep zoom levels for pixel ratio changes

---

src/lib/Scenes/Artwork/Components/CommercialInformation.tsx

- We had not updated the logic in the parent component when to show `ExtraLinks` now that we're no longer showing if the artwork only has `isInquireable`
#trivial

Fixes empty space in Artwork view

---

src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx

> Analytics fix: In the artwork tombstone, the action_name for clicking on an artist name should be "artistName", not "artworkClassification"
#trivial

Fix analytics bug

---

CHANGELOG.md
src/lib/Scenes/Home/index.tsx

Fixes https://artsyproduct.atlassian.net/browse/PLATFORM-1781
Re-applies #1866, which was accidentally reverted here https://github.com/artsy/emission/commit/5b0ea4cf316a1ccd5d16c86444741db17d5309d8#r35129124

[Home] Stop scroll-to-top behaviour on Artists/Auctions tabs.

---

src/lib/Scenes/Artwork/Components/AuctionPrice.tsx

__Before:__
__After:__
#trivial

[Design Tweak] If no information on reserve or max bid (smaller text below 'starting bid') move the rest of the content up

---

CHANGELOG.md
src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
src/lib/tests/mockTracking.ts
src/lib/utils/track/schema.ts

https://artsyproduct.atlassian.net/browse/PURCHASE-1486
Added `@track` around few auction related actions based on ☝️ 
`BidButton` logic was little complicated and hard to read, ended up consolidating some checks in one place and also tried to break `render` to call two other renders in `if` statement.
Let me know if there is a better way to make this more readable and if my changes don't help.
#skip_new_tests (for existing schema.ts file)

Track more auction events

---

CHANGELOG.md
src/lib/Components/Consignments/Submission/__tests__/consignmentSetupToSubmission-tests.ts
src/lib/Components/Consignments/Submission/consignmentSetupToSubmission.ts

Tracked here: https://www.notion.so/artsy/Consignments-that-specify-an-edition-without-an-edition-size-crash-the-app-206bd7177f654660a5f03208edf81839
I also updated the unit test to use Jest's new inline snapshot checking.

[PURCHASE-1520] Fixes submitting a consignment with a missing edition size

---

CHANGELOG.md
src/lib/Scenes/Artwork/Artwork.tsx

Tracked here: https://www.notion.so/artsy/When-viewing-a-modal-i-e-the-Attribution-Class-one-going-back-to-the-artwork-page-triggers-a-ref-295d8c5c0d204f748ee1da194fa4c607

[PURCHASE-1519] Fixes issue where the Artwork page would show a refresh animation on re-appear

---

CHANGELOG.md
src/lib/Scenes/Favorites/Components/Artists/index.tsx

#1901 added some safety to our use of image URLs (specifically, accessing `something.image.url` would crash if `image` was `null`). Looking closer at the [crash](https://sentry.io/organizations/artsynet/issues/1250975276/) [logs](https://sentry.io/organizations/artsynet/issues/1250975252/), we see that the query response that causes these crashes is `b108ebed90e257a8a29d53a085165670`, the `ArtistsMeQuery` query. The component uses a function that restructures its arguments in a way that causes a crash if `image` is `null`, so it seems like our likely source. The function was actually destructing more than it had to (and re-structuring to pass parameters into a child component) so the fix was simple:
```diff
renderItem={({
item: {
href,
-            image: { url },
+            image, …
```

Fixes crash with missing artist images

---

CHANGELOG.md
src/lib/Components/ReadMore.tsx
src/lib/Components/__tests__/ReadMore-tests.tsx

- Uses em dash between text instead in unexpanded text in `ReadMore` component
- https://artsyproduct.atlassian.net/browse/PURCHASE-1540

PURCHASE-1540 -  Uses em dash between text in ReadMore

---

src/lib/Components/RetryErrorBoundary.tsx
src/setupJest.ts

https://artsyproduct.atlassian.net/browse/ME-17
#trivial 
There's a separate method for capturing `Error`s called `Sentry.captureException` but I found that the stack trace disappeared when using that method 🤔 So I decided to just capture the stack trace as a string. We'll need to figure out why the stack trace is disappearing if we ever want to set up symbolication for eigen (that's where you tell sentry about the source maps for your js bundle so it can replace bundled JS line numbers with source TS line numbers)

ME-17 Send RetryErrorBoundary errors to sentry

---

src/lib/Components/Inbox/Conversations/Messages.tsx

This was using the relay node ID instead of the impulse conversation ID
#trivial

Fix query for messages list in conversation

---

docs/adding_new_components.md

This updates the docs for adding new components. The biggest change is just that the docs indicate they are a guide, rather than a tutorial. That is to say, they explain how to do this in general, rather than give specific code that can be copy and pasted.

Updates docs for adding new components

---

CHANGELOG.md
src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx

Fixes [PURCHASE-1600](https://artsyproduct.atlassian.net/browse/PURCHASE-1600)
Before:
After:
The spacing between the sections were complex so for the sake of not breaking the layout for other variations of the screen lifted the logic up to the parent component.

No 'Contact Gallery' Button for artwork in closed auction

---

CHANGELOG.md
src/lib/Scenes/Artwork/Components/AuctionCountDownTimer.tsx
src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
src/lib/Scenes/Artwork/Components/__tests__/AuctionCountDownTimer-tests.tsx
src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
src/lib/__fixtures__/ArtworkBidAction.ts

Addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-1597
Before:
There are a few issues with the above image:
- We should not be showing the "availability" message and corresponding partner information for this case.
- We should be showing the timer (at 0, with `In progress` as the label)
- We should be correctly showing `Enter live bidding` vs. `Watch live bidding`
I confirmed that out logic for when to show `Enter` vs. `Watch` is correct, so I suspect the original bug report was due to weirdness around auction state transitions. 
When I am able to register OR already registered:
When I am not able to register:

Fixes a few issues on the artwork view while auction is open for live bidding

---

CHANGELOG.md

This PR updates entries from #1920, #1921, and #1924, which had been entered into the already-released 1.18.0 version. New changelog entries should always go in the `### Master` section. To help with this, I simplified the comment at the top, but we could add a Danger rule if it would help, too. 
I also added ticket numbers to the entries, [following last week's announcement](https://artsy.slack.com/archives/C02BAQ5K7/p1571323993074300).
/cc @sweir27 @ashkan18

Fixes changelog and updates instructions #trivial

---

Example/Emission/ARLabOptions.m
src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx

Just to get aligned with https://github.com/artsy/eigen/pull/2934 so we don't have to do extra key conversion for feature flagging in multiple platforms.
#trivial #skip_new_tests

Rename enablePriceTransparency to AROptionsPriceTransparency for consistency

---

src/lib/Components/ReadMore.tsx
src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
src/lib/Scenes/Artwork/Components/__tests__/ArtworkDetails-tests.tsx

| Before  | After  |
|---|---|
| ![Screen Shot 2019-10-30 at 10 48 13](https://user-images.githubusercontent.com/498212/67871526-dd23d780-fb06-11e9-8412-cdbbe0d8c9e4.png) | ![Screen Shot 2019-10-30 at 10 47 57](https://user-images.githubusercontent.com/498212/67871515-d9905080-fb06-11e9-8b21-95ca1df9370d.png) |

[PURCHASE-1545] All artwork details subfields have a ReadMore link

---

CHANGELOG.md
src/lib/Components/Bidding/Screens/ConfirmBid/PriceSummary.tsx
src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap

(sort of) addresses https://artsyproduct.atlassian.net/browse/AUCT-692
For some reason the loader started working fine... I just needed to add a bit of `margin-top` to make it look a little nicer. I didn't know what else to do so I just added some typos to the branch name `loaoeader`.

Adjust the loader position for <PriceSummary>

---

src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx

Couldn't help myself, my curiosity got the better of me.
This bug runs deeper than Airdrop, but that's where we saw it first. Users sharing artworks to other iOS or macOS devices were sending a _text file_, which is *not* QWoA at all. So what was going on?
Our previous work on sharing had us doing a lot of semantic construction before passing the content on to iOS to actually share. This is an anti-pattern; the iOS share API is designed to be given a URL, title, and message so that the OS can massage that data into whatever semantic representation makes sense for the share destination the user picks.
That is to say, instead of computing a string `title` with the artwork title, artist names, and URL all in that string, we should be sending an object with that data to let the OS render …

[ME-37] Fixes iOS Share Sheet invocation

---

src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx

addresses https://sentry.io/organizations/artsynet/issues/1351246099/\?project\=166818\&query\=is%3Aunresolved
In the TestFlight version  6.1.0 (2019.11.22.8) I noticed that updating a feature flag to `false` on https://echo-web-production.herokuapp.com/accounts/1/features/14 would cause a crash on the Confirm Bid screen in Emission. After some digging I noticed that the boolean `false` value in Echo would end up being `0` in the iOS world (which is understandable given that some languages treat `0` as a falsy value).
Normally this wouldn't cause any problems, but because of the way the conditional is written, this was causing a crash:
```tsx
enablePriceTransparency && <Component>
```
this one-liner was returning `0` and React tried to render the `0` as a text anyway, but in React Native …

Fixes an issue where the feature flag of '0' causes a crash

---

Example/Podfile.lock
src/lib/utils/renderMarkdown.tsx

- https://artsyproduct.atlassian.net/browse/MX-116
- Wraps the returned markdown in a `Text` element. In some edge cases React-native would crash due to text not being in a text component.

MX-116 - Fixes markdown bug causing Artwork crash

---

Pod/Classes/ViewControllers/ARArtworkComponentViewController.h
Pod/Classes/ViewControllers/ARArtworkComponentViewController.m

- Exposes `artworkID` for Eigen #native_no_changes

Updates emission VC to expose artworkID

---

Example/Podfile.lock
package.json
yarn.lock

We need to point to point to our fork of `tipsi-stripe` because we pulled in [this fix](https://github.com/tipsi/tipsi-stripe/pull/508) for [this issue](https://github.com/tipsi/tipsi-stripe/issues/408) (it'll be included in an upcoming release of `tipsi-stripe`, so I'm fine still pointing to my own fork). Previously, we did this in Eigen, but was removed in the RN upgrade infrastructure PR:
https://github.com/artsy/eigen/pull/2962/files#diff-4a25b996826623c4a3a4910f47f10c30L101
This was causing the bug (app crashes when entering credit card number) to re-occur.
This adds it back, using that new infrastructure mechanism. I took a look at the other RN pods that we were pointing to forks on, and it appears all the changes we'd made are now included in their upstreams, so we're good to go 🙌

Points to our fork of tipsi-stripe #trivial

---

dangerfile.ts

I was reviewing #1999 and noticed the "skip new tests" hashtag to avoid the Danger rule. We've been doing that a lot, and it got me thinking about the purpose of the rule itself.
According to the comments in the Dangerfile, the rule is really intended only for _new files_, but _modified files_ were being included in the check too. A comment above alludes to the fact that they're most interchangeable – but in my opinion, the check for new tests is not one of those times.
I've changed the Dangerfile to only check for new files, while leaving existing variables so that future rules can use them.
After merging this PR, the new-tests rule won't triggered spuriously, so we will all need to adjust our barometers for when it makes sense to add "skip new tests" to our PR descriptions 👍

Updates Danger rule for adding tests for new files

---

src/lib/Components/Artist/ArtistHeader.tsx

https://artsy.slack.com/archives/CN8S32FJR/p1576238196078900

Fix artist header when `bylineRequired` field is an empty string.

---

src/lib/Components/Inbox/Conversations/Messages.tsx

https://artsyproduct.atlassian.net/browse/MX-75
The problem was just that we were calculating the height of the flatlist in a really naive way.

[MX-75] fix scroll to bottom in conversations

---

.circleci/config.yml
docs/adding_a_lab_option.md
docs/developing_a_feature.md

This has been on my TODO list from the Front-End iOS Practice and conversations with @yuki24 in https://github.com/artsy/eigen/pull/2934#issuecomment-547111199 , I've updated the docs around lab options and Echo Features. I've tried to explain both the _why_ and the _how_, framed in terms of developing new features.

Adds documentation for releasing iOS features

---

.circleci/config.yml

Matches the change made here: https://github.com/artsy/emission/commit/5187b967414872b82fd525c1a51503172c967d1e
I think this was caused when we upgraded Circle CI machines a few weeks ago (though I'm not sure why it only started failing today). The issue was we were installing a specific version of Bundler to get around [a bug](https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html) with Bundler. Since we're on a new enough version by default on the CI machines, I took out the explicit installation step (which was failing while waiting for user input to confirm replacing the already-installed version).

Removes bundler installation from deploy job

---

src/lib/Components/Consignments/Screens/Overview.tsx
src/lib/Components/Consignments/Submission/geminiUploadToS3.ts

Show an error alert and allow retry rather than crash on unhandled JS Exception.
Copy in screenshot is out of date - updated copy is:
"Sorry, we couldn't upload your images."  - (Removed optional s)
"Please try again or contact consign@artsy.net for help."
The error alert looks like this:

[MX-70] - Guard against S3 upload crash

---

Pod/Classes/ViewControllers/ARCollectionComponentViewController.m

Update the full-bleed method to return `true` enabling the collection header image to extend to the top of the iOS devices' viewport rather than being cut off by the status bar.
Screenshots with various collection headers below:

Adds full bleed to collections header

---

dangerfile.ts

We're seeing a Danger failure in this PR because I added a new mock, and Danger is insisting we write a unit test _for that mock_: https://github.com/artsy/emission/pull/2027
It's expecting that `src/lib/Scenes/Settings/__mocks__/LoggedInUserInfo.tsx` has a corresponding `src/lib/Scenes/Settings/__mocks__/__tests__/LoggedInUserInfo-tests.tsx` test file. This update excludes mocks from the Danger rule.
EDIT: Forgot to say that I tested this change locally using `DANGER_GITHUB_API_TOKEN=MY_PERSONAL_ACCESS_TOKEN yarn danger pr https://github.com/artsy/emission/pull/2027` and it works 👍

Excludes mocks from requiring their own unit tests

---

.circleci/config.yml

#2026 upgraded Xcode 11, which required Circle to install Node 12. I forgot to include this installation in the deploy job. Since the other PR was already reviewed, I'm marking this as #mergeongreen right away to unblock deploys.

Installs Node 12 on deploy build #trivial

---

src/lib/Components/Artist/ArtistShows/Metadata.tsx
src/lib/Components/Artist/ArtistShows/__tests__/ArtistShow-tests.tsx
src/lib/Components/Artist/ArtistShows/__tests__/__snapshots__/ArtistShow-tests.tsx.snap

Added a null check similar to partner name check to prevent crash. 
This is what component looks like with showTypeString:
and without:

[MX-135] - Null checks for optional show.kind metadata

---

src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap

This PR fixes a bug where the collection header image URL was being reformated in Gemini both on the server and the client, thus creating an invalid URL.
[Links to FX-1742](https://artsyproduct.atlassian.net/browse/FX-1742)

Fixes bug causing image to fail to render in collection header

---

.circleci/config.yml

Since #1781, we have been downloading CocoaPods specs from the CDN instead of using the Specs repo. That means that this setup step is no longer required, but is still taking up CI time.
Also, Prettier made some changes to the yaml file, so, sure!

Removes CocoaPods Specs repo setup

---

src/lib/Containers/Artist.tsx

https://artsyproduct.atlassian.net/browse/MX-96
companion for artsy/eigen#2995 — removes one final redundant screen view event.

[MX-96] Remove redundant screen view tracking for Artist page

---

src/lib/Containers/Artist.tsx

This is a follow-up to https://github.com/artsy/emission/pull/2058 . Without decorating the top-level component with either `@screenTrack()` (which generates tracking events itself) or `@track()` (which exposes the tracking capabilities to the component tree, but doesn't itself track events), then the component tree will fail to render. I've verified this still keeps fixes the duplicate artist screen tracks 👍 
Going to self-merge so we have a workable beta for the weekend.

Fixes issue with Artist tracking components #trivial

---

src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
src/lib/Scenes/Collection/Components/__tests__/FeaturedArtists-tests.tsx

https://artsyproduct.atlassian.net/browse/FX-1729
QA fix: adds a missing bit of the tracking payload, as noted in the ticket discussion.

Add missing event type for Collections' view-more-artists interaction

---

src/lib/utils/volleyClient.ts

Was going through sentry and noticed a lot of noise from these volley client errors. i don't know why volley is failing so often, but the noise is due to the stack trace being included in the error message rather than as metadata. Sentry identifies errors by the message so different messages means different errors. This PR should group them by http status.

reduce volley client error message noise in sentry

---

src/lib/Scenes/Collection/Components/FeaturedArtists.tsx

This PR updates a single analytics constant for the FeaturedArtist follow/unfollow events within the Collection page, per @abhitip's feedback on https://artsyproduct.atlassian.net/browse/FX-1747.

Update analytics constant for Collection/Featured Artists

---

package.json
src/lib/Scenes/Search/SearchResult.tsx
src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx
yarn.lock

https://artsyproduct.atlassian.net/browse/MX-126
~On hold while we have a RFC for this new dependency, `grapheme-splitter` #2072~

[MX-126] highlight diacritics in search results

---

src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap

Addresses https://artsyproduct.atlassian.net/browse/FX-1789 by specifying a right margin on the title of the collection screen.
Before this change: 
After this change:

[FX-1789] Add right margin to collection title

---

scripts/update-metaphysics-and-eigen.js

yesterday we needed to manually edit an existing query in MP's persisted query map. Unfortunately after deploying emission it overwrote that manual change because that's how emission updates the MP query map during it's deploy job on CI.
here we change the logic so that it preserves the MP version as the source of truth.
see artsy/metaphysics#2160 #2075 and https://artsy.slack.com/archives/CN8S32FJR/p1581001886215700 for context

Preserve changes made manually to the MP query map

---

src/lib/AppRegistry.tsx
src/lib/Scenes/Artwork/Artwork.tsx
src/lib/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx
src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
src/lib/Scenes/Artwork/__tests__/__snapshots__/Artwork-tests.tsx.snap
src/lib/utils/__tests__/placeholders-tests.tsx
src/lib/utils/__tests__/renderWithLoadProgress-tests.tsx
src/lib/utils/__tests__/renderWithPlaceholder-tests.tsx
src/lib/utils/placeholders.tsx
src/lib/utils/renderWithLoadProgress.tsx
src/lib/utils/renderWithPlaceholder.tsx

first part of https://artsyproduct.atlassian.net/browse/MX-158, adding a placeholder loading screen for the artwork page.
next task is to spike on splitting the page query into above-the-fold and below-the-fold content.

[MX-158] add placeholder loading state for artwork page

---

src/lib/Components/ReadMore.tsx
src/lib/Scenes/Artwork/__tests__/__snapshots__/Artwork-tests.tsx.snap
src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap

https://artsyproduct.atlassian.net/browse/FX-1748
This simply updates `ReadMore` to use font size `3` instead of `3t` (i.e. the <b>t</b>ightly-spaced variant)
I was curious why this component was spec'd with `3t` size to begin with, so I did the Github and Jira archaeology to find:
- https://github.com/artsy/emission/pull/1654, which implements:
- https://artsyproduct.atlassian.net/browse/PURCHASE-1139, which includes the comp:
- https://app.zeplin.io/project/5ab94282c124db8d58365b47/screen/5cdb43f2b4655d1e7436ca1a
From there I can see that this component was 16/24 serif which does in fact [map to size 3](https://www.notion.so/artsy/Typography-42e0e8e4f4e34ccc84c7de7adcd1b519)
I figure this was an oversight that just persisted till now, so I think this change should be good to go, and …

[FX-1748] Fix line-height in ReadMore component

---

Example/Emission/ARLabOptions.m
src/lib/Components/FilterModal.tsx
src/lib/Components/__tests__/FilterModal-tests.tsx
src/lib/Components/__tests__/__snapshots__/FilterModal-tests.tsx.snap
src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
src/lib/Scenes/Collection/Collection.tsx
src/lib/Scenes/Collection/__tests__/Collection-tests.tsx
src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap

This PR combines #2067 and #2068 into a single branch to support building the collections artwork filter container as outlined in [FX-1474](https://artsyproduct.atlassian.net/browse/FX-1474)
Includes:
- [Modal overlay](https://artsyproduct.atlassian.net/browse/FX-1765)
- [Conditionally rendering filter button](https://artsyproduct.atlassian.net/browse/FX-1763)
- [Modal overlay closes by selecting Close icon + when clicking outside of the modal area](https://artsyproduct.atlassian.net/browse/FX-1766)
- [Hides filter button + modal overlay behind feature flag](https://artsyproduct.atlassian.net/browse/FX-1796)
**With Feature Flag Enabled (Modal Visible)**
**With Feature Flag Disabled (Modal Not Visible)**

Collections Artwork Filter Container

---

src/lib/Scenes/Favorites/index.tsx

I was surprised to have to pass in explicit `width` and `height` props, instead of using CSS. Must be a weird React Native SVG thing.

[MX-170] Increases Settings icon size

---

src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx

https://artsyproduct.atlassian.net/browse/MX-161
Tiny bugfix for a rare situation where the event data we get after a gesture ends doesn't seem to make sense.

[MX-161] Return early if event data doesn't make sense
